### ISSUE TITLE
Missing firmware T495 0.1.27

### ISSUE THREAD

**Issue by speachy** [fwupd/firmware-lenovo#100]
Released 2021-01-19

https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t495-type-20nj-20nk/downloads/ds539877-bios-update-utility-bootable-cd-for-windows-10-64-bit-thinkpad-t495

**Comment by kmauleon** [comment]
hi @speachy ... sorry for the delay.  please see below as per BIOS team
**The system BIOS 1.27 waiting for our UT test, we will release this BIOS on LVFS web site about on 3/8.**

**Comment by applesun123** [comment]
BIOS firmware 1.27 is ready on LVFS web site.

**Comment by speachy** [comment]
Thank you for getting this up!
