### ISSUE TITLE
udevd: Unknown key identifier 'zoom'

### ISSUE THREAD

**Issue by joakim-tjernlund** [fwupd/firmware-lenovo#106]
I get this on my new T14 (20S0000FMX) and figured this might be a FW issue with keycode mapping?

**Comment by ktnlikeasmallcat** [comment]
also happens on T410

**Comment by Zeitsperre** [comment]
I'm seeing this on a T430 as well

**Comment by hughsie** [comment]
I think you need to file this with systemd or the kernel I'm afraid -- I don't think it's anything to do with fwupd or the *process* of firmware updates.
