### ISSUE TITLE
Black screen after starting `fwupdx64.efi` on Lenovo P70 (Arch Linux)

### ISSUE THREAD

**Issue by sedrubal** [fwupd/firmware-lenovo#121]
#### Describe the bug
When I start a firmware update (Intel Management Engine) with `fwupdx64.efi`, and reboot into the UEFI updater, it results in a black screen. When I press the power button of my laptop I can hear a beep code (`- - . . .` / long long short short short). I guess it is signaling, that I should not interrupt the process. The fans are ventilating. After waiting some minutes, nothing happens. When I restart using <kbd>Ctrl</kbd> + <kbd>Alt</kbd> + <kbd>Backspace</kbd> and run `fwupmgr` it tells me, that the updater did not run.

#### Steps to Reproduce
- Use a Lenovo P70 (20ER003SGE) with Arch Linux
- `fwupdmgr update`
- update `Intel Management Engine` from `184.80.3746` to `184.83.3874`
- press <kbd>y</kbd> when it asks to reboot
- After rebooting, you can read `Resetting`
- Then the device reboots again, fans turn on and the screen is black

#### Expected behavior
At this point I expect the fwupmgr UEFI updater to display a progress bar on the screen (as it did on previous updates) and the Intel ME gets updated. When it is done, the device should reboot into the system.

#### fwupd version information

<details>
<summary><code>$ fwupdmgr --version</code></summary>
<pre>
$ fwupdmgr --version
client version: 1.6.0
compile-time dependency versions
        gusb:   0.3.6

daemon version: 1.6.0
</pre>
</details>

Source: `pacman`

#### fwupd device information

<details>
<summary><code>$ fwupdmgr get-devices --show-all-devices</code></summary>
<pre>
$ fwupdmgr get-devices --show-all-devices
20ER003SGE
│
├─GM107GLM [Quadro M600M]:
│     Device ID:          ce4c74a5188d5b9cdb1e72ed32dad2d313c1c999
│     Current version:    a2
│     Vendor:             NVIDIA Corporation (PCI:0x10DE)
│     GUIDs:              d1079796-02ba-50d9-a8ce-c76519d255b5
│                         768699a7-ad1c-5ce2-9c6b-ae097ba2229c
│                         34e50bcd-a9d7-5468-b2ee-e77de378dee7
│                         1ff39d65-6601-5e0e-8f67-355725c82003
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─HD Graphics 530:
│     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
│     Current version:    06
│     Vendor:             Intel Corporation (PCI:0x8086)
│     GUIDs:              84a4dbbc-4a5f-57e7-980a-775bfb35ba11
│                         49ab06cd-bdd1-5e47-a843-9ace3766777d
│                         fb0e4398-241c-5c36-ab78-398aa4ed66e5
│                         be415cfb-b50d-5724-9483-7a56f16d0d70
│     Device Flags:       • Internal device
│                         • Cryptographic hash verification is available
│   
├─INTEL SSDSCKKF256H6L:
│     Device ID:          5dbeb140337f610d54913c0f43d15fdaa0eafb51
│     Summary:            ATA Drive
│     Current version:    LBFL11P
│     Vendor:             Intel (ATA:0x8086|OUI:5cd2e4)
│     GUIDs:              a6af6710-9837-5f0d-8ca2-405f259ce5f6
│                         38bae1a4-d6a2-5ab4-84a2-d90d93084106
│                         983c4c4a-a661-57ac-a5a4-a8bb8b37b2ed
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel Management Engine:
│     Device ID:          118ec9ef6f590ae68fae0026096cb21882481627
│     Current version:    184.80.3746
│     Minimum Version:    184.80.3746
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUIDs:              9b0578cf-f035-4fe8-b6ae-42591c946c36
│                         d7b47f59-ab20-51b8-9261-d68741f61e09
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel(R) Core™ i7-6700HQ CPU @ 2.60GHz:
│     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Current version:    0x000000e2
│     Vendor:             Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f
│                         30249f37-d140-5d3e-9319-186b1bd5cac3
│                         215d01de-fd1a-57cf-9153-72e29c0b7ffe
│                         c944e5cd-430c-5731-a9d5-c1b63c61cf27
│     Device Flags:       • Internal device
│   
├─Samsung SSD 850 EVO 500GB:
│     Device ID:          64ec4cd1e1c9565e79b00f4e7221b1c689b33e96
│     Summary:            ATA Drive
│     Current version:    EMT02B6Q
│     Vendor:             Samsung (ATA:0x144D|OUI:002538)
│     GUIDs:              4f91c57f-0080-5f61-95b8-c54899cc39cb
│                         086811eb-c412-5a0b-a319-7c37d3dd3e46
│                         967c50bf-25a0-5394-b21d-5939967dade6
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│ │   Device ID:          584bb826ddd562b072efe306596b05d0ae9a29f5
│ │   Current version:    0.2.32
│ │   Minimum Version:    0.2.19
│ │   Vendor:             LENOVO (DMI:LENOVO)
│ │   GUIDs:              df91783d-a03d-485a-9a8e-a3f39067f18e
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       603eb043-4f1d-5538-9d3a-9923b4d07b34
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─Intel AMT [unprovisioned]:
│       Device ID:        e2623122c99d58220498aacbfcfdb1baebbae3c5
│       Summary:          Hardware and firmware technology for remote out-of-band management
│       Current version:  11.8.80.3746
│       Bootloader Version:11.8.80.3746
│       Vendor:           Intel Corporation
│       GUID:             2800f812-b7b4-2d4b-aca8-46e0ff65814c
│       Device Flags:     • Internal device
│     
├─TPM:
│     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
│     Summary:            TPM 2.0 Device
│     Current version:    303.12.0.0
│     Vendor:             Intel (TPM:INTC)
│     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6
│                         34801700-3a50-5b05-820c-fe14580e4c2d
│                         8e1cbc5d-5a11-5149-bfea-b6065d5296ba
│                         03f304f4-223e-54f4-b2c1-c3cf3b5817c6
│                         52d7b679-db28-5bf7-bd87-41d77aeec600
│     Device Flags:       • Internal device
│   
└─UEFI Device Firmware:
      Device ID:          422d67cf5a4e6aeea9f92945ea2aafc1cbe6a317
      Current version:    65553
      Minimum Version:    1
      Vendor:             DMI:LENOVO
      GUIDs:              64f10525-b16b-4fd6-a7e3-6e04ad32b64a
                          0ece6108-781e-5b2a-be3d-c00805f787a4
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
</pre>
</details>

#### System UEFI configuration

<details>
<summary><code>$ efibootmgr -v</code></summary>
<pre>
$ efibootmgr -v
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0010,0000,0017,0018,0019,001A,001B,001C,001D,001E,001F,0020,0021
Boot0000* Linux-Firmware-Updater        HD(1,GPT,be192cdf-02f0-c54d-931d-c9cbfe3dbebc,0x800,0x100000)/File(\EFI\arch\fwupdx64.efi)
Boot0002* GRUB  HD(1,GPT,be192cdf-02f0-c54d-931d-c9cbfe3dbebc,0x800,0x100000)/File(\EFI\GRUB\grubx64.efi)
Boot0010  Setup FvFile(721c8b66-426c-4e86-8e99-3457c46ab0b9)
Boot0011  Boot Menu     FvFile(126a762d-5758-4fca-8531-201a7f57f850)
Boot0012  Diagnostic Splash Screen      FvFile(a7d8d9a6-6ab0-4aeb-ad9d-163e59a7a380)
Boot0013  Lenovo Diagnostics    FvFile(3f7e615b-0d45-4f80-88dc-26b234958560)
Boot0014  Startup Interrupt Menu        FvFile(f46ee6f4-4785-43a3-923d-7f786c3c8479)
Boot0015  Rescue and Recovery   FvFile(665d3f60-ad3e-4cad-8e26-db46eee9f1b5)
Boot0016  MEBx Hot Key  FvFile(ac6fd56a-3d41-4efd-a1b9-870293811a28)
Boot0017* USB CD        VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,86701296aa5a7848b66cd49dd3ba6a55)
Boot0018* USB FDD       VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,6ff015a28830b543a8b8641009461e49)
Boot0019* ATAPI CD0     VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a35403)
Boot001A* NVMe0 VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a400)
Boot001B* NVMe1 VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,001c199932d94c4eae9aa0b6e98eb8a401)
Boot001C* ATA HDD2      VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f600)
Boot001D* ATA HDD3      VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f604)
Boot001E* ATA HDD0      VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f602)
Boot001F* ATA HDD1      VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f603)
Boot0020* USB HDD       VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,33e821aaaf33bc4789bd419f88c50803)
Boot0021* PCI LAN       VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,78a84aaf2b2afc4ea79cf5cc8f3d3803)
Boot0022* IDER BOOT CDROM       PciRoot(0x0)/Pci(0x14,0x0)/USB(15,1)
Boot0023* IDER BOOT Floppy      PciRoot(0x0)/Pci(0x14,0x0)/USB(15,0)
Boot0024* ATA HDD       VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,91af625956449f41a7b91f4f892ab0f6)
Boot0025* ATAPI CD      VenMsg(bc7838d2-0f82-4d60-8316-c068ee79d25b,aea2090adfde214e8b3a5e471856a354)
</pre>
</details>

<details>
<summary><code>$ efivar -l | grep fw</code></summary>
<pre>
$ efivar -l | grep fw
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-9b0578cf-f035-4fe8-b6ae-42591c946c36-0
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-ux-capsule
</pre>
</details>

<details>
  <summary><code>$ tree /boot</code></summary>
<pre>
$ tree /boot
/boot
├── efi
│   └── EFI
│       ├── arch
│       │   ├── fw
│       │   │   ├── fwupd-3b8c8162-188c-46a4-aec9-be43f1d65697.cap
│       │   │   └── fwupd-9b0578cf-f035-4fe8-b6ae-42591c946c36.cap
│       │   ├── fwupdx64.efi
│       │   └── fwupdx64.efi.signed
│       └── GRUB
│           └── grubx64.efi
├── efikeys
│   ├── db.cer
│   ├── db.crt
│   ├── db.esl
│   ├── db.key
│   ├── GUID
│   ├── KEK.cer
│   ├── KEK.crt
│   ├── KEK.esl
│   ├── KEK.key
│   ├── NAME
│   ├── PK.auth
│   ├── PK.cer
│   ├── PK.crt
│   ├── PK.esl
│   ├── PK.key
│   ├── PK_null.auth
│   └── PK_null.esl
├── grub
│   ├── fonts
│   │   └── unicode.pf2
│   ├── grub-btrfs.cfg
│   ├── grub.cfg
│   ├── grubenv
│   ├── themes
│   │   └── starfield
│   │       ├── blob_w.png
│   │       ├── boot_menu_c.png
│   │       ├── boot_menu_e.png
│   │       ├── boot_menu_ne.png
│   │       ├── boot_menu_n.png
│   │       ├── boot_menu_nw.png
│   │       ├── boot_menu_se.png
│   │       ├── boot_menu_s.png
│   │       ├── boot_menu_sw.png
│   │       ├── boot_menu_w.png
│   │       ├── COPYING.CC-BY-SA-3.0
│   │       ├── dejavu_10.pf2
│   │       ├── dejavu_12.pf2
│   │       ├── dejavu_14.pf2
│   │       ├── dejavu_16.pf2
│   │       ├── dejavu_bold_14.pf2
│   │       ├── README
│   │       ├── slider_c.png
│   │       ├── slider_n.png
│   │       ├── slider_s.png
│   │       ├── starfield.png
│   │       ├── terminal_box_c.png
│   │       ├── terminal_box_e.png
│   │       ├── terminal_box_ne.png
│   │       ├── terminal_box_n.png
│   │       ├── terminal_box_nw.png
│   │       ├── terminal_box_se.png
│   │       ├── terminal_box_s.png
│   │       ├── terminal_box_sw.png
│   │       ├── terminal_box_w.png
│   │       └── theme.txt
│   └── x86_64-efi
│       ├── acpi.mod
│       ├── adler32.mod
│       ├── affs.mod
│       ├── afs.mod
│       ├── ahci.mod
│       ├── all_video.mod
│       ├── aout.mod
│       ├── appleldr.mod
│       ├── archelp.mod
│       ├── ata.mod
│       ├── at_keyboard.mod
│       ├── backtrace.mod
│       ├── bfs.mod
│       ├── bitmap.mod
│       ├── bitmap_scale.mod
│       ├── blocklist.mod
│       ├── boot.mod
│       ├── boottime.mod
│       ├── bsd.mod
│       ├── bswap_test.mod
│       ├── btrfs.mod
│       ├── bufio.mod
│       ├── cacheinfo.mod
│       ├── cat.mod
│       ├── cbfs.mod
│       ├── cbls.mod
│       ├── cbmemc.mod
│       ├── cbtable.mod
│       ├── cbtime.mod
│       ├── chain.mod
│       ├── cmdline_cat_test.mod
│       ├── cmp.mod
│       ├── cmp_test.mod
│       ├── command.lst
│       ├── configfile.mod
│       ├── core.efi
│       ├── cpio_be.mod
│       ├── cpio.mod
│       ├── cpuid.mod
│       ├── crc64.mod
│       ├── cryptodisk.mod
│       ├── crypto.lst
│       ├── crypto.mod
│       ├── cs5536.mod
│       ├── ctz_test.mod
│       ├── datehook.mod
│       ├── date.mod
│       ├── datetime.mod
│       ├── diskfilter.mod
│       ├── disk.mod
│       ├── div.mod
│       ├── div_test.mod
│       ├── dm_nv.mod
│       ├── echo.mod
│       ├── efifwsetup.mod
│       ├── efi_gop.mod
│       ├── efinet.mod
│       ├── efi_uga.mod
│       ├── ehci.mod
│       ├── elf.mod
│       ├── eval.mod
│       ├── exfat.mod
│       ├── exfctest.mod
│       ├── ext2.mod
│       ├── extcmd.mod
│       ├── f2fs.mod
│       ├── fat.mod
│       ├── file.mod
│       ├── fixvideo.mod
│       ├── font.mod
│       ├── fshelp.mod
│       ├── fs.lst
│       ├── functional_test.mod
│       ├── gcry_arcfour.mod
│       ├── gcry_blowfish.mod
│       ├── gcry_camellia.mod
│       ├── gcry_cast5.mod
│       ├── gcry_crc.mod
│       ├── gcry_des.mod
│       ├── gcry_dsa.mod
│       ├── gcry_idea.mod
│       ├── gcry_md4.mod
│       ├── gcry_md5.mod
│       ├── gcry_rfc2268.mod
│       ├── gcry_rijndael.mod
│       ├── gcry_rmd160.mod
│       ├── gcry_rsa.mod
│       ├── gcry_seed.mod
│       ├── gcry_serpent.mod
│       ├── gcry_sha1.mod
│       ├── gcry_sha256.mod
│       ├── gcry_sha512.mod
│       ├── gcry_tiger.mod
│       ├── gcry_twofish.mod
│       ├── gcry_whirlpool.mod
│       ├── geli.mod
│       ├── gettext.mod
│       ├── gfxmenu.mod
│       ├── gfxterm_background.mod
│       ├── gfxterm_menu.mod
│       ├── gfxterm.mod
│       ├── gptsync.mod
│       ├── grub.efi
│       ├── gzio.mod
│       ├── halt.mod
│       ├── hashsum.mod
│       ├── hdparm.mod
│       ├── hello.mod
│       ├── help.mod
│       ├── hexdump.mod
│       ├── hfs.mod
│       ├── hfspluscomp.mod
│       ├── hfsplus.mod
│       ├── http.mod
│       ├── iorw.mod
│       ├── iso9660.mod
│       ├── jfs.mod
│       ├── jpeg.mod
│       ├── keylayouts.mod
│       ├── keystatus.mod
│       ├── ldm.mod
│       ├── legacycfg.mod
│       ├── legacy_password_test.mod
│       ├── linux16.mod
│       ├── linux.mod
│       ├── loadbios.mod
│       ├── load.cfg
│       ├── loadenv.mod
│       ├── loopback.mod
│       ├── lsacpi.mod
│       ├── lsefimmap.mod
│       ├── lsefi.mod
│       ├── lsefisystab.mod
│       ├── lsmmap.mod
│       ├── ls.mod
│       ├── lspci.mod
│       ├── lssal.mod
│       ├── luks.mod
│       ├── lvm.mod
│       ├── lzopio.mod
│       ├── macbless.mod
│       ├── macho.mod
│       ├── mdraid09_be.mod
│       ├── mdraid09.mod
│       ├── mdraid1x.mod
│       ├── memdisk.mod
│       ├── memrw.mod
│       ├── minicmd.mod
│       ├── minix2_be.mod
│       ├── minix2.mod
│       ├── minix3_be.mod
│       ├── minix3.mod
│       ├── minix_be.mod
│       ├── minix.mod
│       ├── mmap.mod
│       ├── moddep.lst
│       ├── modinfo.sh
│       ├── morse.mod
│       ├── mpi.mod
│       ├── msdospart.mod
│       ├── mul_test.mod
│       ├── multiboot2.mod
│       ├── multiboot.mod
│       ├── nativedisk.mod
│       ├── net.mod
│       ├── newc.mod
│       ├── nilfs2.mod
│       ├── normal.mod
│       ├── ntfscomp.mod
│       ├── ntfs.mod
│       ├── odc.mod
│       ├── offsetio.mod
│       ├── ohci.mod
│       ├── part_acorn.mod
│       ├── part_amiga.mod
│       ├── part_apple.mod
│       ├── part_bsd.mod
│       ├── part_dfly.mod
│       ├── part_dvh.mod
│       ├── part_gpt.mod
│       ├── partmap.lst
│       ├── part_msdos.mod
│       ├── part_plan.mod
│       ├── part_sun.mod
│       ├── part_sunpc.mod
│       ├── parttool.lst
│       ├── parttool.mod
│       ├── password.mod
│       ├── password_pbkdf2.mod
│       ├── pata.mod
│       ├── pbkdf2.mod
│       ├── pbkdf2_test.mod
│       ├── pcidump.mod
│       ├── pgp.mod
│       ├── play.mod
│       ├── png.mod
│       ├── priority_queue.mod
│       ├── probe.mod
│       ├── procfs.mod
│       ├── progress.mod
│       ├── raid5rec.mod
│       ├── raid6rec.mod
│       ├── random.mod
│       ├── rdmsr.mod
│       ├── read.mod
│       ├── reboot.mod
│       ├── regexp.mod
│       ├── reiserfs.mod
│       ├── relocator.mod
│       ├── romfs.mod
│       ├── scsi.mod
│       ├── search_fs_file.mod
│       ├── search_fs_uuid.mod
│       ├── search_label.mod
│       ├── search.mod
│       ├── serial.mod
│       ├── setjmp.mod
│       ├── setjmp_test.mod
│       ├── setpci.mod
│       ├── sfs.mod
│       ├── shift_test.mod
│       ├── shim_lock.mod
│       ├── signature_test.mod
│       ├── sleep.mod
│       ├── sleep_test.mod
│       ├── spkmodem.mod
│       ├── squash4.mod
│       ├── strtoull_test.mod
│       ├── syslinuxcfg.mod
│       ├── tar.mod
│       ├── terminal.lst
│       ├── terminal.mod
│       ├── terminfo.mod
│       ├── test_blockarg.mod
│       ├── testload.mod
│       ├── test.mod
│       ├── testspeed.mod
│       ├── tftp.mod
│       ├── tga.mod
│       ├── time.mod
│       ├── tpm.mod
│       ├── trig.mod
│       ├── tr.mod
│       ├── true.mod
│       ├── udf.mod
│       ├── ufs1_be.mod
│       ├── ufs1.mod
│       ├── ufs2.mod
│       ├── uhci.mod
│       ├── usb_keyboard.mod
│       ├── usb.mod
│       ├── usbms.mod
│       ├── usbserial_common.mod
│       ├── usbserial_ftdi.mod
│       ├── usbserial_pl2303.mod
│       ├── usbserial_usbdebug.mod
│       ├── usbtest.mod
│       ├── verifiers.mod
│       ├── video_bochs.mod
│       ├── video_cirrus.mod
│       ├── video_colors.mod
│       ├── video_fb.mod
│       ├── videoinfo.mod
│       ├── video.lst
│       ├── video.mod
│       ├── videotest_checksum.mod
│       ├── videotest.mod
│       ├── wrmsr.mod
│       ├── xfs.mod
│       ├── xnu.mod
│       ├── xnu_uuid.mod
│       ├── xnu_uuid_test.mod
│       ├── xzio.mod
│       ├── zfscrypt.mod
│       ├── zfsinfo.mod
│       ├── zfs.mod
│       └── zstd.mod
├── initramfs-linux-fallback.img
├── initramfs-linux.img
├── initramfs-linux-lts-fallback.img
├── initramfs-linux-lts.img
├── intel-ucode.img
├── vmlinuz-linux
└── vmlinuz-linux-lts

11 directories, 341 files
</pre>
</details>

**Additional questions**
- Operating system and version: **Arch Linux (up to date)**
- Have you tried rebooting? **Yes**
- Is this a regression? **?**
- Are you using an NVMe disk? **No**
- Is secure boot enabled? **No** (/ I tested it with both)
- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS? `Boot Order Lock` is turned **off**

**Comment by kmauleon** [comment]
hi @sedrubal can you please send screenshot of BIOS settings... also please post result of below command... thank you very much...
**fwupdmgr get-devices**

**Comment by sedrubal** [comment]
I updated the description above and can confirm, that `Boot Order Lock` is turned off. Further BIOS settings can be found here:

![lenovo-p70-bios-settings-1](https://user-images.githubusercontent.com/5571650/119115005-fb259580-ba26-11eb-93cb-68b9a52300f3.jpg)
![lenovo-p70-bios-settings-2](https://user-images.githubusercontent.com/5571650/119115012-fbbe2c00-ba26-11eb-94ca-edd20a24dd35.jpg)


I already posted the output of `fwupdmgr get-devices --show-all-devices` above, but here again without `--show-all-devices`:

```
$ fwupdmgr get-devices
20ER003SGE
│
├─INTEL SSDSCKKF256H6L:
│     Device ID:          5dbeb140337f610d54913c0f43d15fdaa0eafb51
│     Summary:            ATA Drive
│     Current version:    LBFL11P
│     Vendor:             Intel (ATA:0x8086|OUI:5cd2e4)
│     GUIDs:              a6af6710-9837-5f0d-8ca2-405f259ce5f6
│                         38bae1a4-d6a2-5ab4-84a2-d90d93084106
│                         983c4c4a-a661-57ac-a5a4-a8bb8b37b2ed
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Intel Management Engine:
│     Device ID:          118ec9ef6f590ae68fae0026096cb21882481627
│     Current version:    184.80.3746
│     Minimum Version:    184.80.3746
│     Vendor:             DMI:LENOVO
│     Update State:       Transient failure
│     Update Error:       Secure boot is enabled, but shim isn't installed to the EFI system partition
│     Last modified:      2021-05-21 09:10
│     GUIDs:              9b0578cf-f035-4fe8-b6ae-42591c946c36
│                         d7b47f59-ab20-51b8-9261-d68741f61e09
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Samsung SSD 850 EVO 500GB:
│     Device ID:          64ec4cd1e1c9565e79b00f4e7221b1c689b33e96
│     Summary:            ATA Drive
│     Current version:    EMT02B6Q
│     Vendor:             Samsung (ATA:0x144D|OUI:002538)
│     GUIDs:              4f91c57f-0080-5f61-95b8-c54899cc39cb
│                         086811eb-c412-5a0b-a319-7c37d3dd3e46
│                         967c50bf-25a0-5394-b21d-5939967dade6
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─System Firmware:
│     Device ID:          584bb826ddd562b072efe306596b05d0ae9a29f5
│     Current version:    0.2.32
│     Minimum Version:    0.2.19
│     Vendor:             LENOVO (DMI:LENOVO)
│     GUIDs:              df91783d-a03d-485a-9a8e-a3f39067f18e
│                         230c8b18-8d9b-53ec-838b-6cfc0383493a
│                         603eb043-4f1d-5538-9d3a-9923b4d07b34
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Cryptographic hash verification is available
│                         • Device is usable for the duration of the update
│   
└─UEFI Device Firmware:
      Device ID:          422d67cf5a4e6aeea9f92945ea2aafc1cbe6a317
      Current version:    65553
      Minimum Version:    1
      Vendor:             DMI:LENOVO
      GUIDs:              64f10525-b16b-4fd6-a7e3-6e04ad32b64a
                          0ece6108-781e-5b2a-be3d-c00805f787a4
      Device Flags:       • Internal device
                          • Updatable
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
```

**Comment by kmauleon** [comment]
hi @sedrubal can you please try following settings as attached images for _SecureBoot and Startup_.
![SecureBoot Disabled](https://user-images.githubusercontent.com/62524943/119119892-3d1dfe00-ba5e-11eb-9a96-727921747ab7.jpg)
![Startup Settings](https://user-images.githubusercontent.com/62524943/119119908-43ac7580-ba5e-11eb-8c61-60ffaec3392b.jpg)

Then please try to execute the following again...
**fwupdmgr --force refresh
fwupdmgr update**

**Comment by sedrubal** [comment]
I already disabled `Secure Boot` before for testing and it did not change anything. Now I additionally set "UEFI/Legacy Boot" to `Both` and `CSM Support` to `Yes` and after running `fwupdmgr --force refresh && fwupdmgr update` `fwupdx64.efi` started successfully and I could see the update screen as expected. After ~1 minute the system rebooted - everything as expected.

But when I run `fwupdmgr` again, it still says `Upgrade available for Intel Management Engine from 184.80.3746 to 184.83.3874`. So it seems that the update did not happen. I repeated the step about 4 times but the result was the same.

Apart from the non-functional Intel ME update I'm wondering if fwup requires `CSM Support` to be turned on. As soon as I enable secure boot, the BIOS is setting `UEFI/Legacy Boot` to `UEFI only` and `CSM Support` to `No`. AFAIK fwup works with secure boot as long as `fwupdx64.efi` is properly signed. But why did the update screen appear, when I enabled `CSM Support`?

**Comment by kmauleon** [comment]
hi @sedrubal sorry I can not answer your question as I am not into BIOS and fwupd technicalities.  Maybe @hughsie can help to answer... BTW, what's the ME version in BIOS now?  I am asking because there is an existing issue in BIOS that ME is already updated in BIOS but fwupd still detects lower version thus prompting the user to update again.  Please advise.  Thank you very much...

**Comment by sedrubal** [comment]
Thank @kmauleon the BIOS displays `11.8.83.3874` which I guess is equivalent to `184.83.3874`, which is the version, fwupd tries to install. `11.8.83.3874` is also the latest Intel ME version I can find on the support website of Lenovo. So it seems, the upgrade was successful and I have a workaround for this issue.

**Comment by kmauleon** [comment]
hi @sedrubal thank you very much for the confirmation and you are most welcome!

**Comment by sedrubal** [comment]
@kmauleon just want to note one thing: Using [mei-amt-check](https://github.com/mjg59/mei-amt-check) (which is querying the ME version via `/dev/mei0`) gives me the right version `11.8.83`, while `fwupdmgr get-devices` gives me `184.80.3746`.

**Comment by kmauleon** [comment]
hi @sedrubal this is a known issue and our BIOS DEV can't debug without seeing the content of ESRT table.  I can't get anyone to run a tool on their system... so i'm not sure how we can resolve the issue.  thank you very much for the information

**Comment by sedrubal** [comment]
@kmauleon if you tell me the issue and the tool, I have to run, I can maybe provide some information. This however is the content of `/sys/firmware/efi/esrt/`:

| Entry  | fw_class                             | lowest_supported_fw_version | last_attempt_version | last_attempt_status | fw_type | fw_version | capsule_flags |
|--------|--------------------------------------|-----------------------------|----------------------|---------------------|---------|------------|---------------|
| entry0 | df91783d-a03d-485a-9a8e-a3f39067f18e | 131091                      | 0                    | 0                   | 1       | 131104     | 0x0           |
| entry1 | 9b0578cf-f035-4fe8-b6ae-42591c946c36 | 3092254370                  | 3092254370           | 0                   | 2       | 3092254370 | 0x8010        |
| entry2 | 64f10525-b16b-4fd6-a7e3-6e04ad32b64a | 1                           | 0                    | 0                   | 2       | 65553      | 0x0           |

**Comment by kmauleon** [comment]
hi @sedrubal thank you very much for your support... as I am not allowed to share the tool publicly, can you please contact me thru my lenovo email kmauleon@lenovo.com  ... thank you very much for your help in advanced...
