### ISSUE TITLE
L14 AMD is missing UEFI FW 1.19

### ISSUE THREAD

**Issue by valkum** [fwupd/firmware-lenovo#135]
Version 1.19: https://support.lenovo.com/us/en/downloads/ds545476-bios-update-utility-bootable-cd-for-windows-10-64-bit-thinkpad-l14-types-20u5-20u6-l15-types-20u7-20u8
Release Notes: https://download.lenovo.com/pccbbs/mobiles/r19uj09w.txt

**Comment by mrhpearson** [comment]
Unfortunately the L14 AMD isn't part of the Lenovo Linux program so the firmware team aren't putting updates on LVFS. They don't have the resources for that exercise.

Mark
