### ISSUE TITLE
ThinkPad P14s Gen 2 AMD system firmware is missing

### ISSUE THREAD

**Issue by bdaase** [fwupd/firmware-lenovo#143]
The ThinkPad P14s Gen 2 AMD system firmware is missing on the lvfs, even though it is referenced as available in the corresponding hardware manual.

**Comment by mrhpearson** [comment]
We haven't released P14s G2 AMD with Linux yet - there are still HW enablement issues we're working through.
Mark

**Comment by bdaase** [comment]
Thanks for the fast response :)

Do you have a rough ETA when we can expect it?

**Comment by mrhpearson** [comment]
We've been hit by WLAN component shortages and they switched parts on us very very late in the program. The new parts don't have Linux support upstream yet (vendors are working on it right now). I'm going to guess at least another month but I don't have an actual ETA.
Mark

**Comment by bdaase** [comment]
Sure, the first thing I did after purchase was swapping out the Realtek card for an AX210 - with that everything works flawlessly under Linux so far for me :)

So we first have to wait for the hardware stuff to be fixed before we can expect system firmware on the LVFS?

**Comment by mrhpearson** [comment]
I'll see if the FW team will put it up sooner. The problem is that they usually test FW updates with our preload image - which we don't have yet.
Mark

**Comment by bdaase** [comment]
Thank you, Mark. This is highly appreciated!

**Comment by bdaase** [comment]
Thank you, Mark, it looks like its available on the lvfs now: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR1MET.firmware.

Edit: It is available now and update went perfectly fine!
