### ISSUE TITLE
Missing firmware 1.35 for Lenovo

### ISSUE THREAD

**Issue by csantelmann** [fwupd/firmware-lenovo#151]
Hi,
I got a Lenovo X13 notebook.
According to the Lenovo site, there is a new firmware 1.35 available:
https://pcsupport.lenovo.com/de/de/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x13-type-20uf-20ug/downloads/DS544980
fwupd does not offer the new version.
Can I do anything to help fix this?
Regards
Cord

**Comment by mrhpearson** [comment]
It will make it's way to LVFS - it just takes our BIOS teams some time to prepare the LVFS release, test it and deliver it. 
We're looking into how to streamline the process but it's complicated (and a honestly a little frustrating).
Mark

**Comment by csantelmann** [comment]
Thanks a lot for the information! I'm in no hurry.
Cord
