### ISSUE TITLE
Missing FW for T14s Gen 2i

### ISSUE THREAD

**Issue by joakim-tjernlund** [fwupd/firmware-lenovo#177]

**Comment by joakim-tjernlund** [comment]
You should include FW on LVFS before certifying for Linux :)

**Comment by mrhpearson** [comment]
Somehow I'd missed this originally - but looks like FW is there now
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN35ET.firmware
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN35HT.firmware
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN35RN.firmware

So closing ticket.
