### ISSUE TITLE
Missing existing firmware updates for ThinkPad USB-C Dock Gen2

### ISSUE THREAD

**Issue by equaeghe** [fwupd/firmware-lenovo#188]
The ThinkPad USB-C Dock Gen2 [has updates available](https://download.lenovo.com/pccbbs/mobiles/usbcg2dkfw1113_2.txt) that are far more recent than [those available via LVFS](https://fwupd.org/lvfs/search?value=Lenovo+ThinkPad+USB-C+Dock+Gen2). Is it possible for these to be made available?

**Comment by mrhpearson** [comment]
Unfortunately currently the USB-C dock is not in scope for getting Linux support I'm afraid. 
I'm pushing to expand our docking support but for now the expectation should be that this dock won't be on LVFS and you'll need to use a Windows machine to update your dock. Sorry
