### ISSUE TITLE
Restarted system w/o AC power

### ISSUE THREAD

**Issue by laur89** [fwupd/firmware-lenovo#212]
Initiated System Firmware upgrade while connected to AC power. After some hours, the reboot happened whilst disconnected from the AC.

Looks like the upgrade finished, after which the `BIOS Self Healing backup progressing` progress bar was shown - does this mean the upgrade was rolled back? Running fwupdmgr upon startup showed some errors about skipping upgrade due to not being connected to AC.

Now `fwupdmgr get-devices` shows:
```
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Summary:            UEFI ESRT device
│ │   Current version:    0.1.39
│ │   Vendor:             Lenovo (DMI:LENOVO)
│ │   Update State:       Success
│ │   Update Message:     The computer will be restarted automatically after updating BIOS completely. Do NOT turn off your computer or remove the AC adaptor w
hile update is in progress.
│ │   GUIDs:              01453b71-da0c-4832-9f4f-e378245339c7
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a
│ │                       38ad8832-d322-5d73-aff7-77b8ae0f1a6f
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─UEFI dbx:
│       Device ID:        362301da643102b9f38477387e2193e57abaa590
│       Summary:          UEFI revocation database
│       Current version:  77
│       Minimum Version:  77
│       Vendor:           UEFI:Linux Foundation
│       Install Duration: 1 second
│       GUIDs:            14503b3d-73ce-5d06-8137-77c68972a341
│                         5971a208-da00-5fce-b5f5-1234342f9cf7
│                         c6682ade-b5ec-57c4-b687-676351208742
│                         f8ba2887-9411-5c36-9cee-88995bb39731
│       Device Flags:     • Internal device
│                         • Updatable
│                         • Needs a reboot after installation
│                         • Only version upgrades are allowed
│                         • Signed Payload
```

It should've been from 1.37->1.39, so it looks like the upgrade succeeded. What about the `Update Message` though - is it normal it's still shown?

Can I be confident the upgrade completed successfully?

**Comment by mrhpearson** [comment]
The BIOS self healing is normal - that's the last stage of a succesful update.
If you go into the BIOS setup menu (F1 during early boot) then as long as that says 1.39 I think you're set. Not sure why the update didn't happen when connected to AC power though.
As a heads up - assuming this is for a 2020 AMD (e.g T14 AMD G1) you're probably going to want to revert back to 1.37 as there is an issue with audio breaking after suspend with this update  :( We're investigating the issue.

**Comment by laur89** [comment]
Thanks for the heads-up!
I'll stay from suspending in the meantime and look forward to the fix-forward.
