### ISSUE TITLE
Lenovo ThinkPad X260 latest firmware versions missing

### ISSUE THREAD

**Issue by mohms** [fwupd/firmware-lenovo#213]
The [Lenovo update Site](https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x260/downloads/ds105890) shows the latest UEFI version for the X260 to be 1.49 while the latest version in [LVFS](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR02ET.firmware) is 1.44. 

Is it possible to get the newer versions uploaded? Thanks in advance

**Comment by mrhpearson** [comment]
I'll ask the FW team - internal ticket LO-1669

**Comment by ChiWei-Chen** [comment]
@mohms , the latest BIOS just released to LVFS. Please let us know if this does not work for you.
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR02ET.firmware

**Comment by mohms** [comment]
@ChiWei-Chen after turning off secure boot before starting the update it worked perfectly. Thank you very much!

**Comment by abitrolly** [comment]
@mrhpearson @ChiWei-Chen Lenovo x260 now has BIOS 1.50 with several CVE fixes https://download.lenovo.com/pccbbs/mobiles/r02uj77d.txt, but LVFS only provides 1.49 https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR02ET.firmware

Is it possible to upload 1.50 firmware for x260 to LVFS?

**Comment by ChiWei-Chen** [comment]
@abitrolly,
Thanks for your inquiry. Since ThinkPad X260 is already EOL and we currently have resource constraints for LVFS validation, we are unable to publish BIOS version 1.50 to LVFS.
If you require version 1.50, please update via the ISO method instead. :'(

**Comment by abitrolly** [comment]
@ChiWei-Chen no problem, I understand. Opened https://gitlab.com/fwupd/lvfs-website/-/work_items/1109 to better communicate support status to LVFS users.

Does "ISO method" mean creating USB stick using ISO from https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x260/20f5/downloads/driver-list/component?name=BIOS%2FUEFI and loading from there? Or maybe it is possible to use `fwupdmgr` with that ISO to install the firmware without USB or portable CD drive?

**Comment by hughsie** [comment]
@mrhpearson can you click some "End of life" buttons when logged into lenovo_thinkpad -- or @ChiWei-Chen please -- https://fwupd.org/lvfs/devices/status is the link you want. I don't think I can do it as an admin.

**Comment by mrhpearson** [comment]
Done!

@ChiWei-Chen - let's sync up offline, we should go through and check for the other platforms that just went out of support. Should set it up as a yearly event :) (tracking with LO-4448)

**Comment by abitrolly** [comment]
> Should set it up as a yearly event :)

@mrhpearson is there such thing as "monthly process" instead of event? I did only small business jos/gigs, so I've only heard about "business process automation". The closest thing I saw are Fedora Infra SOPs - https://docs.fedoraproject.org/en-US/infra/sysadmin_guide/#_standard_operating_procedures Not only SOPs can be scripted/automated, they also don't require too much brain power to follow, so it can be made as side activity/business process day once a month. And even outsourced to subcontractor like me, who would automate the tagging the first day. 😁

**Comment by abitrolly** [comment]
@mrhpearson - if Lenovo could get API to fetch "model, firmware, checksum" entries, then LVFS could streamline new firmware releases going from "upload" to "approve". Just an idea.

From discussion in https://gitlab.com/fwupd/lvfs-website/-/work_items/1109#note_3378134497
