### ISSUE TITLE
ThinkPad T14 Gen 2i missing ECP 1.41

### ISSUE THREAD

**Issue by galibozek** [fwupd/firmware-lenovo#231]
After adding a new BIOS (1.50) version, ECP 1.41 was omitted
 
```
  1.50      (N34UR16W)  1.50 (N34ET50W)      1.41 (N34HT41W)   01    2022/05/23
```

**Comment by mrhpearson** [comment]
Agreed - raised internal ticket LO-1757 to request the EC FW gets updated too. Not sure why it was missed

Thanks for flagging it
Mark

**Comment by ChiWei-Chen** [comment]
@galibozek , thanks for reporting this missing FW.
It's stable now. Please let us know if this does not work for you.
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN34HT.firmware
