### ISSUE TITLE
[Thinkpad P15v gen 2] Fan constantly running despite low CPU usage

### ISSUE THREAD

**Issue by ssilenzi** [fwupd/firmware-lenovo#232]
Hello,
the one I am going to describe is for sure a bug, but I do not know if it depends on Firmware or Windows drivers.

![image](https://user-images.githubusercontent.com/44733864/171844268-5955c5e9-89dc-4491-9645-54c764afb31f.png)

OS:
Windows 11 Pro

Description:
the starting point is to have no application running and the fans almost completely off. When the screen becomes inactive, and it goes black, the fans start to run at the maximum speed! It happens every time the screen goes black.

**Comment by mrhpearson** [comment]
Hi,

You mention Windows drivers - do you see this under Linux?
LVFS forum is really for Linux firmware _update_ issues - not sure this really belongs here I'm afraid.

If you see it under Linux can you put a post on the Lenovo Linux forum (https://forums.lenovo.com/linux) and I'll pick it up there with instructions on how to dump EC registers.
If you see it only under Windows I recommend contacting customer support and seeing if they can help.

Mark
