### ISSUE TITLE
Intel Management Engine Update fails on Thinkpad T14 (Gen1)

### ISSUE THREAD

**Issue by majamee** [fwupd/firmware-lenovo#235]
**Describe the bug**
I am unable to update Intel Management Engine on ThinkPad T14 Gen1.

**Expected behavior**
Intel Management Engine Update gets installed successfully

**Actual behavior**
The Update cannot be applied successfully. On reboot I get an error message about the capsules capabilities, compare screenshot at the end of this post. 

**Transcribed error message**
```
WARNING: Could not query capsule capabilities: Unsupported
WARNING: Could not apply capsules: Unsupported
Reset System
```

**Steps to Reproduce**

What I did:
```
sudo -i
fwupdmgr refresh --force
fwupdmgr get-updates
```

The following update is offered:
```
fwupdmgr get-updates                                                                                                                                                [ ok ]
Devices with no available firmware updates: 
 • Integrated Camera
 • Thunderbolt host controller
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI dbx
Devices with the latest available firmware version:
 • Embedded Controller
 • KXG6AZNV1T02 TOSHIBA
 • System Firmware
20S00057GE
│
└─Intel Management Engine:
  │   Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
  │   Summary:            UEFI ESRT device
  │   Current version:    225.53.1649
  │   Minimum Version:    0.0.1
  │   Vendor:             Lenovo (DMI:LENOVO)
  │   Update State:       Success
  │   GUID:               0d7baa94-7f7f-4896-b1d3-8a6c594ff635
  │   Device Flags:       • Internal device
  │                       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Needs a reboot after installation
  │                       • Device is usable for the duration of the update
  │ 
  └─ThinkPad T14 Gen 1/ P14s Gen 1/ T15 Gen 1/ P15s Gen 1/ T14 Gen 1 Healthcare Edition:
        New version:      225.60.1807
        Remote ID:        lvfs
        Release ID:       11750
        Summary:          Lenovo ThinkPad T14 Gen 1/ P14s Gen 1/ T15 Gen 1/ P15s Gen 1/ T14 Gen 1 Healthcare Edition Consumer ME Firmware
        License:          Proprietary
        Size:             3,1 MB
        Created:          2022-01-25
        Urgency:          High
        Details:          https://pcsupport.lenovo.com/de/en/search?query=N2XRN11W
        Vendor:           Lenovo
        Release Flags:    • Is upgrade
        Description:      
        • 1 Intel Platform Update
        
        2021.2 Version 14.1.60.1807 Fixes the IPU 2021.2 security vulnerabilities. please refer to Issues List.

```

When trying to apply the update (`fwupdmgr update`), everything seems successful until the reboot, where the update should be completed.
Nevertheless, instead of completing the update, I get the following error message shown during reboot with the firmware update being queued:
![fwupmgr_reboot_error](https://user-images.githubusercontent.com/20463582/167615912-8c85a666-408f-4372-b7ca-78947581d3e9.jpg)

My system details:
```
OS: Ubuntu 18.04.6 LTS x86_64 
Host: 20S00057GE ThinkPad T14 Gen 1 
Kernel: 5.4.0-120-generic 
Uptime: 3 hours, 37 mins 
Packages: 3079 
Shell: zsh 5.4.2 
Resolution: 1920x1080, 2560x1080 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita [GTK3] 
Icons: Adwaita [GTK3] 
Terminal: gnome-terminal 
CPU: Intel i7-10510U (8) @ 4.900GHz 
GPU: Intel Device 9b41 
Memory: 7347MiB / 15667MiB 
BIOS Version: N2XET35W (1.25 )
```

```
fwupdmgr --version
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.3.10
compile   com.hughsie.libjcat           0.1.11
compile   org.freedesktop.gusb          0.3.10
runtime   org.freedesktop.fwupd-efi     1.0
runtime   com.hughsie.libjcat           0.1.11
runtime   org.kernel                    5.4.0-120-generic
compile   org.freedesktop.fwupd         1.8.1
runtime   org.freedesktop.fwupd         1.8.1
```

```
which fwupdmgr 
/snap/bin/fwupdmgr
```

Also: My BIOS still reports the installed ME Firmware Version to be 14.1.53.1649 while the to be installed version is labeled as 14.1.60.1807

The bug report here was opened as suggested by @ChiWei-Chen (https://github.com/fwupd/firmware-lenovo/issues/140#issuecomment-1161517080)

Please assist, any help is welcome.

**Comment by ChiWei-Chen** [comment]
@majamee , thanks, I've shared this with FW team.
(LO-1797: just for my internal tracking)

**Comment by ChiWei-Chen** [comment]
@majamee , the FW team wants to get your BIOS dump for investigation. If you're willing to help on this, could you drop me a mail to: ( cchen50 [at] lenovo dot com ). I'll sent you the instruction and the efi tool.
Thanks!

**Comment by majamee** [comment]
@ChiWei-Chen Any news about investigating the BIOS dump?

**Comment by ChiWei-Chen** [comment]
@majamee , thank you for your assistance. 
The FW team copied the BIOS section base on the BIOS dump. And confirmed that they can update MEFW on our side. 
Now they've involved the supplier to confirm where the error message comes from.

**Comment by majamee** [comment]
@ChiWei-Chen Thank you, please let me know, if you or the supplier does need some additional information to overcome this issue.

**Comment by ChiWei-Chen** [comment]
@majamee . The FW team could not reproduce the issue with your BIOS dump, it is suspected fwupd related.
This seems related to [RH#1878662](https://bugzilla.redhat.com/show_bug.cgi?id=1878662), could you provide the upgrade fails. Log from fwupdate with command "fwupdate -L"?

Did you see ME version already "14.1.60.1807" in BIOS Main page(press F1 in preboot phase)?

Thanks!

**Comment by majamee** [comment]
@ChiWei-Chen On BIOS main page still the old version of ME is listed.
Also the snap version of fwupd (https://snapcraft.io/fwupd) seems not to include "fwupdate" as I get the following output for 
"fwupdate -L":

`command not found: fwupdate`

For comparison:
```
fwupdmgr --version
runtime   com.dell.libsmbios            2.4
runtime   org.freedesktop.gusb          0.3.10
compile   com.hughsie.libjcat           0.1.11
compile   org.freedesktop.gusb          0.3.10
runtime   org.freedesktop.fwupd-efi     1.0
runtime   com.hughsie.libjcat           0.1.11
runtime   org.kernel                    5.4.0-121-generic
compile   org.freedesktop.fwupd         1.8.1
runtime   org.freedesktop.fwupd         1.8.1
```

Operating system is: Ubuntu 18.04.6 LTS x86_64

**Comment by majamee** [comment]
@ChiWei-Chen The issue is Ubuntu 18.04 specific it seems.
The native fwupdmgr version is too outdated to apply the firmware updates and the snap version ends in the issue, posted above.

I just created a live usb disk using mkusb-dus based on Ubuntu 20.04 with an added persistent storage, booted my machine from it and was able to install the firmware updates including the Intel Media Engine update successfully using "fwupdmgr update" from within the live environment. Very strange though.

Would be very happy to find any solution for Ubuntu 18.04 as the workaround is just not scale-able.

**Comment by ChiWei-Chen** [comment]
@majamee , it's appreciated for sharing the information. Sorry, I didn't notice you're using Ubuntu 18.04, but it's good to know your problem is resolved. I'll check with FW whether they can find some clues in Ubuntu 18.04.

**Comment by ChiWei-Chen** [comment]
@majamee , as confirmed by FW experts, there are no different Settings for different OS versions in FW. This is suspected to some patches may need to be backport to Ubuntu 18.04.
Allow me to double confirm, this issue was initially encountered on native fwupdmgr version in Ubuntu 18.04.6, even with snap version fwupdmgr 1.8.1 installed in Ubuntu 18.04.6. 
Please let me know if I misunderstood. Thanks!

**Comment by majamee** [comment]
Correct. The native version in Ubuntu 18.04 reports it is too old to proceed. The above described problem is true for the latest stable snap version of fwupd on Ubuntu 18.04.

**Comment by ChiWei-Chen** [comment]
@majamee , thanks for the confirmation.

@hughsie , would it be the 1.8.1 snap version of fwupd having dependency problem with old Kernel we need to backport, could we have your comment on which patch we can start?
Thanks!

**Comment by ChiWei-Chen** [comment]
@majamee , it seems Canonical will not update 18.04, it is suggested to upgrade Ubuntu 20.04 (or later) if you see the same problem in the future. Thank you for your understanding.
