### ISSUE TITLE
ThinkPad T14 Gen 2 Customer ME Update missing

### ISSUE THREAD

**Issue by galibozek** [fwupd/firmware-lenovo#237]
Customer ME Update: **240.41.2142** has been omitted for 
Lenovo ThinkPad T14 Gen 2 / P14s Gen 2 / T15 Gen 2 / P15s Gen 2

**Comment by mrhpearson** [comment]
Ack.
It's normal for it to take longer to hit LVFS (something I'm trying to improve) and is to related to how the FW team get their approvals & testing done for the releases. I'll check on the status but my guess is it will land in the next couple of weeks.
