### ISSUE TITLE
Latest firmware for X13/T14s Gen 2 AMD shown as "testing"

### ISSUE THREAD

**Issue by mohms** [fwupd/firmware-lenovo#259]
The two latest firmware releases for  [Lenovo (ThinkPad) ThinkPad X13/T14s Gen 2 AMD](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR1NET.firmware) - 0.1.20 and 0.1.21 - are shown as "state: testing". However, 1.21 is released for download on the [Lenovo support site](https://pcsupport.lenovo.com/de/de/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x13-gen-2-type-20xh-20xj/20xj/downloads/driver-list/component?name=BIOS) and can be downloaded for Linux as a .cab file. Trying to upgrade from that file complains about it not being signed, though.

Is there a reason for the testing state or is it more of an oversight?

**Comment by mrhpearson** [comment]
Hmm - it's been in testing for a month so it looks like someone forgot to move it...grumble
I'll send a nudge to the FW team (tracked internally with ticket  LO-1963)

**Comment by ChiWei-Chen** [comment]
Mark, thanks.

@mohms , the FW team moved the BIOS 1.20 and 1.21 to stable. Please let me know if this doesn't work for you. Thanks!
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR1NET.firmware
