### ISSUE TITLE
“No updates to process, exiting in 10 seconds” delay on every boot

### ISSUE THREAD

**Issue by da2x** [fwupd/firmware-lenovo#274]
Hi, I’ve got a Lenovo ThinkPad T14 with Fedora 36 and fwupd 1.8.1.

Every time I power on my laptop, it shows the following text:

> WARNING: No updates to process, exiting in 10 seconds.

It seems to originate from:

https://github.com/fwupd/fwupd-efi/blob/13492e3563da1a25fb2ee7ac7e6a210b211bdccc/efi/fwupdate.c#L573

How do I disable this delay at start up? No one has 10 seconds to waste every day in this day and age.

My laptop has the latest firmware version installed, according to the Lenovo website.

`fwupdmgr get-devices` shows `Success` in every device’s `Update State` field.

**Comment by hughsie** [comment]
What does `efibootmgr -v` print?

**Comment by da2x** [comment]
> What does `efibootmgr -v` print?

```
BootCurrent: 0001
Timeout: 0 seconds
BootOrder: 0002,0001,0000,0017,0018,0019,001A,001B,001C
Boot0000* Windows Boot Manager  HD(1,GPT,a26b9715-anon,0x800,0x12c000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)WINDOWS.........x...B.C.D.O.B.J.E.C.T.=.{.9.d.e.a.8.6.2.c.-.5.c.d.d.-.4.e.7.0.-.a.c.c.1.-.f.3.2.b.3.4.4.d.4.7.9.5.}...d................
Boot0001* Fedora        HD(1,GPT,a26b9715-anon,0x800,0x12c000)/File(\EFI\fedora\shimx64.efi)
Boot0002* Linux-Firmware-Updater        HD(1,GPT,a26b9715-anon,0x800,0x12c000)/File(\EFI\fedora\fwupdx64.efi)
Boot0010  Setup FvFile(721c8b66-anon)
Boot0011  Boot Menu     FvFile(126a762d-anon)
Boot0012  Diagnostic Splash Screen      FvFile(a7d8d9a6-anon)
Boot0013  Lenovo Diagnostics    FvFile(3f7e615b-anon)
Boot0014  ThinkShield secure wipe       FvFile(3593a0d5-anon)
Boot0015  Startup Interrupt Menu        FvFile(f46ee6f4-anon)
Boot0016  Rescue and Recovery   FvFile(665d3f60-anon)
Boot0017* USB CD        VenMsg(bc7838d2-anon,86701296shortn)
Boot0018* USB FDD       VenMsg(bc7838d2-anon,6ff015a2shortn)
Boot0019* NVMe0 VenMsg(bc7838d2-anon,001c1999shortn)
Boot001A* ATA HDD0      VenMsg(bc7838d2-anon,91af6259short)
Boot001B* USB HDD       VenMsg(bc7838d2-anon,33e821aashort)
Boot001C* PXE BOOT      VenMsg(bc7838d2-anon,78a84aafshort)
Boot001D  Regulatory Information        FvFile(478c92a0-anon)
Boot001E* Boot Next Boot Option VenMsg(bc7838d2-anon,a7ca6d35short)
```

**Comment by hughsie** [comment]
> BootOrder: 0002

This means it's booting Linux-Firmware-Updater every single time. Try `efibootmgr --delete-bootnum --bootnum 0002`

**Comment by da2x** [comment]
Lenovo’s UEFI settings screen only lists Fedora as a boot option. Neither Windows Boot Manager nor Linux-Firmware-Updater was in the list.

> Try `efibootmgr --delete-bootnum --bootnum 0002`

That resolved the problem. Any idea what caused this? I’m assuming fwupd injected itself into the boot order at some time to perform a firmware update, and then didn’t clean up after itself?

**Comment by hughsie** [comment]
> I’m assuming fwupd injected itself into the boot order

I don't think so; we use BootNext which is a one-time thing. It's entirely possible there was a firmware bug; Lenovo firmware used to futz with the BootOrder, which is why for Lenovo we use `Linux-Firmware-Updater` rather than `Linux Firmware Updater` (i.e. no spaces) due to bugs.
