### ISSUE TITLE
Thinkpad x13 gen 2 AMD - Unable to charge battery after BIOS update.

### ISSUE THREAD

**Issue by Cyanose** [fwupd/firmware-lenovo#282]
Arch Linux 6.0.2 
Recent bios update to version https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR1NET.firmware 0.1.21 caused laptop battery to be unable to charge. Connecting the adapter was just preventing laptop from discharging (Laptop had been consuming the energy directly from the charger, but was unable to charge battery). The interesting fact I found was that the `/sys/class/power_supply/AC` directory was missing. also in the journalctl there were entry: `ACPI: \_SB_PCI0.LPC0.EC0_.AC__:  Error reading AC Adapter state: AE_NOT_FOUND`

Bios downgrade to version 0.1.20 fixed the issue

**Comment by hughsie** [comment]
@mrhpearson help!

**Comment by mrhpearson** [comment]
Thanks for the report. Raised ticket  LO-2092 to the firmware team.

I don't have a X13 AMD G2 to test with directly myself but I do have a T14s G2 AMD which uses the same FW. I'm seeing that ACPI message and the lack of the power_supply/AC directory - but the battery is charging so those might be a red-herring (do you not seen those with 1.20?)

I'll update when I hear back from the FW team
Mark

**Comment by Cyanose** [comment]
Hi, thanks for the action sir.
On the 1.20 bios version the ACPI messege regarding adapter I get in log is: `ACPI: AC: AC Adapter [AC] (on-line)` 
And the `power_supply/AC` directory does exists with the proper content inside. The battery is charging just as it should.
Best regards

**Comment by mrhpearson** [comment]
Got confirmation from the BIOS team that this was a known issue and will be fixed in release R1NET54W BIOS
ETA for that is 18th November (it takes a while for it to go through our internal test and release process).
Note - I think 54W will be version 1.24

**Comment by hughsie** [comment]
@mrhpearson can I flip that bit that makes the uploader have to specify R1NET54W?

**Comment by mrhpearson** [comment]
How does that work? Means for that platform the next release has to be that?
I don't have a problem with that - unless a problem is found with 54W and they end up with 55W...

**Comment by Cyanose** [comment]
Thanks a lot for your involvement once again,
So if I understood correctly, This will be fixed not in the next incoming update, but I need to wait for version 0.1.24 ?

**Comment by hughsie** [comment]
> How does that work

Ohh, sorry, I mean we make it mandatory to specify the tag e.g. `R1NET54W` for each upload. It's getting a bit confusing to compare version numbers to tags like `R1NET54W` when the latter keep being forgotten on the LVFS... :)

**Comment by mrhpearson** [comment]
@Cyanose - yes, but I think 1.24 is going to be the next release. 1.22 got pulled because of issues found during internal testing and I have no idea what happened to 1.23 (I assume the same).
 
@hughsie - Thumbs up from me and if any bombs get thrown just bounce them my way. I never got a reply back to my previous probe about this so silence is taken as acceptance....

**Comment by Cyanose** [comment]
@mrhpearson, @hughsie I've recently discovered that despite AC directory being-no existent in the file system, the battery can still be charged. What actually causes the problem with the battery charging is trying to limit the maximum battery treshold via the systemd daemon that writes to the `/sys/class/power_supply/BAT0/charge_control_start_threshold` and `/sys/class/power_supply/BAT0/charge_control_end_threshold` files) this caused the problem with charging. 

I managed to limit it `via` tlp and It seems like working (Either setting limit for charging and actual charging)

**Comment by mrhpearson** [comment]
1.24 has been released which should fix this issue - can we confirm and close if it's good
