### ISSUE TITLE
Bios Bug Lenovo ThinkPad T14/P14s Gen 2 AMD System Firmware R1MET51W, Version 0.1.21

### ISSUE THREAD

**Issue by sisyphus74** [fwupd/firmware-lenovo#288]
i get following errors on boot:
```
Nov 10 08:31:11 poseidon kernel: ACPI BIOS Error (bug): Failure creating named object [\_SB.WMI6], AE_ALREADY_EXISTS (20220331/dswload2-326)
Nov 10 08:31:11 poseidon kernel: fbcon: Taking over console
Nov 10 08:31:11 poseidon kernel: ACPI Error: AE_ALREADY_EXISTS, During name lookup/catalog (20220331/psobject-220)
Nov 10 08:31:11 poseidon kernel: ACPI: Skipping parse of AML opcode: Device (0x5B82)
Nov 10 08:31:11 poseidon kernel: ACPI: 14 ACPI AML tables successfully acquired and loaded

```
machine: Lenovo Thinkpad P14s AMD Gen2
System Firmware R1MET51W, Version 0.1.21
* Bios Update:
 • Prometheus (10.01.3273255 → 10.01.3478575)
 • System Firmware (0.1.19 → 0.1.21)
$ fwupdmgr --version
runtime   org.freedesktop.fwupd         1.8.7
runtime   org.freedesktop.fwupd-efi     1.3
runtime   com.hughsie.libjcat           0.1.12
runtime   com.dell.libsmbios            2.4
compile   com.hughsie.libjcat           0.1.12
runtime   org.kernel                    6.0.7-arch1-1
compile   org.freedesktop.gusb          0.4.2
compile   org.freedesktop.fwupd         1.8.7

latest Arch

$ efivar -l | grep fw
0abba7dc-e516-4167-bbf5-4d9d1c739416-fwupd-8fb7e1f9-447b-41fb-8832-ae5ef955665f-0
$ tree /boot
/boot
├── a1b26f0fbca14d6c9afdc1f6c6e9c874
├── amd-ucode.img
├── EFI
│   ├── arch
│   │   ├── fw
│   │   │   └── fwupd-8fb7e1f9-447b-41fb-8832-ae5ef955665f.cap
│   │   └── fwupdx64.efi
│   ├── BOOT
│   │   └── BOOTX64.EFI
│   ├── Linux
│   └── systemd
│       └── systemd-bootx64.efi
├── initramfs-linux-fallback.img
├── initramfs-linux.img
├── loader
│   ├── entries
│   │   └── arch.conf
│   ├── loader.conf
│   └── random-seed

    Operating system and version: latest arch
    Have you tried rebooting? - yes
    Are you using an NVMe disk? - yes
    Is secure boot enabled? - no
    Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS? - ?

See Issue: https://github.com/fwupd/firmware-lenovo/issues/262

**Comment by sisyphus74** [comment]
@mrhpearson is this a consequential error from: https://github.com/fwupd/firmware-lenovo/issues/262?

**Comment by mrhpearson** [comment]
Hi @sisyphus74 

I don't think it's related to the other bug - it's another, fairly benign, error reported at boot.

As noted in #262 - if you could report this on the Lenovo linux forum (https://forums.lenovo.com/t5/Linux-Operating-Systems/ct-p/lx_en)  that would be appreciated. Try and keep the LVFS issues for firmware update issues rather than the firmware itself.

Thanks!
Mark

**Comment by sisyphus74** [comment]
Hi @mrhpearson, thanks for your answer. Its already done: https://forums.lenovo.com/t5/ThinkPad-P-and-W-Series-Mobile-Workstations/ACPI-BIOS-Error-Bug-after-Bios-Upgrade-Failure-creating-named-object/m-p/5181338
