### ISSUE TITLE
Lenovo T14 Gen2i - No sound nor input after LVFS ME update (Ubuntu 20.04)

### ISSUE THREAD

**Issue by ruimbribeiro** [fwupd/firmware-lenovo#295]
After updating to the latest ME version, I got several problems on my laptop.

- First a screen started to appear on restart: `Recovering ME update ... Failed to recover (this was failing around 60%).`
- I got a DummyOutput in the Sound settings
- No input is detected as well.

After doing `fwupdmgr reinstall` I have no more the "Recovering ME" screen.

Still I have no sound nor input.

I find it odd that the version that LVFS installed is not supported for my Lenovo laptop 

As per Lenovo Website.
https://support.lenovo.com/in/en/downloads/ds558339-intel-management-engine-150-firmware-consumer-update-utility-thinkpad

```
Support models      
ThinkPad P15  Gen 2i  (Machine types: 20YQ, 20YR)
ThinkPad P15v Gen 2i  (Machine types: 21A9, 21AA)
ThinkPad T15  Gen 2i  (Machine types: 20W4, 20W5)
ThinkPad T15p Gen 2i  (Machine types: 21A7, 21A8)
```

**System info**

```
fwupdmgr get-history
20W0S0RW00
│
├─SKHynix HFS512GDE9X081N:
│ │   Device ID:          04e17fcf7d3de91da49a163ffe4907855c3648be
│ │   Previous version:   41720C20
│ │   GUID:               34f9d6fa-e1d6-5d7d-909e-0406644298c5
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─PC711 512GB:
│       New version:      41730C20
│       Remote ID:        lvfs
│       Release ID:       12987
│       Summary:          SK hynix PC711 512GB NVMe SSD Firmware for Lenovo PC
│       License:          Proprietary
│       Size:             1,4 MB
│       Created:          2022-04-20
│       Urgency:          High
│       Vendor:           Lenovo
│       Description:      
│       Firmware update may fail when HDD password is set in BIOS.In that case, remove HDD password then try update again.
│       
│       Firmware and device description: SKHynix_HFS512GDE9X081N, Firmware Version: 41730C20
│       
│       Supported device description: SKHynix_HFS512GDE9X081N, Firmware Version: 41710C20, 41720C20
│       
│       Supported Product Scope - Lenovo ThinkPad, ThinkCentre, ThinkStation, IdeaCentre
│     
├─Embedded Controller:
│ │   Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
│ │   Previous version:   0.1.41
│ │   Update State:       Success
│ │   GUID:               2a5d161c-0ba2-4136-94b3-c027f0a7e5fc
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Reported to remote server
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─ThinkPad T14 Gen 2 / P14s Gen 2 / T15 Gen 2 / P15s Gen 2:
│       New version:      0.1.42
│       Remote ID:        lvfs
│       Release ID:       14474
│       Summary:          Lenovo ThinkPad T14 Gen 2 / P14s Gen 2 / T15 Gen 2 / P15s Gen 2 Embedded Controller Firmware
│       License:          Proprietary
│       Size:             767,3 kB
│       Created:          2022-06-15
│       Urgency:          Medium
│       Vendor:           Lenovo
│       Description:      
│       Embedded Controller Firmware N34HT42W version 1.42
│     
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Previous version:   0.1.52
│ │   Update State:       Success
│ │   Last modified:      2022-12-04 16:50
│ │   GUID:               973a10fa-79c0-453e-b78c-27b55cc0e6eb
│ │   Device Flags:       • Internal device
│ │                       • Updatable
│ │                       • System requires external power source
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Reported to remote server
│ │                       • Device is usable for the duration of the update
│ │ 
│ └─ThinkPad T14 Gen 2 / P14s Gen 2 / T15 Gen 2 / P15s Gen 2:
│       New version:      0.1.52
│       Remote ID:        lvfs
│       Release ID:       14062
│       Summary:          Lenovo ThinkPad T14 Gen 2 / P14s Gen 2 / T15 Gen 2 / P15s Gen 2 System Firmware
│       License:          Proprietary
│       Size:             18,3 MB
│       Created:          2021-06-15
│       Urgency:          Critical
│       Vendor:           Lenovo
│       Description:      
│       This stable release fixes the following issues:
│       
│       • Updated includes a security fix.
│     
└─Intel Management Engine:
  │   Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
  │   Previous version:   240.42.2235
  │   Update State:       Success
  │   Last modified:      2022-12-04 20:57
  │   GUID:               5d19c74d-6a93-489a-a5ed-65cb7f1e13bf
  │   Device Flags:       • Internal device
  │                       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Needs a reboot after installation
  │                       • Reported to remote server
  │                       • Device is usable for the duration of the update
  │ 
  └─ThinkPad T14 Gen 2 / P14s Gen 2 / T15 Gen 2 / P15s Gen 2:
        New version:      240.42.2235
        Remote ID:        lvfs
        Release ID:       15678
        Summary:          Lenovo ThinkPad T14 Gen 2 / P14s Gen 2 / T15 Gen 2 / P15s Gen 2 Consumer ME Firmware
        License:          Proprietary
        Size:             3,8 MB
        Created:          2021-11-17
        Urgency:          High
        Details:          https://pcsupport.lenovo.com/de/en/search?query=N34RN17W
        Vendor:           Lenovo
        Description:      
        This stable release fixes the following issues:
        
        • Updated includes a security fix.

```

```
fwupdmgr update --show-all
Devices with no available firmware updates: 
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
Devices with the latest available firmware version:
 • Embedded Controller
 • Intel Management Engine
 • SKHynix HFS512GDE9X081N
 • System Firmware
 • UEFI dbx
```

**Comment by mrhpearson** [comment]
Sorry - I'd missed this thread. Is this still an issue or did it get resolved? Were you able to reinstall the ME firmware?

Tagging @kmauleon in case she has any suggestions

**Comment by kmauleon** [comment]
will try to ping the owner and feedback thank you very much

@mrhpearson i think this is similar with #250 BIOS fix may need to be applied to different platforms

**Comment by ruimbribeiro** [comment]
Hey @mrhpearson 

```
fwupdmgr reinstall
```

After running reinstall and after a reboot the system took a while but seemed to recover and now I don't have the recover message on boot anymore.

Although I did have to deal with both missing input and output devices. 

Changing the file `/etc/modprobe.d/alsa-base.conf`

And adding: `options snd-hda-intel model=auto` fixed it.

**Comment by mrhpearson** [comment]
OK - I think we're good then on the FW update front at least?

The audio issue is likely not FW update related and is more likely to be related to an OS update or your distro. We can get into the details of that if you want on the Lenovo forums (https://forums.lenovo.com/linux) - my guess is issues with the sof-firmware installation if you're using snd-hda-intel but I'd need to look at logs to be sure.

OK if we close this as this forum is for tracking FW update problems?

Mark

**Comment by adityamukho** [comment]
@mrhpearson still fails on my ThinkPad P15V Gen 2i (Corporate) after `fwupdmgr reinstall` - meaning the firmware update fails.

**Comment by adityamukho** [comment]
I have written in more detail about this here: https://github.com/fwupd/firmware-lenovo/issues/250

**Comment by mrhpearson** [comment]
Ack - I see Chi-Wei and Kathreene have commented on that thread and they're best placed to help so let's see what they come back with

**Comment by kmauleon** [comment]
@mrhpearson should we close this particular ticket? thanks to @ruimbribeiro fixed it by fwupdmgr reinstall with additional steps.... and track the other platforms separately

**Comment by kmauleon** [comment]
will close this one as fixed... let me know if need to reopen... thank you very much.

**Comment by PauloMorgs** [comment]
Folks, I'm having the same issue here. 

> Hey [@mrhpearson](https://github.com/mrhpearson)
> 
> ```
> fwupdmgr reinstall
> ```
> 
> After running reinstall and after a reboot the system took a while but seemed to recover and now I don't have the recover message on boot anymore.
> 
> Although I did have to deal with both missing input and output devices.
> 
> Changing the file `/etc/modprobe.d/alsa-base.conf`
> fwupdmgr reinstall
> And adding: `options snd-hda-intel model=auto` fixed it.

I tried this but there's no alsa-base.conf file. I created one but no success. 

The intel me firmware update and error after each startup does not really bother me, but having no audio is extremely detrimental to my work. I would appreciate any additional help.

It is worth mentioning that when i run `fwupdmgr reinstall` there's only these options available: 

> 
> WARNING: UEFI capsule updates not available or enabled in firmware setup
> See https://github.com/fwupd/fwupd/wiki/PluginFlag:capsules-unsupported for more information.
> 0.	Cancel
> 1.	04e17fcf7d3de91da49a163ffe4907855c3648be (BC711 NVMe SK hynix 512GB)
> 2.	ff75e69eba7f7bc73bf2e2524de4c41d32d61506 (Prometheus)
> 3.	2581b515c779125bfc75dfdf633c3b6651c500d6 (Prometheus (IOTA Config))
> 4.	5bc922b7bd1adb5b6f99592611404036bd9f42d0 (UEFI CA)
> 5.	362301da643102b9f38477387e2193e57abaa590 (UEFI dbx)

Aditional info:
20W000T9US (ThinkPad T14 Gen 2i)
11th Gen Intel(R) Core(TM) i5-1135G7 (8) @ 4.20 GHz
Omarchy 3.2.0
Linux 6.17.8-arch1-1

**Comment by kmauleon** [comment]
@PauloMorgs let's discuss in issue #556 for proper tracking... thank you
