### ISSUE TITLE
Lenovo T590 Upgrade Intel Management Engine from 192.90.2072 to 192.92.2145 failing

### ISSUE THREAD

**Issue by ehsavoie** [fwupd/firmware-lenovo#296]
Upgrade Intel Management Engine from 192.90.2072 to 192.92.2145 I'm on Fedora 37 Plasma.
On reboot the upgrade fails, I see the
'Could not query capsule capabilities: Unsupported...System Reset' Message

├─Intel Management Engine:
│ │   Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│ │   Résumé:             UEFI ESRT device
│ │   Version actuelle:   192.90.2072
│ │   Version minimum:    0.0.1
│ │   Fournisseur:        Lenovo (DMI:LENOVO)
│ │   État de mise à jour:Needs reboot
│ │   Dernière modification:2022-12-05 20:05
│ │   GUID:               2c0665e2-fdbd-495e-b8e4-69d92b9c119a
│ │   Drapeaux de périphérique:• Périphérique interne
│ │                       • Mise à jour possible
│ │                       • Le système nécessite une source d'alimentation externe
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Device is usable for the duration of the update
│ │
│ └─  Nouvelle version:
│       Licence:          Inconnu
│       Description:
│       The vendor did not supply any release notes.
│
├─System Firmware:
│ │   Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Résumé:             UEFI ESRT device
│ │   Version actuelle:   0.1.77
│ │   Version minimum:    0.1.71
│ │   Fournisseur:        Lenovo (DMI:LENOVO)
│ │   État de mise à jour:Success
│ │   GUIDs:              603baf73-b997-45b5-86b4-2f981a008e18
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │   Drapeaux de périphérique:• Périphérique interne
│ │                       • Mise à jour possible
│ │                       • Le système nécessite une source d'alimentation externe
│ │                       • Supported on remote server
│ │                       • Needs a reboot after installation
│ │                       • Cryptographic hash verification is available
│ │                       • Device is usable for the duration of the update

**Comment by kmauleon** [comment]
hi @ehsavoie already pinged MEFW owner... will update once I got feedback from them... thank you very much

**Comment by kmauleon** [comment]
hi @hughsie could this be a fwupd issue? owner's findings as below.  Please advise.  Thank you very much.
Fedora 35	1.6.4	     PASS
Fedora 37	1.8.7	     Failed

**Comment by hughsie** [comment]
> Could not query capsule capabilities: Unsupported

This means that fwupd-efi did `RT->QueryCapsuleCapabilities` and that returned `EFI_UNSUPPORTED`. In that case we log a warning, and then assume `EfiResetWarm` _and then_ call `RT->UpdateCapsule`.

@ehsavoie can you confirm the version you have installed of fwupd-efi please. Do you also see a debug line of `Capsules: 1` on the boot screen, on the next line after ...`assuming EfiResetWarm: Unsupported`?

**Comment by kmauleon** [comment]
also can you please try to update one firmware at a time... BIOS System Firmware or EC Firmware first then MEFW

**Comment by kmauleon** [comment]
as per owner this could be fwupd related @hughsie 
I think it related to fwupd tool, because 1.6.4 version is PASS but 1.8.8 failed.
Could you let linux owner to check this issue firstly?

btw @ehsavoie can you please try >> fwupdmgr reinstall

**Comment by kmauleon** [comment]
as per owner, please update BIOS to 1.78 which implemented a fix for MEFW capsule update... thank you very much

**Comment by kmauleon** [comment]
hi @ehsavoie have you tried updating BIOS to 1.78?

**Comment by kmauleon** [comment]
@ehsavoie any update from your side please

**Comment by kmauleon** [comment]
no update for a year... closing this for now...
