### ISSUE TITLE
Thinkpad X1 carbon 9th gen won't install new embedded controller fw

### ISSUE THREAD

**Issue by PixelHegel** [fwupd/firmware-lenovo#297]
**Describe the bug:**
1. I got the X1c 9th from a secondary market and found it has a low version of BIOS. 0.x.x BIOS (I don't remember the exact version), and N32HT10x (0.10) embedded controller fw
2. I'm running an Archlinux, at the beginning I burn a bootable CD into a USB disk to update the BIOS, and the BIOS is updated to N32ET81W(1.57) successfully, but the Embedded Controller is still N32HT10x (0.10). And it started show `2nd ECDSA region was changed. Please update ECFW which corresponds it` when power on.
3. Then I tried to use `fwupdmgr` to update the embedded controller, I tried ` fwupdmgr update, fwupdmgr install XXXXXX.cab`, but after install/reboot( looks like the update process went well, no error message, and I can see a progress bar under the Lenovo logo), but after reboot, the version of embedded controller is still  N32HT10x (0.10)

**Other ways I have tried:**
1. I have tried downgrading the BIOS to the lowest version(1.47) I can get with fwupdmgr, and updating it again,  the EC version is still N32HT10x (0.10)
2. I also tried using another disk with windows installed, using the windows Lenovo fw update tool to do this, but the issue still remains, the version of embedded controller fw never changed, and it's still N32HT10x (0.10)

**Steps to Reproduce**
sudo fwupmgr update
reboot

**fwupdmgr get-updates**

> Devices with no available firmware updates: 
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • UEFI Device Firmware
>  • WDC PC SN730 SDBPNTY-1T00-1101
>  • ELAN0673:00 04F3:3188
>  • 0000:00:1f.5
>  • Integrated Camera
>  • Prometheus IOTA Config
> Devices with the latest available firmware version:
>  • Intel Management Engine
>  • System Firmware
>  • UEFI Device Firmware
>  • Prometheus
> LENOVO 20XWSITH04
> │
> └─Embedded Controller:
>   │   Device ID:          632acf4927c0b5fb53519d6beed3b60adb73f1d5
>   │   Summary:            UEFI ESRT device
>   │   Current version:    0.0.10
>   │   Minimum Version:    0.0.10
>   │   Vendor:             Lenovo (DMI:LENOVO)
>   │   Update State:       Success
>   │   Problems:           • Device requires AC power to be connected
>   │   GUID:               61b65ccc-0116-4b62-80ed-ec5f089ae523
>   │   Device Flags:       • Internal device
>   │                       • System requires external power source
>   │                       • Supported on remote server
>   │                       • Needs a reboot after installation
>   │                       • Device is usable for the duration of the update
>   │                       • Updatable
>   │ 
>   ├─ThinkPad X1 Carbon 9th / X1 Yoga 6th:
>   │     New version:      0.1.33
>   │     Remote ID:        lvfs
>   │     Release ID:       15079
>   │     Summary:          Lenovo ThinkPad X1 Carbon 9th / X1 Yoga 6th Embedded Controller Firmware
>   │     License:          Proprietary
>   │     Size:             767.4 kB
>   │     Created:          2022-08-18
>   │     Urgency:          High
>   │     Vendor:           Lenovo
>   │     Release Flags:    • Is upgrade
>   │     Description:      
>   │     Lenovo Embedded Controller Firmware Version 1.33
>   │     
>   │     Problem fixes
>   │     
>   │     • Fixed an issue where the fans rarely rotate at full speed after resuming from sleep.
>   │   
>   ├─ThinkPad X1 Carbon 9th / X1 Yoga 6th:
>   │     New version:      0.1.32
>   │     Remote ID:        lvfs
>   │     Release ID:       11862
>   │     Summary:          Lenovo ThinkPad X1 Carbon 9th / X1 Yoga 6th Embedded Controller Firmware
>   │     License:          Proprietary
>   │     Size:             767.4 kB
>   │     Created:          2022-02-02
>   │     Urgency:          High
>   │     Vendor:           Lenovo
>   │     Release Flags:    • Is upgrade
>   │     Description:      
>   │     Lenovo Embedded Controller Firmware Version 1.32
>   │     
>   │     Important updates
>   │     
>   │     • Fixed an issue where system may be damaged when 2 AC adapters with different capacity such as 45W and 65W, or docking stations are connected to both Type-C port, and disconnected and connected again alternately.
>   │   
>   ├─ThinkPad X1 Carbon 9th / X1 Yoga 6th:
>   │     New version:      0.1.31
>   │     Remote ID:        lvfs
>   │     Release ID:       10900
>   │     Summary:          Lenovo ThinkPad X1 Carbon 9th / X1 Yoga 6th Embedded Controller Firmware
>   │     License:          Proprietary
>   │     Size:             767.4 kB
>   │     Created:          2021-11-30
>   │     Urgency:          High
>   │     Vendor:           Lenovo
>   │     Release Flags:    • Is upgrade
>   │     Description:      
>   │     Lenovo Embedded Controller Firmware Version 1.31
>   │     
>   │     Problem fixes
>   │     
>   │     • Fixed an issue where Proximity sensor detects an error.
>   │   
>   ├─ThinkPad X1 Carbon 9th / X1 Yoga 6th:
>   │     New version:      0.1.30
>   │     Remote ID:        lvfs
>   │     Release ID:       10550
>   │     Summary:          Lenovo ThinkPad X1 Carbon 9th / X1 Yoga 6th Embedded Controller Firmware
>   │     License:          Proprietary
>   │     Size:             767.4 kB
>   │     Created:          2021-11-05
>   │     Urgency:          High
>   │     Vendor:           Lenovo
>   │     Release Flags:    • Is upgrade
>   │     Description:      
>   │     Lenovo Embedded Controller Firmware Version 1.30
>   │     
>   │     New functions or enhancements
>   │     
>   │     • Added automatic performance adjustment feature while meeting application is running.(This is for Windows only.)
>   │   
>   ├─ThinkPad X1 Carbon 9th / X1 Yoga 6th:
>   │     New version:      0.1.29
>   │     Remote ID:        lvfs
>   │     Release ID:       9732
>   │     Summary:          Lenovo ThinkPad X1 Carbon 9th / X1 Yoga 6th Embedded Controller Firmware
>   │     License:          Proprietary
>   │     Size:             767.4 kB
>   │     Created:          2021-08-05
>   │     Urgency:          High
>   │     Vendor:           Lenovo
>   │     Release Flags:    • Is upgrade
>   │     Description:      
>   │     Lenovo Embedded Controller Firmware Version 1.29
>   │     
>   │     Problem fixes
>   │     
>   │     • Fixed a flicker issue happened on a specific monitor.
>   │   
>   ├─ThinkPad X1 Carbon 9th / X1 Yoga 6th:
>   │     New version:      0.1.27
>   │     Remote ID:        lvfs
>   │     Release ID:       9331
>   │     Summary:          Lenovo ThinkPad X1 Carbon 9th / X1 Yoga 6th Embedded Controller Firmware
>   │     License:          Proprietary
>   │     Size:             767.4 kB
>   │     Created:          2021-07-20
>   │     Urgency:          High
>   │     Vendor:           Lenovo
>   │     Release Flags:    • Is upgrade
>   │     Description:      
>   │     Lenovo Embedded Controller Firmware Version 1.27
>   │     
>   │     Problem fixes
>   │     
>   │     • Fixed an issue where FnLock LED will change when Quick Clean Application is running.
>   │   
>   └─ThinkPad X1 Carbon 9th / X1 Yoga 6th:
>         New version:      0.1.26
>         Remote ID:        lvfs
>         Release ID:       8908
>         Summary:          Lenovo ThinkPad X1 Carbon 9th / X1 Yoga 6th Embedded Controller Firmware
>         License:          Proprietary
>         Size:             767.4 kB
>         Created:          2021-06-14
>         Urgency:          High
>         Vendor:           Lenovo
>         Release Flags:    • Is upgrade
>         Description:      
>         Lenovo Embedded Controller Firmware Version 1.26

      
**fwupdmgr get-devices**

> LENOVO 20XWSITH04
> │
> ├─ELAN0673:00 04F3:3188:
> │     Device ID:          00814797ceaa566edb28479cbedd7dbb4399d303
> │     Summary:            Touchpad
> │     Current version:    0x0001
> │     Bootloader Version: 0x0002
> │     Vendor:             ELAN Microelectronics (HIDRAW:0x04F3)
> │     GUIDs:              b88767d5-e812-52cc-9d41-52f955688447 ← HIDRAW\VEN_04F3&DEV_3188
> │                         c1707114-b7a7-5b01-8eed-86e953846079 ← HIDRAW\VEN_04F3&DEV_3188&REV_00
> │                         ff773656-f4e2-5780-886a-95e7620d5ca5 ← HIDRAW\VEN_04F3&DEV_3188&MOD_0003
> │                         4b808d27-c833-50cc-8177-9a401f5c08fe ← ELANTP\ICTYPE_14
> │                         2830260e-1d93-5488-87c1-6fede038f24a ← ELANTP\ICTYPE_14&MOD_0003
> │                         4615b877-5b3e-5165-8cdf-477b2e7eb556 ← ELANTP\ICTYPE_14&MOD_0003&DRIVER_HID
> │     Device Flags:       • Internal device
> │                         • Updatable
> │   
> ├─0000:00:1f.5:
> │     Device ID:          b04e387fb80d2b91f37a4d0c7b21461c451775e1
> │     Summary:            Memory Technology Device
> │     Vendor:             DMI:LENOVO
> │     GUIDs:              5f93d7e7-e282-59b9-b663-0146e382f8f6 ← MTD\NAME_0000:00:1f.5
> │                         1d5d8ab8-c56e-59b0-9567-d4d306907af8 ← MTD\VENDOR_LENOVO&NAME_0000:00:1f.5
> │                         68e9d87c-4daa-5308-aea9-a4d42105b680 ← MTD\VENDOR_LENOVO&PRODUCT_20XWSITH04&NAME_0000:00:1f.5
> │     Device Flags:       • Internal device
> │                         • Updatable
> │                         • Needs a reboot after installation
> │                         • Cryptographic hash verification is available
> │   
> ├─11th Gen Intel Core™ i7-1185G7 @ 3.00GHz:
> │     Device ID:          4bde70ba4e39b28f9eab1628f9dd6e6244c03027
> │     Current version:    0x000000a4
> │     Vendor:             Intel
> │     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
> │                         30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
> │                         2347ad97-b545-5bae-b6b3-b70a9553cbba ← CPUID\PRO_0&FAM_06&MOD_8C
> │                         1df99df5-22f4-5505-98cc-22dcc53b132a ← CPUID\PRO_0&FAM_06&MOD_8C&STP_1
> │     Device Flags:       • Internal device
> │   
> ├─Embedded Controller:
> │     Device ID:          632acf4927c0b5fb53519d6beed3b60adb73f1d5
> │     Summary:            UEFI ESRT device
> │     Current version:    0.0.10
> │     Minimum Version:    0.0.10
> │     Vendor:             Lenovo (DMI:LENOVO)
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               61b65ccc-0116-4b62-80ed-ec5f089ae523
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Supported on remote server
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─Integrated Camera:
> │     Device ID:          3fa281ddf80d8a06b8ee5d8beb48d38ee95a9627
> │     Current version:    61.1
> │     Vendor:             Azurewave (USB:0x13D3)
> │     Serial Number:      0000
> │     GUIDs:              bc121e30-c172-5bf0-9a06-495355bea278 ← USB\VID_13D3&PID_5411
> │                         ad93a8b9-464b-5ea6-9b06-59d8605805ea ← USB\VID_13D3&PID_5411&REV_6101
> │     Device Flags:       • Updatable
> │   
> ├─Intel Management Engine:
> │     Device ID:          5bfc5b91c18ef8b751d3d052af77b69ebf738038
> │     Summary:            UEFI ESRT device
> │     Current version:    240.42.2235
> │     Minimum Version:    0.0.1
> │     Vendor:             Lenovo (DMI:LENOVO)
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               c1b2be54-d7ed-4e24-a577-7c5f32bb7587
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Supported on remote server
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─Prometheus:
> │ │   Device ID:          0d5d05911800242bb1f35287012cdcbd9b381148
> │ │   Summary:            Fingerprint reader
> │ │   Current version:    10.01.3478575
> │ │   Vendor:             Synaptics (USB:0x06CB)
> │ │   Install Duration:   2 seconds
> │ │   Serial Number:      82846867446248
> │ │   GUIDs:              448868f0-e05d-5849-8fc4-b8fa1ec16bf5 ← USB\VID_06CB&PID_00FC
> │ │                       896bb9a6-a8be-5727-8a3a-43ca249f6933 ← USB\VID_06CB&PID_00FC&REV_0000
> │ │   Device Flags:       • Updatable
> │ │                       • Supported on remote server
> │ │                       • Cryptographic hash verification is available
> │ │                       • Signed Payload
> │ │ 
> │ └─Prometheus IOTA Config:
> │       Device ID:        73e606488fec47b3e3f9288094f66fded0051446
> │       Summary:          Fingerprint reader config
> │       Current version:  0008
> │       Minimum Version:  0008
> │       Vendor:           Synaptics (USB:0x06CB)
> │       GUIDs:            5cfe6094-5ba5-5713-b5a4-bc9d9c0f55df ← USB\VID_06CB&PID_00FC-cfg
> │                         d9fbfaa0-2fc3-5225-aaf4-6c640029b473 ← USB\VID_06CB&PID_00FC&CFG1_3698&CFG2_0
> │       Device Flags:     • Updatable
> │                         • Only version upgrades are allowed
> │                         • Signed Payload
> │     
> ├─System Firmware:
> │ │   Device ID:          a083ebc5138e5e071ef7270cc9a8280722cc7adf
> │ │   Summary:            UEFI ESRT device
> │ │   Current version:    0.1.57
> │ │   Minimum Version:    0.1.39
> │ │   Vendor:             Lenovo (DMI:LENOVO)
> │ │   Update State:       Success
> │ │   Problems:           • Device requires AC power to be connected
> │ │   GUIDs:              14f3350e-cf63-4e68-a0d9-0af1d5389a17
> │ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
> │ │   Device Flags:       • Internal device
> │ │                       • System requires external power source
> │ │                       • Supported on remote server
> │ │                       • Needs a reboot after installation
> │ │                       • Cryptographic hash verification is available
> │ │                       • Device is usable for the duration of the update
> │ │                       • Updatable
> │ │ 
> │ ├─AMT [unprovisioned]:
> │ │     Device ID:        8d5470e73fd9a31eaa460b2b6aea95483fe3f14c
> │ │     Summary:          Hardware and firmware technology for remote out-of-band management
> │ │     Current version:  15.0.42.2235
> │ │     Bootloader Version:15.0.42.2235
> │ │     Vendor:           Intel Corporation (MEI:0x8086)
> │ │     GUIDs:            12f80028-b4b7-4b2d-aca8-46e0ff65814c
> │ │                       f18c7464-aa01-5b3d-bd4f-6623597d0f70 ← MEI\VEN_8086&DEV_A0E0
> │ │                       395a4458-f3a4-54b5-9947-e8b069f33c31 ← MEI\VEN_8086&DEV_A0E0&REV_20
> │ │                       4e60e8d4-fe52-55e2-bcd1-73a0eac30ab2 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_17AA22D5
> │ │                       070acb43-84d6-5cc7-a713-9a9a0cccee24 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_17AA22D5&REV_20
> │ │     Device Flags:     • Internal device
> │ │   
> │ └─BootGuard Configuration:
> │       Device ID:        b0d4430dfa6bde9f0c22680df36dbc8c15c80753
> │       Current version:  20
> │       Vendor:           Intel Corporation (MEI:0x8086)
> │       GUIDs:            dd17041c-09ea-4b17-a271-5b989867ec65
> │                         f18c7464-aa01-5b3d-bd4f-6623597d0f70 ← MEI\VEN_8086&DEV_A0E0
> │                         395a4458-f3a4-54b5-9947-e8b069f33c31 ← MEI\VEN_8086&DEV_A0E0&REV_20
> │                         4e60e8d4-fe52-55e2-bcd1-73a0eac30ab2 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_17AA22D5
> │                         070acb43-84d6-5cc7-a713-9a9a0cccee24 ← MEI\VEN_8086&DEV_A0E0&SUBSYS_17AA22D5&REV_20
> │       Device Flags:     • Internal device
> │     
> ├─TPM:
> │     Device ID:          c6a80ac3a22083423992a3cb15018989f37834d6
> │     Current version:    1.258.0.0
> │     Vendor:             ST Microelectronics (TPM:STM)
> │     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
> │                         84df3581-f896-54d2-bd1a-372602f04c32 ← TPM\VEN_STM&DEV_0001
> │                         bfaed10a-bbc1-525b-a329-35da2f63e918 ← TPM\VEN_STM&MOD_
> │                         70b7b833-7e1a-550a-a291-b94a12d0f319 ← TPM\VEN_STM&DEV_0001&VER_2.0
> │                         06f005e9-cb62-5d1a-82d9-13c534c53c48 ← TPM\VEN_STM&MOD_&VER_2.0
> │     Device Flags:       • Internal device
> │   
> ├─TigerLake-LP GT2 [Iris Xe Graphics]:
> │     Device ID:          5792b48846ce271fab11c4a545f7a3df0d36e00a
> │     Current version:    01
> │     Vendor:             Intel Corporation (PCI:0x8086)
> │     GUIDs:              54ff3ed7-1ea3-5279-975f-93c13bf2aa53 ← PCI\VEN_8086&DEV_9A49
> │                         3c11d563-4f83-5bd1-8369-75359ea6b6f6 ← PCI\VEN_8086&DEV_9A49&REV_01
> │                         b4dd3af7-f47a-5b73-bde1-a429880ed88c ← PCI\VEN_8086&DEV_9A49&SUBSYS_17AA22D5
> │                         28209551-256d-54ce-aaf8-3f0957f5237a ← PCI\VEN_8086&DEV_9A49&SUBSYS_17AA22D5&REV_01
> │                         06f2a40f-75b6-5238-9fac-71ea35045c1c ← PCI\VEN_8086&DEV_9A49&REV_00
> │                         d9576708-72a4-5802-8997-cd7b4f03ec07 ← PCI\VEN_8086&DEV_9A49&SUBSYS_17AA22D5&REV_00
> │     Device Flags:       • Internal device
> │                         • Cryptographic hash verification is available
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
> │     Summary:            UEFI ESRT device
> │     Current version:    2754747
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               7716d876-a9a6-4901-aa97-e3baef2813a9
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
> │     Summary:            UEFI ESRT device
> │     Current version:    1
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               76ca0ad8-4a14-4389-b7e5-fd88791762ad
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          97b6fe9b220c7b9e1a3a1d9f404c00d4fe77ae7e
> │     Summary:            UEFI ESRT device
> │     Current version:    1.2.10
> │     Minimum Version:    0.0.1
> │     Vendor:             Lenovo (DMI:LENOVO)
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               d115756c-5710-49db-a367-cf59e98db5a0
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Supported on remote server
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          ae1abd099407b1d95698d69b7273f7fed5c6f35c
> │     Summary:            UEFI ESRT device
> │     Current version:    1409356159
> │     Minimum Version:    1
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               11fe9275-9b06-4c8d-853e-c6c61dd05891
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          4b78f537b7d3e281a2ecbc83048b8856fb9eb98e
> │     Summary:            UEFI ESRT device
> │     Current version:    1.2.28.0
> │     Vendor:             Lenovo (DMI:LENOVO)
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               aa096a98-94e6-479b-92f7-5771f6f2d96f
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          2656b5b7e7c4f91fef1537f93095449cda5fb264
> │     Summary:            UEFI ESRT device
> │     Current version:    65794
> │     Minimum Version:    65794
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               3eeba6c0-a6f3-4b0e-b27e-cf57f21ca332
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          de4826630a1fc5be5355c9b6b2c4052051f350c6
> │     Summary:            UEFI ESRT device
> │     Current version:    10
> │     Minimum Version:    10
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               2063b1c1-5a43-4a1b-9ddc-3cd6974c3b7b
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
> │     Summary:            UEFI ESRT device
> │     Current version:    1
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               626d93db-2c42-48c3-915a-71f968a81b04
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          f95c9218acd12697af946874bfe4239587209232
> │     Summary:            UEFI ESRT device
> │     Current version:    0
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               3dd84775-ec79-4ecb-8404-74de030c3f77
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          d96de5c124b60ed6241ebcb6bb2c839cb5580786
> │     Summary:            UEFI ESRT device
> │     Current version:    1
> │     Minimum Version:    1
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               69585d92-b50a-4ad7-b265-2eb1ae066574
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          f37fb01122dd62c773f4e84ec89737e059712d59
> │     Summary:            UEFI ESRT device
> │     Current version:    69145
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               4e88068b-41b2-4e05-893c-db0b43f7d348
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          36efb79c255f402f619fa9eb53cd659db51f2a04
> │     Summary:            UEFI ESRT device
> │     Current version:    24833
> │     Minimum Version:    1
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               643508a1-3059-47f7-804b-9cd21fe60384
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─UEFI Device Firmware:
> │     Device ID:          11a7fbdd09ce583e58b899660fe10f147fd155a2
> │     Summary:            UEFI ESRT device
> │     Current version:    3263046
> │     Vendor:             DMI:LENOVO
> │     Update State:       Success
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               88523ddf-3aac-41f6-b15f-dc7bea434b39
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Needs a reboot after installation
> │                         • Device is usable for the duration of the update
> │                         • Updatable
> │   
> ├─USB4 host controller:
> │     Device ID:          a9800468272e0df850248ce0fdae941c5e4abebe
> │     Summary:            Unmatched performance for high-speed I/O
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               e72e778e-94f7-5ed2-b560-1c1262ee217c ← TBT-fixed
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Signed Payload
> │   
> ├─USB4 host controller:
> │     Device ID:          8ea4a41a1436a078768d0c5e5298b866c412309c
> │     Summary:            Unmatched performance for high-speed I/O
> │     Problems:           • Device requires AC power to be connected
> │     GUID:               e72e778e-94f7-5ed2-b560-1c1262ee217c ← TBT-fixed
> │     Device Flags:       • Internal device
> │                         • System requires external power source
> │                         • Signed Payload
> │   
> └─WDC PC SN730 SDBPNTY-1T00-1101:
>       Device ID:          04e17fcf7d3de91da49a163ffe4907855c3648be
>       Summary:            NVM Express solid state drive
>       Current version:    11130001
>       Vendor:             Sandisk Corp (NVME:0x15B7)
>       Serial Number:      20095T451410
>       Problems:           • Device requires AC power to be connected
>       GUIDs:              fccbb6ea-e20e-58ad-bf8a-7fb7d43ff4c2 ← NVME\VEN_15B7&DEV_5006
>                           a39943dd-3afb-54f8-b110-c5a21f071200 ← NVME\VEN_15B7&DEV_5006&REV_00
>                           12c86995-0b90-5ec5-98f3-7a6ed4ca50e0 ← NVME\VEN_15B7&DEV_5006&SUBSYS_15B75006
>                           7b974856-317d-5538-a915-de0a6353750f ← NVME\VEN_15B7&DEV_5006&SUBSYS_15B75006&REV_00
>                           6820f074-c740-5edd-b5fb-7db6ec7ff103 ← WDC PC SN730 SDBPNTY-1T00-1101
>       Device Flags:       • Internal device
>                           • System requires external power source
>                           • Needs a reboot after installation
>                           • Device is usable for the duration of the update
>                           • Updatable

**Comment by hughsie** [comment]
@mrhpearson PVT perhaps?

**Comment by mrhpearson** [comment]
So if you're on 0.0.x firmware - that's, I believe, pre-release. Tread very carefully as it's easy to brick a unit (voice of experience...)

I think I'm going to have to go through the FW release notes and find the interim steps to get you updated. Can you send me a note (markpearson at lenovo dot com) and I'll have to do some digging and then will figure out some instructions for you. We should be able to get this fixed....but whoever sold you that system did not do you any favours :/

**Comment by PixelHegel** [comment]
> So if you're on 0.0.x firmware - that's, I believe, pre-release. Tread very carefully as it's easy to brick a unit (voice of experience...)
> 
> I think I'm going to have to go through the FW release notes and find the interim steps to get you updated. Can you send me a note (markpearson at lenovo dot com) and I'll have to do some digging and then will figure out some instructions for you. We should be able to get this fixed....but whoever sold you that system did not do you any favours :/

Thanks a lot! I have sent you an email

**Comment by mrhpearson** [comment]
Hi - cleaning up my inboxes after the inevitable post holiday swamp...
Did I reply to your email - I couldn't find it and was worried I might have missed it if it arrived just before the holidays. Please send me a nudge with wherever we were at

**Comment by PixelHegel** [comment]
> Hi - cleaning up my inboxes after the inevitable post holiday swamp... Did I reply to your email - I couldn't find it and was worried I might have missed it if it arrived just before the holidays. Please send me a nudge with wherever we were at

Hi @mrhpearson  looks like I haven't gotten your reply,  I sent you an email again just now, thanks for the help!

**Comment by mrhpearson** [comment]
I'm sorry - I'm just not seeing it :( 
Can you try my personal account - the lenovo email server may be filtering you for some reason. mpearson-lenovo at squebb dot ca.
Mark

**Comment by mrhpearson** [comment]
Discussed by email. 
I need to close this case as the system is an unsupported SIT proto system that is not able to be updated by software (nd should not have been released outside Lenovo).
Mark

**Comment by Thinkpadx12** [comment]
Help, my notebook also has this problem, also BIOS update, EC version or 0.15 has not changed, I also bought a second-hand market notebook, maybe also a pre-release version of BIOS, landlord your problem solved? My laptop model is thinkpad x12D-GEN1

**Comment by Thinkpadx12** [comment]
My BIOS version 0.19, EC version 0.15, now BIOS upgraded to version 1.31, EC or 0.15 has not changed, and there is the same problem as the landlord, please ask the bulls if there is a way to solve this problem, I need 0.19 version of BIOS to restore it, my mailbox gmxr@qq.com, if there is this BIOS program please send me a copy, thank you very much.
