### ISSUE TITLE
Missing updates for Lenovo ThinkPad T580/P52s

### ISSUE THREAD

**Issue by davidstrauss** [fwupd/firmware-lenovo#3]
For missing firmware please provide the following items:

* Link to firmware update at OEM website: https://pcsupport.lenovo.com/us/en/products/LAPTOPS-AND-NETBOOKS/THINKPAD-T-SERIES-LAPTOPS/THINKPAD-T580-TYPE-20L9-20LA/downloads/DS502395

* Firmware release date (if available on OEM website): 2019-03-13, but the 2019-02-19 update is also missing

* Link to the device page on LVFS: https://fwupd.org/lvfs/device/com.lenovo.ThinkPadN27ET.firmware

It looks like the firmwares have been uploaded (but maybe embargoed somehow?): https://fwupd.org/lvfs/device/com.lenovo.ThinkPadN27ET.firmware/analytics

The graph shows two 2019 Q1 uploads for the device, which matches Lenovo's firmware release count for 2019 so far. Yet, neither appears on the LVFS site or on my Fedora-based desktop.

**Comment by kmauleon** [comment]
latest firmware available [here](https://fwupd.org/lvfs/search?value=T580). please check. thank you very much.
