### ISSUE TITLE
Lenovo Intel Management Engine Install has wrong version.

### ISSUE THREAD

**Issue by g4borg** [fwupd/firmware-lenovo#300]
Intel Platform Update 2022.3 Product Version Maintenance Release Version LVFS: 1.25.1932 reports unfortunately as Version 256.25.1932 in the fwupd tool, causing it to install it again and again and again, especially if you run a distro that has fwupd as part of their autoupdate (like discover on kde-neon)

Seems to be simply an issue with the version string somewhere.

Also saw it on other Linux distros.

All tried machines were Lenovo ThinkPad T15p Gen3i

**Comment by g4borg** [comment]
I attach the fwpud get-updates screen that shows the version problem

```
│
└─Intel Management Engine:
  │   Device ID:          <redacted>
  │   Summary:            UEFI ESRT device
  │   Current version:    1.25.1932
  │   Vendor:             Lenovo (DMI:LENOVO)
  │   Update State:       Success
  │   GUID:               23192307-d667-4bdf-af1a-6059db171246
  │   Device Flags:       • Internal device
  │                       • Updatable
  │                       • System requires external power source
  │                       • Supported on remote server
  │                       • Needs a reboot after installation
  │                       • Device is usable for the duration of the update
  │ 
  └─ThinkPad T15p Gen 3i/ P15v Gen 3i:
        New version:      256.25.1932
        Remote ID:        lvfs
        Release ID:       16407
        Summary:          Lenovo ThinkPad T15p Gen 3i/ P15v Gen 3i ME Firmware
        License:          Proprietary
        Size:             3.7 MB
        Created:          2022-10-27
        Urgency:          High
        Details:          https://pcsupport.lenovo.com/de/en/search?query=N3ERN13W
        Vendor:           Lenovo
        Release Flags:    • Is upgrade
        Description:      
        Intel Platform Update 2022.3 Product Version Maintenance Release Version 16.1.25.1932 (LVFS: 1.25.1932) Problem Fixes Mitigated the following security vulnerabilities under issues.Please see fixed issues for details.
```

**Comment by kmauleon** [comment]
hi @g4borg thank you for reporting... I will ping the owner

**Comment by kmauleon** [comment]
hi @g4borg can you please try to execute the following...
fwupdmgr refresh --force
fwupdmgr update

**Comment by g4borg** [comment]
seems like it is fixed, i see no pending updates.

**Comment by beejunk** [comment]
I am seeing this issue on a Lenovo Thinkpad T560 running Kubuntu 22.04. Running the commands suggested by @kmauleon does not work; the updates still show up as pending in the Discover software center.

**Comment by g4borg** [comment]
Did you apply the upgrade at least once by restarting? Does it still show 256.25.1932 as destination upgrade ? If yes we can reopen it 

Maybe paste the fwupd get-updates for the devs

**Comment by kmauleon** [comment]
hi @beejunk please open a separate ticket for proper tracking as they have different owner... Happy Holidays!

**Comment by beejunk** [comment]
I know it's been a while, but wanted to follow up and say that this issue resolved itself on my laptop at some point shortly after my last comment. I'm assuming my system just hadn't picked up the fix yet when I made my comment.
