### ISSUE TITLE
Failed to recover ME Firmware on Thinkpad T15 Gen2

### ISSUE THREAD

**Issue by ScrupPi** [fwupd/firmware-lenovo#303]
After each reboot i get messages prior to BIOS start messages:

> (1) "Reading ME Firmware... Please do not power off! 48% Completed"
> (2) "Recovering ME Firmware...Please do not power off!   10% Completed"
> (3) "Failed to recover ME Firmware..."

After that:
- BIOS starts;
- Ubuntu 22.04 starts, but **audio devices are missing**, both output and input;
- Windows 11 starts. Audio works.

What should i do to fix this problem?

I've tried to install recent ME FW manually or downgrade to previous version, but those failed as well.

To install recent FW i've done:
1) Downloaded "Intel Management Engine 15.0 Firmware (Corporate) Update Utility for Linux - ThinkPad" from [https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t15-gen-2-type-20w4-20w5/downloads/driver-list/component?name=Motherboard%20Devices%20%28core%20chipset,%20onboard%20video,%20PCIe%20switches%29](url)
2) $ sudo fwupdmgr --allow-older --allow-reinstall install n38rk03w.cab

> $ sudo fwupdmgr --allow-older --allow-reinstall install n38rk03w.cab
```
Decompressing…           [***************************************]
No supported devices found
```

> $ sudo dmidecode | grep SKU
```
 		Corporate SKU
 	SKU Number: LENOVO_MT_20W5_BU_Think_FM_ThinkPad T15 Gen 2i
 	SKU Number: Not Specified
```

To downgrade:
> (1) $ sudo fwupdmgr downgrade 349bb341230b1a86e5effe7dfe4337e1590227bd
```
╔══════════════════════════════════════════════════════════════════════════════╗
║ Downgrade Intel Management Engine from 240.42.2235 to 240.41.2142?           ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issues:                              ║
║                                                                              ║
║ • Mitigated the following security vulnerabilities:                          ║
║                                                                              ║
║ 20W5S2SE19 must remain plugged into a power source for the duration of the   ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]:
```
> (2) Confirm, reboot.
> (3) After reboot and "Failed to recover ME Firmware..." message i get this:

```
Error 354: Update to Image with lower VCN is not allowed
Reset System
```
> (4) After that msg "Reading ME Firmware... Please do not power off! 48% Completed" and so on...

Downgrade prevention in BIOS is deactivated.

BIOS info screenshot:
![Screenshot from 2022-12-19 17-56-25](https://user-images.githubusercontent.com/121031580/208431179-3369259f-93bf-4822-a164-c83ec9443ff9.png)

Devices list:
[fwupdmgr_get-devices.txt](https://github.com/fwupd/firmware-lenovo/files/10259238/fwupdmgr_get-devices.txt)

**Comment by kmauleon** [comment]
will ping the owner... thank you very much for reporting

MEFW is already latest as reported by fwupd and BIOS Setup Menu.
Downgrade is not allowed.

@mrhpearson i think this is similar with #250 BIOS fix may need to be applied to different platforms

**Comment by nemo-mona** [comment]
I have the exact same issue. ME failure message and no audrio. I tried the exact same solution myself but also hit a wall that downgrade isn't possible:
After reboot and ME read failure I get:
Specified firmware is older than installed '240.41.2142 < 240.42.2235'

And the it restarts the same with the latest version again. BIOS settings also allow downgrade but are ignored. 
@kmauleon the link you provided doesn't seem to have the solution. 

Anyone knows how I can downgrade the firmware or get fixed FW?

Thanks

**Comment by kmauleon** [comment]
hi @nemo-mona still asking BIOS owners for this one... downgrading MEFW is prohibited... sorry.  Happy holidays!

**Comment by kmauleon** [comment]
can you please try as suggested here >> https://github.com/fwupd/firmware-lenovo/issues/295#issuecomment-1362651135

**Comment by ScrupPi** [comment]
> can you please try as suggested here >> [#295 (comment)](https://github.com/fwupd/firmware-lenovo/issues/295#issuecomment-1362651135)

It worked, problem is gone. Thank you @kmauleon !

1. Did `fwupdmgr reinstall` & `reboot`.
2. Got `Reading ME ...` -> `Recovering ME ...` -> `Failed ...` -> BIOS started boot process.
4. Black screen for 3-5 minutes (suppose it was ME update process).
5. Then normal reboot occured - without `Reading-Recovering-Failed`.
6. Sound issue in Ubuntu is fixed without editing `/etc/modprobe.d/alsa-base.conf`

**Comment by kmauleon** [comment]
great! thank you very much @ScrupPi !  closing this ticket ^_^

**Comment by poti1** [comment]
Worked great for me as well.
Tiny note for others:

ME stand for management engine.
So select that firmware option.

**Comment by aphta** [comment]
Also worked, for me for Ubuntu 24.10. on a T14s . Thank you @kmauleon  !

1. Did `fwupdmgr reinstall` 
2. Choose Option 2
3. I still got "Recovering ME failed" 
4. Waited for 2-3 Minutes (actually I once pressed Enter)
5. Then normal reboot occured - without Reading-Recovering-Failed.
6. Sound issue in Ubuntu is fixed without editing /etc/modprobe.d/alsa-base.conf

edit
7. during the next reboot i had a screen saying "BIOS self-healing process in progress. but it got stuck"
8. I had to unplug the laptop from power
9. pressed the reset button on the back of the laptop
10. during the next reboot tha self healing of the BIOS went thru

Problem seems to be finaly solved. 

Thanks to everyone for the Help

**Comment by hazz-ina62** [comment]
Hello everyone 
I am currently using Windows on this laptop, and I am experiencing an Intel ME firmware problem that appears before the operating system loads.
Each time the machine starts, I see the following pre-boot messages for several minutes:

`Reading ME Firmware... 48%`
`Recovering ME Firmware... 60%`
`Failed to recover ME Firmware...`

After this sequence, Windows eventually boots, but the process takes around 8–10 minutes.

When I attempted the official Intel Management Engine firmware update from Lenovo, the installer generated this message in error.txt:

`Error 280: Detected ME in Recovery Mode`

This indicates that the Management Engine is stuck in Recovery Mode, and the firmware cannot be reflashed from within the OS.

If this Intel ME firmware issue can be resolved through fwupd or any Linux-based flashing method, I am willing to try using Linux Mint to fix it.
At the moment, the ME is stuck in Recovery Mode and shows messages like:

Windows updates and Lenovo tools cannot repair the ME region (the updater reports Error 280: Detected ME in Recovery Mode).
So I would like to test whether Linux tools such as fwupd can successfully reflash or repair the ME firmware. If Linux can handle this, I will move to Linux Mint and attempt the repair process there.

Any advice or confirmation about whether fwupd can fix this situation would be greatly appreciated.

**Comment by kmauleon** [comment]
@hazz-ina62 can you please try procedure from this case https://github.com/fwupd/firmware-lenovo/issues/360#issuecomment-2395047396

**Comment by Q1bit** [comment]
I have the same problem with my ThinkPad P14s Gen 3 after updating Intel ME.
The process shows "Reading ME Firmware... 48%" and "Recovering ME Firmware... 60%", but then fails with "Failed to recover ME Firmware."

I tried using fwupdmgr reinstall (my version is CSME v16.1.38.2676). The progress showed success and it asked for a reboot, but after rebooting, I still get the "Failed to recover ME Firmware" error.

It did not work for me. Could you please help? Is there any other solution?

**Comment by kmauleon** [comment]
hi @Q1bit can you please open a ticket for proper tracking... thank you very much!
