### ISSUE TITLE
T570P51s 0.1.51 and 0.1.52 require 0.1.64 to install

### ISSUE THREAD

**Issue by jonbrenner** [fwupd/firmware-lenovo#313]
Firmware obtained from lvsh: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN1VET.firmware

The following firmware incorrectly requires a higher version (0.1.64) to be installed:
* [Lenovo-ThinkPad-T570P51s-SystemFirmware-0.1.51.cab](https://fwupd.org/downloads/891ce6c766966ea09590c899cf930765526a1ad50eabd60cdf62d144730fcf26-Lenovo-ThinkPad-T570P51s-SystemFirmware-0.1.51.cab)
* [Lenovo-ThinkPad-T570P51s-SystemFirmware-0.1.52.cab](https://fwupd.org/downloads/2e7b3c7bb16aae742bc10dc606b03aaa37139af39346c9e72e36b4e4988bcf27-Lenovo-ThinkPad-T570P51s-SystemFirmware-0.1.52.cab)

Error message: `Not compatible with firmware version 0.1.50, requires >= 0.1.64`

**Comment by hughsie** [comment]
@mrhpearson can you tag the right person please -- I think one of the requirements is screwy.

**Comment by mrhpearson** [comment]
Of course. I've raised internal ticket  LO-2253 to get this resolved. 
I'd like to understand how this happened as well - it's a peculiar mistake to make (and not catch in testing more worryingly)

**Comment by hughsie** [comment]
@mrhpearson there are no signed tests, so I don't think anyone actually tested this before uploading. If they did, they didn't send the signed report. Maybe this gives more weight to making them compulsory? https://lists.linuxfoundation.org/pipermail/lvfs-announce/2022-November/000075.html

**Comment by mrhpearson** [comment]
Hi @hughsie - Let's sync up offline so I can flag it to the team here but no concerns from me; seems a no-brainer. 

Testing and review is part of our sign-off process so should have been done. I was going to pick your brains on if this was maybe something that wouldn't have been caught with an older fwupdmgr maybe? I was waiting to get details back from the FW team first though - China is just coming back online after their new year holiday so I should hear back from them soon.

**Comment by julian-klode** [comment]
P52s 0.1.35 (not on lvfs afaict) is affected too.

**Comment by ChiWei-Chen** [comment]
Hi,
The FW team released 1.53 and the requirement seems removed, could anyone give it a try and see if it works? Thanks!
https://fwupd.org/downloads/b79c9b8908f270e705b8975616e3183a8ee5e41fe14c60b2293e041124b3db28-Lenovo-ThinkPad-T570P51s-SystemFirmware-0.1.53.cab

**Comment by SillieWous** [comment]
I can confirm that it works, writing this on a 0.1.53 machine. ^^

**Comment by ChiWei-Chen** [comment]
@SillieWous thanks for the feedback.

@hughsie , @mrhpearson , can we close this?

@julian-klode , this P52s seems different from this, could you open a new ticket and provide the failed log when executing `sudo fwupdmgr upgrade` ? Thanks!

**Comment by jonbrenner** [comment]
1.53 was downloaded and it installed correctly. Thanks for the resolution.

There is a separate issue where updating blows away my EFI boot entry, which is annoying. I'll create/update a separate issue for that.
