### ISSUE TITLE
Missing BIOS 1.30 for Lenovo Thinkpad T480

### ISSUE THREAD

**Issue by varnie** [fwupd/firmware-lenovo#33]
For missing firmware please provide the following items:

- Link to firmware update at OEM website
https://pcsupport.lenovo.com/ru/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t480-type-20l5-20l6/downloads/ds502355

- Firmware release date (if available on OEM website)
24 Jan 2020

- Link to the device page on LVFS.
https://fwupd.org/lvfs/search?value=t480

**Comment by lijunwang1990** [comment]
we update BIOS to 1.34 now, and the older version will be covered, please use the latest version. Thankyou.
