### ISSUE TITLE
T490s - Intel Management Engine Version invalid?

### ISSUE THREAD

**Issue by Sash2208** [fwupd/firmware-lenovo#330]
In my Fedora Security Dashboard:
![grafik](https://user-images.githubusercontent.com/130969677/232422747-936d112e-2481-443a-962e-5015f1044bff.png)

![grafik](https://user-images.githubusercontent.com/130969677/232423098-05740c2f-7918-4213-8f3f-e3699060cf77.png)

Anyone have an idea why its telling me to install a new version but according to fwupdmgr, the latest version is already installed..

**Comment by hughsie** [comment]
Hmm, unexpected. Can you attach the output of `fwupdmgr get-devices` please?

**Comment by Sash2208** [comment]
Yes, no problem:

LENOVO 20NX000EGE
│
├─USB2.0 Hub:
│ │   Gerätekennung:      b6bcdb236926a2452b472d3dad455c414145b52e
│ │   Zusammenfassung:    USB 3.x hub
│ │   Aktuelle Version:   50.33
│ │   Anbieter:           VIA Labs, Inc. (USB:0x17EF)
│ │   Installationsdauer: 15 Sekunden
│ │   GUIDs:              e2c96871-8be3-530e-a796-5652cee64eeb ← USB\VID_17EF&PID_3071
│ │                       dea51bff-550e-54e7-9b88-d05519771a15 ← USB\VID_17EF&PID_3071&REV_5033
│ │                       6f3f32bd-ac98-523e-9128-ef67941fb614 ← USB\VID_17EF&PID_3071&HUB_20
│ │   Device Flags:       • Aktualisierbar
│ │                       • Kryptografische Hash-Verifizierung ist verfügbar
│ │                       • Gerät führt Aktualisierungen in Etappen durch
│ │                       • Das Gerät kann sich nach Fehlern beim Aufspielen wiederherstellen
│ │                       • Unsignierte Nutzdaten
│ │ 
│ └─USB2.0 Hub:
│       Gerätekennung:    63331ea6a67c1085fbdfda1a9b630896d9fc7ec0
│       Zusammenfassung:  USB 3.x hub
│       Aktuelle Version: 50.34
│       Anbieter:         VIA Labs, Inc. (USB:0x17EF)
│       Installationsdauer:15 Sekunden
│       GUIDs:            e2c96871-8be3-530e-a796-5652cee64eeb ← USB\VID_17EF&PID_3071
│                         f6540363-8288-5dce-86dd-be3656cee148 ← USB\VID_17EF&PID_3071&REV_5034
│                         3545c1f3-4d81-59f7-b9d9-d25d5811e4be ← USB\VID_17EF&PID_3071&HUB_10
│       Device Flags:     • Aktualisierbar
│                         • Kryptografische Hash-Verifizierung ist verfügbar
│                         • Gerät führt Aktualisierungen in Etappen durch
│                         • Das Gerät kann sich nach Fehlern beim Aufspielen wiederherstellen
│                         • Unsignierte Nutzdaten
│     
├─USB3.1 Hub:
│ │   Gerätekennung:      da77984c82b59c6fc69516431f467fd9a8d39a7f
│ │   Zusammenfassung:    USB 3.x hub
│ │   Aktuelle Version:   50.33
│ │   Anbieter:           VIA Labs, Inc. (USB:0x17EF)
│ │   Installationsdauer: 15 Sekunden
│ │   GUIDs:              e2c96871-8be3-530e-a796-5652cee64eeb
│ │                       2c08e9d9-1f25-5564-b4db-49867dd2c593 ← USB\VID_17EF&PID_3070
│ │                       804c86fc-4fc2-5426-8600-14a8691f1083 ← USB\VID_17EF&PID_3070&REV_5033
│ │                       6d51c3aa-707f-5d41-812d-5cb5c8a4a25d ← USB\VID_17EF&PID_3070&HUB_0004
│ │   Device Flags:       • Aktualisierbar
│ │                       • Kryptografische Hash-Verifizierung ist verfügbar
│ │                       • Gerät führt Aktualisierungen in Etappen durch
│ │                       • Das Gerät kann sich nach Fehlern beim Aufspielen wiederherstellen
│ │                       • Unsignierte Nutzdaten
│ │ 
│ └─USB3.1 Hub:
│       Gerätekennung:    d68b5d74453efa336214e42d39ec96008a3fed64
│       Zusammenfassung:  USB 3.x hub
│       Aktuelle Version: 50.34
│       Anbieter:         VIA Labs, Inc. (USB:0x17EF)
│       Installationsdauer:15 Sekunden
│       GUIDs:            e2c96871-8be3-530e-a796-5652cee64eeb
│                         2c08e9d9-1f25-5564-b4db-49867dd2c593 ← USB\VID_17EF&PID_3070
│                         bf3a0660-00f1-52fc-9b18-2cfa0cbf4dc7 ← USB\VID_17EF&PID_3070&REV_5034
│                         816fc838-78d7-5deb-85ef-a95935318198 ← USB\VID_17EF&PID_3070&HUB_0010
│       Device Flags:     • Aktualisierbar
│                         • Kryptografische Hash-Verifizierung ist verfügbar
│                         • Gerät führt Aktualisierungen in Etappen durch
│                         • Das Gerät kann sich nach Fehlern beim Aufspielen wiederherstellen
│                         • Unsignierte Nutzdaten
│     
├─Core™ i7-8565U CPU @ 1.80GHz:
│     Gerätekennung:      4bde70ba4e39b28f9eab1628f9dd6e6244c03027
│     Aktuelle Version:   0x000000f0
│     Anbieter:           Intel
│     GUIDs:              b9a2dd81-159e-5537-a7db-e7101d164d3f ← cpu
│                         30249f37-d140-5d3e-9319-186b1bd5cac3 ← CPUID\PRO_0&FAM_06
│                         561403e8-143a-5071-ab09-bf5e4c146983 ← CPUID\PRO_0&FAM_06&MOD_8E
│                         d5092916-1868-5182-8c70-12f83dab6372 ← CPUID\PRO_0&FAM_06&MOD_8E&STP_C
│     Device Flags:       • Internes Gerät
│   
├─Embedded Controller:
│     Gerätekennung:      2292ae5236790b47884e37cf162dcf23bfcd1c60
│     Zusammenfassung:    UEFI ESRT device
│     Aktuelle Version:   0.1.23
│     Minimale Version:   0.1.23
│     Anbieter:           Lenovo (DMI:LENOVO)
│     Aktualisierungsstatus:Erfolg
│     GUID:               be9a5f93-930b-40bf-8864-815268ea4ea3
│     Device Flags:       • Internes Gerät
│                         • Aktualisierbar
│                         • System benötigt externe Stromquelle
│                         • Unterstützt auf dem entfernten Server
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│   
├─INTEL SSDPEKKF512G8L:
│     Gerätekennung:      f2759da7fe8e0388c5f3601cb072f837b1070b03
│     Zusammenfassung:    NVM Express solid state drive
│     Aktuelle Version:   L15P
│     Anbieter:           Intel Corporation (NVME:0x8086)
│     Seriennummer:       PHHP938209CA512C
│     GUIDs:              68db11e5-b0cf-5bc9-a94e-17e28496e505 ← NVME\VEN_8086&DEV_F1A6
│                         79517f86-8df8-5d6e-a18b-33f0b36a78e9 ← NVME\VEN_8086&DEV_F1A6&REV_03
│                         396fb4fd-7656-564f-88b5-381e83ca30c0 ← NVME\VEN_8086&DEV_F1A6&SUBSYS_8086390B
│                         f91a5c60-8696-539e-9d0a-57d194f74ac4 ← NVME\VEN_8086&DEV_F1A6&SUBSYS_8086390B&REV_03
│                         87fd9fec-f447-5ec6-a1cd-d55fac0d3d30 ← INTEL SSDPEKKF512G8L
│     Device Flags:       • Internes Gerät
│                         • Aktualisierbar
│                         • System benötigt externe Stromquelle
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│   
├─Intel Management Engine:
│     Gerätekennung:      349bb341230b1a86e5effe7dfe4337e1590227bd
│     Zusammenfassung:    UEFI ESRT device
│     Aktuelle Version:   192.85.1869
│     Minimale Version:   0.0.1
│     Anbieter:           Lenovo (DMI:LENOVO)
│     Aktualisierungsstatus:Erfolg
│     GUID:               ef5cdc85-9cf6-469d-9cb7-920b7dd6672b
│     Device Flags:       • Internes Gerät
│                         • Aktualisierbar
│                         • System benötigt externe Stromquelle
│                         • Unterstützt auf dem entfernten Server
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│   
├─Prometheus:
│ │   Gerätekennung:      d432baa2162a32c1554ef24bd8281953b9d07c11
│ │   Zusammenfassung:    Fingerprint reader
│ │   Aktuelle Version:   10.01.3478575
│ │   Anbieter:           Synaptics (USB:0x06CB)
│ │   Installationsdauer: 2 Sekunden
│ │   Seriennummer:       82849625179368
│ │   GUIDs:              8088f861-6318-5b1e-9ce4-fbddbedb09ac ← USB\VID_06CB&PID_00BD
│ │                       09e8bf16-3e69-50f5-bb66-c7a040248352 ← USB\VID_06CB&PID_00BD&REV_0000
│ │   Device Flags:       • Aktualisierbar
│ │                       • Unterstützt auf dem entfernten Server
│ │                       • Kryptografische Hash-Verifizierung ist verfügbar
│ │                       • Signierte Nutzdaten
│ │ 
│ └─Prometheus IOTA Config:
│       Gerätekennung:    8dcffb5d059857368caa2b7b22371ebd831b0c0c
│       Zusammenfassung:  Fingerprint reader config
│       Aktuelle Version: 0028
│       Minimale Version: 0028
│       Anbieter:         Synaptics (USB:0x06CB)
│       GUIDs:            7c5a1e62-38fa-5859-9337-09dbac6377e4 ← USB\VID_06CB&PID_00BD-cfg
│                         21a62213-7012-552c-9f1a-a51d07c87242 ← USB\VID_06CB&PID_00BD&CFG1_3462&CFG2_0
│       Device Flags:     • Aktualisierbar
│                         • Unterstützt auf dem entfernten Server
│                         • Nur Versionsaktualisierungen sind erlaubt
│                         • Signierte Nutzdaten
│     
├─System Firmware:
│ │   Gerätekennung:      a45df35ac0e948ee180fe216a5f703f32dda163f
│ │   Zusammenfassung:    UEFI ESRT device
│ │   Aktuelle Version:   0.1.79
│ │   Minimale Version:   0.1.62
│ │   Anbieter:           Lenovo (DMI:LENOVO)
│ │   Aktualisierungsstatus:Erfolg
│ │   GUIDs:              6300ba52-d9ea-4ca0-88f9-f89ef73cc07b
│ │                       230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│ │   Device Flags:       • Internes Gerät
│ │                       • Aktualisierbar
│ │                       • System benötigt externe Stromquelle
│ │                       • Unterstützt auf dem entfernten Server
│ │                       • Benötigt einen Neustart nach der Installation
│ │                       • Kryptografische Hash-Verifizierung ist verfügbar
│ │                       • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│ │ 
│ └─UEFI dbx:
│       Gerätekennung:    362301da643102b9f38477387e2193e57abaa590
│       Zusammenfassung:  UEFI revocation database
│       Aktuelle Version: 220
│       Minimale Version: 220
│       Anbieter:         UEFI:Linux Foundation
│       Installationsdauer:1 Sekunde
│       GUIDs:            14503b3d-73ce-5d06-8137-77c68972a341 ← UEFI\CRT_A9087D1044AD18F7A94916D284CBC01827CF23CD8F60B79072C9CAA1FEF4D649
│                         5971a208-da00-5fce-b5f5-1234342f9cf7 ← UEFI\CRT_A9087D1044AD18F7A94916D284CBC01827CF23CD8F60B79072C9CAA1FEF4D649&ARCH_X64
│                         c6682ade-b5ec-57c4-b687-676351208742 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503
│                         f8ba2887-9411-5c36-9cee-88995bb39731 ← UEFI\CRT_A1117F516A32CEFCBA3F2D1ACE10A87972FD6BBE8FE0D0B996E09E65D802A503&ARCH_X64
│       Device Flags:     • Internes Gerät
│                         • Aktualisierbar
│                         • Unterstützt auf dem entfernten Server
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│                         • Nur Versionsaktualisierungen sind erlaubt
│                         • Signierte Nutzdaten
│     
├─TPM:
│     Gerätekennung:      c6a80ac3a22083423992a3cb15018989f37834d6
│     Aktuelle Version:   7.2.2.0
│     Anbieter:           Nuvoton Technology (TPM:NTC)
│     GUIDs:              ff71992e-52f7-5eea-94ef-883e56e034c6 ← system-tpm
│                         fac1c8f3-73c8-5cd6-8330-07a3690b5140 ← TPM\VEN_NTC&DEV_0000
│                         e4a6bfd6-81ba-5d6a-bb28-84be07ee7a29 ← TPM\VEN_NTC&MOD_NPCT75x"!!4rls
│                         e9ccc1dc-960a-5e09-afe9-e59a904b776d ← TPM\VEN_NTC&DEV_0000&VER_2.0
│                         5a6b5ab6-c483-5eec-8a34-23a6d6d120bd ← TPM\VEN_NTC&MOD_NPCT75x"!!4rls&VER_2.0
│     Device Flags:       • Internes Gerät
│                         • System benötigt externe Stromquelle
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät kann sich nach Fehlern beim Aufspielen wiederherstellen
│                         • Die Geheimnisse der vollständigen Festplattenverschlüsselung können bei der Aktualisierung ungültig werden
│                         • Signierte Nutzdaten
│   
├─Thunderbolt host controller:
│     Gerätekennung:      464baa8ffcac354f29b4750ed0931f54891b5f6d
│     Zusammenfassung:    Unmatched performance for high-speed I/O
│     Aktuelle Version:   23.00
│     Anbieter:           Lenovo (THUNDERBOLT:0x0109, TBT:0x0109)
│     GUIDs:              3d3f953a-3408-56fa-81f3-042d73c59c16 ← THUNDERBOLT\VEN_0109&DEV_1806
│                         ea3c7ac8-d937-568a-aab5-e053bd6af9ce ← THUNDERBOLT\VEN_0109&DEV_1806&REV_00
│                         e56d9729-1948-50ec-9a51-bd7448f55816 ← TBT-01091806
│                         1549b317-d074-5089-956b-a043d9b60476 ← TBT-01091806-controller0-0
│     Device Flags:       • Internes Gerät
│                         • Aktualisierbar
│                         • System benötigt externe Stromquelle
│                         • Gerät führt Aktualisierungen in Etappen durch
│                         • Signierte Nutzdaten
│   
├─UEFI Device Firmware:
│     Gerätekennung:      f95c9218acd12697af946874bfe4239587209232
│     Zusammenfassung:    UEFI ESRT device
│     Aktuelle Version:   16851095
│     Minimale Version:   1
│     Anbieter:           DMI:LENOVO
│     Aktualisierungsstatus:Erfolg
│     GUID:               89aab014-a71d-4cae-8824-174808266539
│     Device Flags:       • Internes Gerät
│                         • Aktualisierbar
│                         • System benötigt externe Stromquelle
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│   
├─UEFI Device Firmware:
│     Gerätekennung:      d96de5c124b60ed6241ebcb6bb2c839cb5580786
│     Zusammenfassung:    UEFI ESRT device
│     Aktuelle Version:   117572096
│     Minimale Version:   117572096
│     Anbieter:           DMI:LENOVO
│     Aktualisierungsstatus:Erfolg
│     GUID:               41fc4d0b-3b42-4702-14a5-f615c4b03a42
│     Device Flags:       • Internes Gerät
│                         • Aktualisierbar
│                         • System benötigt externe Stromquelle
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│   
├─UEFI Device Firmware:
│     Gerätekennung:      f37fb01122dd62c773f4e84ec89737e059712d59
│     Zusammenfassung:    UEFI ESRT device
│     Aktuelle Version:   26918
│     Minimale Version:   1
│     Anbieter:           DMI:LENOVO
│     Aktualisierungsstatus:Erfolg
│     GUID:               80c2e1e4-0a6a-42d0-b188-5a218e57c8de
│     Device Flags:       • Internes Gerät
│                         • Aktualisierbar
│                         • System benötigt externe Stromquelle
│                         • Benötigt einen Neustart nach der Installation
│                         • Das Gerät ist während der Dauer der Aktualisierung nutzbar
│   
└─WhiskeyLake-U GT2 [UHD Graphics 620]:
      Gerätekennung:      5792b48846ce271fab11c4a545f7a3df0d36e00a
      Aktuelle Version:   02
      Anbieter:           Intel Corporation (PCI:0x8086)
      GUIDs:              52aa8ac7-c837-561f-af32-b7979cd2f6ed ← PCI\VEN_8086&DEV_3EA0
                          6986c21a-0f3f-5538-bcef-fe4e8cda7ab7 ← PCI\VEN_8086&DEV_3EA0&REV_02
                          07616327-80e8-5a8a-9f8d-3cb40661abc4 ← PCI\VEN_8086&DEV_3EA0&SUBSYS_17AA2286
                          b04f3e30-a317-5349-bbdd-c3c25153a5bd ← PCI\VEN_8086&DEV_3EA0&SUBSYS_17AA2286&REV_02
                          1bb467a3-4af9-53a9-ab48-f588ee6e8066 ← PCI\VEN_8086&DEV_3EA0&REV_00
                          781afc31-5405-5966-8e99-9919e869e38c ← PCI\VEN_8086&DEV_3EA0&SUBSYS_17AA2286&REV_00
      Device Flags:       • Internes Gerät
                          • Kryptografische Hash-Verifizierung ist verfügbar

**Comment by hughsie** [comment]
@mrhpearson the ME with GUID ef5cdc85-9cf6-469d-9cb7-920b7dd6672b has the last release on the LVFS over 1 year ago. Has this model been forgotten, or is it now EoL?

**Comment by Sash2208** [comment]
EOL can not be, then it was apparently forgotten to add to LVFS. What can I do?

**Comment by hughsie** [comment]
@Sash2208 @mrhpearson is able to look internally and find out what's happened.

**Comment by mrhpearson** [comment]
Following up with the FW team - internal ticket is LO-2412

**Comment by kmauleon** [comment]
hi ... it seems ODM missed this... ongoing testing now... will let you know once firmware is put to stable... thank you very much

**Comment by kmauleon** [comment]
latest has been put to stable... please check... thank you very much
[Consumer](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2JRN.firmware)
[Corporate](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2JRM.firmware)

**Comment by Sash2208** [comment]
Many thank, version 192.92.2145 is now installed

**Comment by kmauleon** [comment]
thank you very much for the confirmation... will close this issue
