### ISSUE TITLE
Thinkpad T14s gen3 (amd) - Missing firmwares

### ISSUE THREAD

**Issue by dal00** [fwupd/firmware-lenovo#343]
* Bios is not at the latest 1.31 but at 0.1.30
* NVMe Firmware for MZVL21T0HCLR-00BL7 is over a year old and latest update from this month is missing. This contains significant updates as well.

**Comment by andreas301-sketch** [comment]
X13/T14s Gen 3 AMD Embedded Controller Firmware v. 0.1.25 is also still at stage "testing" for more than 3 month

**Comment by mrhpearson** [comment]
Agreed - not good :(
Internal ticket LO-2505 created. Will check what is happening with the FW team.

**Comment by dal00** [comment]
There was an nvme update yesterday btw.

**Comment by mrhpearson** [comment]
quick update: BIOS 1.30 and EC 1.25 are both now in the stable channel - and the team are testing the latest updates to get those released.

**Comment by dal00** [comment]
Does that also include the update for the Quectel WWAN which seems to be supported by fwupd/lvfs but the latest update is not there for the T14s g3 (amd).

EC 1.25 update applied correctly on my end btw.

**Comment by mrhpearson** [comment]
I'm not sure what the status is on the Quectel modem - completely different team. As we've not done enablement on it for this platform I'll see if I can find out what the plan is - but I would recommend tracking that separately from this ticket.

I also realised I missed checking the NVME - I need to dig into that and check.

**Comment by mrhpearson** [comment]
Hi - version 1.31 has been released to stable. They are working on the update to 1.34 but there were some issues found during testing so it is delayed.
I think we should be OK to close this ticket. Let me know if any objections.

**Comment by dal00** [comment]
@mrhpearson I'm afraid something might be wrong. As EC 1.27 does not seem to be released even for windows yet and no mention on lenovo.com. Is this supposed to be like this? Also no mention of 1.31.

```
$ fwupdmgr update
Devices with no available firmware updates: 
 • ELAN0678:00 04F3:3195
 • EM05-G
 • Fingerprint Sensor
 • Integrated Camera
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade Embedded Controller from 0.1.25 to 0.1.27?                           ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ Some new functionality has also been added:                                  ║
║                                                                              ║
║ • Modify the initialization sequence of expander.                            ║
║ • Add password protection for MPS2845A.                                      ║
║                                                                              ║
║ 21CQCTO1WW must remain plugged into a power source for the duration of the   ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝
Perform operation? [Y|n]: 
n
```

**Comment by ChiWei-Chen** [comment]
@dal00 , could you try with `fwupdmgr refresh`, we saw hundreds of downloads of 1.31 BIOS.

**Comment by dal00** [comment]
@ChiWei-Chen I actually did `fwupdmgr refresh --force` before.

The thing was I didn't do `fwupdmgr get-updates` because that would have showed that 1.31 was there. I have EC 0.1.27 and System Update 0.1.31 avalable now and ready for update.

I was just worried that EC 1.27 went out as a mistake because I could not see it on lenovo.com even.

**Comment by ChiWei-Chen** [comment]
@dal00 , just confirmed with FW team. 1.27 is an official EC version.
The Windows process may take more time, it would go to Lenovo Support site a few days later.
