### ISSUE TITLE
Don't see firmware updates for T16G1

### ISSUE THREAD

**Issue by j5k** [fwupd/firmware-lenovo#347]
We have a few T16G1 devices and the available firmware versions are different. Some see the newest `N3MET15W (1.14 )`, but some stuck on `N3MET12W (1.11 )` or `N3MET11W (1.10 )` and don't see any updates, even with `refresh --force`.

Is there some delay/phasing built-in or why I can't see an update on some devices?

**Comment by mrhpearson** [comment]
There shouldn't be....at least not that I know of.

Can you share the output from `fwupdmgr get-devices` for a device that isn't updating please?

**Comment by j5k** [comment]
After some investigations I found the reason: if the lid is closed, not all firmware updates will be shown with `get-updates`. This is not intuitive and a pity, because you miss important updates, if you are working with closed lid only. The open lid should be only relevant for firmware installation.

@hughsie is this behavior changeable in a next release?

**Comment by hughsie** [comment]
> @hughsie is this behavior changeable in a next release?

It was changed in the last release -- install https://github.com/fwupd/fwupd/releases/tag/1.9.2 :)

**Comment by j5k** [comment]
Oh nice timing :nerd_face: Thanks!
