### ISSUE TITLE
Thank you for the tool

### ISSUE THREAD

**Issue by LIttleAncientForestKami** [fwupd/firmware-lenovo#36]
I just wanted to thank you for the tool and the work behind it. I was looking for ways to update BIOS and this fell from the sky. :-)

Thank you guys. And also for the LVFS and the website https://fwupd.org/

Kudos. Feel free to close this. :-)

PS. GitHub says it's similar to 4 other issues, but they are all true issues, like missing updates or nothing happens after reboot so I'm opening this either way. :-)

**Comment by hughsie** [comment]
Thanks, it's a great feeling to get tickets like this.
