### ISSUE TITLE
Missing UEFI BIOS update (to 1.81) for Lenovo (ThinkPad) ThinkPad T490/ThinkPad P43s/ThinkPad T590/ThinkPad P53s/ThinkPad T490 HC

### ISSUE THREAD

**Issue by qtux** [fwupd/firmware-lenovo#393]
I think the most recent UEFI firmware update 1.81 according to https://download.lenovo.com/pccbbs/mobiles/n2iur36w.txt for T490 and similar devices is missing on fwupd.org. Could you please add it?

**Comment by mrhpearson** [comment]
I'm seeing this FW offered - can you confirm if the update still isn't showing up?
https://fwupd.org/downloads/acc5421167d3542140f9ac2db00ab1a9f3358e5b420b6b020f540406eaeed120-Lenovo-ThinkPad-T490P43sT590P53sT490HC-SystemFirmware-1.81.cab

**Comment by qtux** [comment]
I can confirm that the update works now, thanks for uploading.
