### ISSUE TITLE
Update not possible - Lenovo ThinkPad P1 Gen5 X1 Extreme Gen5 Corporate ME Firmware, for Hybrid Vpro

### ISSUE THREAD

**Issue by asusdisciple** [fwupd/firmware-lenovo#395]
I am using Ubuntu 22.04. The update "Lenovo ThinkPad P1 Gen5 X1 Extreme Gen5 Corporate ME Firmware, for Hybrid Vpro"
which upgrades from 1.27.2176 -> 257.27.2176 always fails.

**Comment by kmauleon** [comment]
hi @asusdisciple this is a known issue.  your system already has the latest MEFW... please ignore the update for now.  fix is under testing by ODM owner.  thank you very much
