### ISSUE TITLE
Thinkpad T14s Gen 4 AMD is a few versions behind

### ISSUE THREAD

**Issue by ulf5** [fwupd/firmware-lenovo#398]
T14s gen 4 AMD is behind:
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR2EET.firmware
https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t14s-gen-4-type-21f8-21f9/downloads/driver-list/component?name=BIOS%2FUEFI&id=5AC6A815-321D-440E-8833-B07A93E0428C

1.09 vs 1.16

**Comment by ulf5** [comment]
@mrhpearson created this based on your response [here](https://github.com/fwupd/firmware-lenovo/issues/396)

**Comment by mrhpearson** [comment]
Thanks :)
Internal ticket LO-2794 updated.

For historical notes (copied):  I can see 1.17 there but under embargo so I believe they are working on this one and maybe there were issues with LVFS and 1.16? Will find out what is going on.

**Comment by frittentheke** [comment]
> Thanks :) Internal ticket LO-2794 updated.
> 
> For historical notes (copied): I can see 1.17 there but under embargo so I believe they are working on this one and maybe there were issues with LVFS and 1.16? Will find out what is going on.

Do you have any update yet @mrhpearson ?

**Comment by mrhpearson** [comment]
Afraid not yet - waiting for an ETA from the FW team.

**Comment by ulf5** [comment]
Now it seems no version at all is available, unless it moved?

**Comment by alexlud** [comment]
1.16 was published today. 
I was able to upgrade from 1.11 to 1.16 (fwupd-1.9.11-1.fc39.x86_64).

**Comment by ChiWei-Chen** [comment]
Hi @ulf5 ,
Both 1.18 BIOS/ 1.13 ECFW moved to stable now, please let us know if this doesn't work for you.
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR2EET.firmware
https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR2EHT.firmware
