### ISSUE TITLE
FIrmware problem closed/opening Lid under Ubuntu 22

### ISSUE THREAD

**Issue by asusdisciple** [fwupd/firmware-lenovo#401]
So I am using Ubuntu 22 with a Lenovo Thinkpad P1 Gen 5. This is the behaviour I had from the start and its a bummer
that a 5000$ notebook can't function properly, especially since it is advertised as officially supporting Ubuntu Linux.

Behaviour:

1. Connect notebook to docking station. Docking station is connected to monitor. The lid is closed.
2. I am using hardware encryption for my SSD so I type in the password (works now with new firmware).
3. The Ubuntu user login appears on the screen.
4. Try to login -> Monitor loses signal and goes black. When I open the lid of the notebook the system is basically dead and I cant start it. I have to do a cold reset with the power button.

This does not happen when the lid of the notebook is open.
I can not understand why Lenovo is not able to implement such basic functionality in their most premium notebook - really its beyond me. Don't know if this Github is the right place to address this issue, but at this point I am really frustrated.

**Comment by hughsie** [comment]
This isn't the right place I'm afraid. You probably ought to try the Lenovo forums, sorry that's not more helpful.
