### ISSUE TITLE
Lenovo K14 Gen 1 (21CU0001BR) updates fail

### ISSUE THREAD

**Issue by daltux** [fwupd/firmware-lenovo#403]
**Describe the bug**
Lenovo K14 Gen 1 (21CU0001BR) laptop seems to be mistaken for another model, maybe L14, and thus no related firmware update is ever successful.

**Steps to Reproduce**

- `fwupdmgr update`
- Try upgrading a Lenovo component e.g. **System Firmware** or **Embedded Controller**
  - It looks okay, asks for a reboot
- Reboot
- Lenovo tries to upgrade it
- The OS is started
- `fwupdmgr update` offers the same update
- `fwupdmgr get-devices` says:

```
Update State:       Failed
Update Error:       failed to update to 0: error-auth-error
```

**Expected behavior**
Firmware upgrade is well succeeded after the machine is rebooted

**fwupd version information**

```shell
fwupdmgr --version
compile   com.hughsie.libxmlb           0.3.14
compile   com.hughsie.libjcat           0.1.9
compile   org.freedesktop.fwupd         1.9.11
runtime   org.freedesktop.fwupd-efi     1.4
compile   org.freedesktop.gusb          0.4.5
runtime   org.freedesktop.gusb          0.4.5
runtime   org.freedesktop.fwupd         1.9.11
runtime   org.kernel                    6.6.9-amd64

apt policy fwupd
fwupd:
  Installed: 1.9.11-1
  Candidate: 1.9.11-1
  Version table:
 *** 1.9.11-1 500
        500 http://debian.pop-sc.rnp.br/debian unstable/main amd64 Packages
        500 http://mirror.uepg.br/debian unstable/main amd64 Packages
        500 http://ftp.br.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status
```

**fwupd device information**
- [fwupdmgr_get-devices.txt](https://github.com/fwupd/fwupd/files/13861096/fwupdmgr_get-devices.txt)

**System UEFI configuration**
- `efibootmgr -v`
  - [efibootmgr-v.txt](https://github.com/fwupd/fwupd/files/13861134/efibootmgr-v.txt)
- `efivar -l | grep fw`
  - (there was no output)
- `tree /boot`
  - [treeboot.txt](https://github.com/fwupd/fwupd/files/13861247/treeboot.txt)

**Additional questions**

- Operating system and version: **Debian GNU/Linux trixie/sid** (updated daily)
- Have you tried rebooting? **yes**
- Is this a regression? I guess **not** as it never worked on this machine besides third-party peripherals like Logitek Unified USB.
- Are you using an NVMe disk? **yes**
- Is secure boot enabled? **Yes** (`mokutil --sb-state` says so)
- Is this a Lenovo system with 'Boot Order Lock' turned on in the BIOS? **Not sure, will confirm**

**Comment by mrhpearson** [comment]
Looks like the same GUID is being used :( I've flagged this to the FW team and will confirm if we need a CHID for this GUID.

Internal ticket LO-2824 for tracking

Please ignore the updates offered for the K-series in the meantime. Unfortunately they aren't in the Linux program so won't get FW updates on LVFS (though they do run Linux well - I got to borrow one for a couple of week).

**Comment by mrhpearson** [comment]
HW ID was added so this should now be fixed. Let me know if you still see it being offered on your K14 G1 as I don't have access to one to test with

**Comment by daltux** [comment]
It currently says there is no available firmware updates, so I believe it is okay now. Thank you very much!
