### ISSUE TITLE
me fw update failed

### ISSUE THREAD

**Issue by issamejekkam** [fwupd/firmware-lenovo#416]
Greetings everyone!

I've encountered a problem with my Lenovo ThinkPad L580 recently, and I'm seeking assistance.

I'm having difficulty understanding the issue. I suspect it might be related to interrupting the Ubuntu installation on my laptop. Every time I power it on, I see the error message "me fw update failed" on the screen. Occasionally, I can access the BIOS and encounter various other messages intermittently. However, the main issue is that the laptop shuts down directly after about 10 seconds, despite trying several troubleshooting tricks from YouTube without success. Could anyone please lend a hand in resolving this?

**Comment by hughsie** [comment]
Did you recently do a firmware update with fwupd?

**Comment by issamejekkam** [comment]
No, i don’t think so.

**Comment by hughsie** [comment]
So,  I think this is a bug, but I don't think it's a fwupd bug I'm afraid. I think you might have more luck with the Lenovo linux forums.

**Comment by issamejekkam** [comment]
Okay, thank you !
