### ISSUE TITLE
ThinkVision - no firmware updates available

### ISSUE THREAD

**Issue by c0d3z3r0** [fwupd/firmware-lenovo#418]
Not sure, if I should open this issue on fwupd or here, but it's Lenovo related, so I chose this repo :)

@mrhpearson any chance Lenovo could start publishing firmware updates for ThinkVision products? I know there are no official updates for most ThinkVision devices, but it might be a good idea to start this and support fwupd from the beginning.

**Comment by mrhpearson** [comment]
It has been discussed internally - but it's quite tricky unfortunately. Not planned for now.

**Comment by c0d3z3r0** [comment]
Is just fwupd tricky or providing updates for ThinkVision? Is it a technical issue or a legal one?
