### ISSUE TITLE
X1 Extreme Gen 5 - Intel ME lvfs fix

### ISSUE THREAD

**Issue by Rick-Alloy** [fwupd/firmware-lenovo#429]
I've still got issues from the bad lvfs firmware that was pushed out last year in that my onboard sound has not worked since, and booting takes around five minutes with the following flow:

"48% Reading ME Firmware...Please do not power off!"
"56% Recovering ME Firmware...Please do not power off!"
"60% Failed to recover ME Firmware..."

This is getting old, well past it actually.

  Is there any word on the fix that is being looked at?  If I throw a spare drive in and install Windows on it, will the MEFW update on the Lenovo site fix the issue?  Is there any known recourse for fixing this?

**Comment by hughsie** [comment]
>  Is there any known recourse for fixing this

Can you `fwupdmgr reinstall` the ME update?

**Comment by Rick-Alloy** [comment]
Unfortunately, no.  The ME firmware will not present as an option even with `--allow-reinstall --allow-older`.

**Comment by kmauleon** [comment]
can you please show results for fwupdmgr get-devices.... thanks

**Comment by Rick-Alloy** [comment]
Sure thing, here's the output.

21DECTO1WW
│
├─ELAN0686:00 04F3:320D:
│     Device ID:          522cb97965758d9b1309d3217dfd41673f410e15
│     Summary:            Touchpad
│     Current version:    0x0003
│     Bootloader Version: 0x0003
│     Vendor:             HIDRAW:0x04F3
│     GUIDs:              71de889a-ea8d-5c66-a0fb-7e11e860cd3d
│                         7e8dad8a-0b0e-527b-8810-d5dbca8804d7
│                         74e88f64-4d6b-5048-8199-fdcc7833b48a
│                         4b808d27-c833-50cc-8177-9a401f5c08fe
│                         e25cd415-0431-502a-9077-3c409b007897
│     Device Flags:       • Internal device
│                         • Updatable
│   
├─Embedded Controller:
│     Device ID:          632acf4927c0b5fb53519d6beed3b60adb73f1d5
│     Summary:            UEFI ESRT device
│     Current version:    0.1.11
│     Minimum Version:    0.1.11
│     Vendor:             Lenovo (DMI:LENOVO)
│     Update State:       Success
│     GUID:               f8963b51-51b6-4059-87c4-722967c16745
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─Fingerprint Sensor:
│     Device ID:          23cf6368c14a875f74c38a5a423518f38d8abbbc
│     Summary:            Match-On-Chip fingerprint sensor
│     Current version:    01000300
│     Vendor:             Goodix (USB:0x27C6)
│     Install Duration:   10 seconds
│     GUIDs:              6322b4f7-0571-5f07-8538-e041bbc70677
│                         14450e82-8667-54c3-98e1-098d8c6dc3b8
│     Device Flags:       • Updatable
│                         • Device can recover flash failures
│                         • Signed Payload
│   
├─Integrated Camera:
│     Device ID:          0fef0a0c55f6442bffaebd774ae771341c89571b
│     Current version:    56.20
│     Vendor:             Chicony Electronics Co.,Ltd. (USB:0x04F2)
│     GUIDs:              b687616d-e0bc-58d3-9022-8f0065eed4ca
│                         bcd2c020-e315-55aa-b7e1-7d2d7108037e
│     Device Flags:       • Updatable
│   
├─Intel Management Engine:
│     Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
│     Summary:            UEFI ESRT device
│     Current version:    1.27.2176
│     Vendor:             Lenovo (DMI:LENOVO)
│     Update State:       Success
│     GUID:               23192307-d667-4bdf-af1a-6059db171246
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─MZVL4256HBJD-00BL7:
│     Device ID:          04e17fcf7d3de91da49a163ffe4907855c3648be
│     Summary:            NVM Express solid state drive
│     Current version:    CL2QHXC7
│     Vendor:             Samsung (NVME:0x144D)
│     GUIDs:              473d1d0f-d24d-5a83-87d8-844bbb9f9411
│                         caade74b-1e15-5ebd-aeb2-7dc4409b95ca
│                         54c7e4f9-5c08-54e5-ad47-7db43eee38d4
│                         37ecdb9a-d43f-58df-b8c7-3f55d7766abb
│                         7fd299a5-add1-5c41-b4b2-02d83d7cd508
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Signed Payload
│   
├─System Firmware:
│     Device ID:          a083ebc5138e5e071ef7270cc9a8280722cc7adf
│     Summary:            UEFI ESRT device
│     Current version:    0.1.21
│     Minimum Version:    0.1.18
│     Vendor:             Lenovo (DMI:LENOVO)
│     Update State:       Success
│     GUIDs:              3a6cdf97-cfb9-479d-9c4c-135e0d4505c9
│                         230c8b18-8d9b-53ec-838b-6cfc0383493a
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Supported on remote server
│                         • Needs a reboot after installation
│                         • Cryptographic hash verification is available
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│     Summary:            UEFI ESRT device
│     Current version:    70154
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               4e88068b-41b2-4e05-893c-db0b43f7d348
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    1
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               69585d92-b50a-4ad7-b265-2eb1ae066574
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          97b6fe9b220c7b9e1a3a1d9f404c00d4fe77ae7e
│     Summary:            UEFI ESRT device
│     Current version:    16777224
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               b451da70-b940-42ec-8dc2-a519690e2623
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          ae1abd099407b1d95698d69b7273f7fed5c6f35c
│     Summary:            UEFI ESRT device
│     Current version:    1
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               23684f26-3bd9-4787-abc8-6fab32d5919a
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          4b78f537b7d3e281a2ecbc83048b8856fb9eb98e
│     Summary:            UEFI ESRT device
│     Current version:    1
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               e5212228-46c9-4190-b064-830baa75ea8c
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          2656b5b7e7c4f91fef1537f93095449cda5fb264
│     Summary:            UEFI ESRT device
│     Current version:    66048
│     Minimum Version:    66048
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               493f355c-7db6-4947-aa72-76d0901f7e5f
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          f95c9218acd12697af946874bfe4239587209232
│     Summary:            UEFI ESRT device
│     Current version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               76ca0ad8-4a14-4389-b7e5-fd88791762ad
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          d96de5c124b60ed6241ebcb6bb2c839cb5580786
│     Summary:            UEFI ESRT device
│     Current version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               626d93db-2c42-48c3-915a-71f968a81b04
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          f37fb01122dd62c773f4e84ec89737e059712d59
│     Summary:            UEFI ESRT device
│     Current version:    22048
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               9497ad8d-bcb5-44af-b4d0-f01064ef3297
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          36efb79c255f402f619fa9eb53cd659db51f2a04
│     Summary:            UEFI ESRT device
│     Current version:    10551296
│     Minimum Version:    57374
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               2a197802-e469-4fa7-a37b-2d681bcf416f
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          11a7fbdd09ce583e58b899660fe10f147fd155a2
│     Summary:            UEFI ESRT device
│     Current version:    3
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               240cf38f-3985-42c5-b77b-8e4bdaf0fcc1
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
├─UEFI Device Firmware:
│     Device ID:          5bfc5b91c18ef8b751d3d052af77b69ebf738038
│     Summary:            UEFI ESRT device
│     Current version:    18548864
│     Minimum Version:    1
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     GUID:               012b2727-3f35-c20a-fb78-d7d4216ce715
│     Device Flags:       • Internal device
│                         • Updatable
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│   
└─Unifying Receiver:
      Device ID:          5859fae972cb36551b299175761b33d8e6e7ce02
      Summary:            Miniaturised USB wireless receiver
      Current version:    RQR12.10_B0032
      Bootloader Version: BOT01.02_B0015
      Vendor:             HIDRAW:0x046D|USB:0x046D
      Install Duration:   30 seconds
      GUIDs:              9d131a0c-a606-580f-8eda-80587250b8d6
                          fcf55bf5-767b-51ce-9c17-f6f538c4ee9f
                          279ed287-3607-549e-bacc-f873bb9838c4
      Device Flags:       • Updatable
                          • Supported on remote server
                          • Unsigned Payload

**Comment by kmauleon** [comment]
hi @Rick-Alloy you already have the latest MEFW... for now please ignore the update notice since the version fix is still under testing by ODM owner... thank you very much

**Comment by Rick-Alloy** [comment]
Hi @kmauleon my issue is that I am caught in the ME firmware recover/fix/fail loop with every boot.  Is there any way to resolve this issue?

**Comment by kmauleon** [comment]
have you tried resetting BIOS to default or maybe set Linux-Firmware-Updater to lowest priority in Boot Menu

**Comment by Rick-Alloy** [comment]
I finally had a chance to look at those suggestions.  Linux Firmware Updater is already at the lowest priority.  I also reset the bios to factory defaults and even did a complete reinstall of the OS.

I still see the Reading, Recovering, Failed on ME firmware at every boot, and onboard sound is still not working in the OS.  I saw that a new firmware update is expected this week, will that address this issue?

**Comment by kmauleon** [comment]
the upcoming update is for the MEFW version fix... not sure though if this will resolve your firmware update loop as well... can you please try to reinstall BIOS firmware via 
"fwupdmgr --allow-reinstall --allow-older install <[cab file](https://fwupd.org/downloads/7405ae173430321bedc5ddab73c801663261a3df40b9a65e80c6655204eab1ea-Lenovo-ThinkPad-P1Gen5X1Extreme5-SystemFirmware-1.20.cab)>"

**Comment by Rick-Alloy** [comment]
I tried that update and while it appeared to succeed, the loops still occurs.  I also updated the MEFW, which is the cause of this update loop, and still ream caught in the loop.  Here is a snap of the BIOS Event log for reference.  As you can see the 16.1.25.1932 MEFW is a factor in this problem.

![fw_log_ss](https://github.com/fwupd/firmware-lenovo/assets/140449892/46eb57d3-3337-4c17-b123-c34acc5da487)

**Comment by Rick-Alloy** [comment]
One interesting thing I learned is that efibootmgr shows BootNext to be the Linux-Firmware-Updater even though I've tried disabling it in BIOS, and I'm wondering if that is part of the issue in the loop.  It seems like the 16.1 update is always pending even after recovery.  Is there a copy of the good latest MEFW to force an upgrade to in hopes of clearing out the pending 16.1 update?

❯ efibootmgr
BootNext: 0001
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0000,0002,001C,001D,001E,001F,0020,0021,0022,0023,0024,0025,0026,0001
Boot0000* ubuntu
Boot0001  Linux-Firmware-Updater
Boot0002* Windows Boot Manager
Boot0010  Setup
Boot0011  Boot Menu
Boot0012  Diagnostic Splash Screen
Boot0013  Lenovo Diagnostics
Boot0014  Asset Information
Boot0015  Regulatory Information
Boot0016  ThinkShield secure wipe
Boot0017  ThinkShield Passwordless Power-On Device Manager
Boot0018  Wi-Fi Configuration
Boot0019  Intel(R) MEBx
Boot001A  Startup Interrupt Menu
Boot001B  Rescue and Recovery
Boot001C* USB CD
Boot001D* USB FDD
Boot001E* NVMe0
Boot001F* NVMe1
Boot0020* ATA HDD0
Boot0021* USB HDD
Boot0022* PXE BOOT
Boot0023* LENOVO CLOUD
Boot0024* ON-PREMISE
Boot0025  Other CD
Boot0026  Other HDD
Boot0027* IDER BOOT CDROM
Boot0028* IDER BOOT Floppy
Boot0029* ATA HDD
Boot002A* ATAPI CD

**Comment by kmauleon** [comment]
I noticed that your MEFW GUID is a mismatch with what is expected... Let's wait for the MEFW version fix as the GUID is related to this one.  Thank you very much.

**Comment by kmauleon** [comment]
ODM just set the firmware to stable please check... thank you very much

**Comment by Rick-Alloy** [comment]
I didn't see it come up in fwupdmgr, so I pulled it from lvfs manually and ran it.

The issues appear to be resolved.  No boot loop, and sound now works within the OS.  Thank you very much.

**Comment by kmauleon** [comment]
great news! thanks for checking @Rick-Alloy... closing this ticket
