### ISSUE TITLE
[Feature] Add Thinkpad X13s system firmware update

### ISSUE THREAD

**Issue by ahoneybun** [fwupd/firmware-lenovo#439]
`fwupdmgr get-devices` output:

├─Prometheus:
│ │   Device ID:          23ec719b6aabc2d2dac5176c232f0da7a21881b0
│ │   Summary:            Fingerprint reader
│ │   Current version:    10.01.3478575
│ │   Vendor:             Synaptics (USB:0x06CB)
│ │   Install Duration:   2 seconds
│ │   Serial Number:      13434744271712
│ │   GUID:               448868f0-e05d-5849-8fc4-b8fa1ec16bf5 ← USB\VID_06CB&PID_00FC
│ │   Device Flags:       • Updatable
│ │                       • Supported on remote server
│ │                       • Cryptographic hash verification is available
│ │                       • Signed Payload
│ │ 
│ └─Prometheus IOTA Config:
│       Device ID:        1c9da4ef563b0ccf0e36e409e3281a1ac62309af
│       Summary:          Fingerprint reader config
│       Current version:  0007
│       Minimum Version:  0007
│       Vendor:           Synaptics (USB:0x06CB)
│       GUIDs:            5cfe6094-5ba5-5713-b5a4-bc9d9c0f55df ← USB\VID_06CB&PID_00FC-cfg
│                         d9fbfaa0-2fc3-5225-aaf4-6c640029b473 ← USB\VID_06CB&PID_00FC&CFG1_3698&CFG2_0
│       Device Flags:     • Updatable
│                         • Only version upgrades are allowed
│                         • Signed Payload
│     
├─System Firmware:
│     Device ID:          a45df35ac0e948ee180fe216a5f703f32dda163f
│     Summary:            UEFI ESRT device
│     Current version:    222626144
│     Minimum Version:    65536
│     Vendor:             LENOVO (DMI:LENOVO)
│     Update State:       Success
│     Problems:           • Device requires AC power to be connected
│     GUIDs:              97c70140-fa24-424e-8b27-b3dca496ec96
│                         230c8b18-8d9b-53ec-838b-6cfc0383493a ← main-system-firmware
│     Device Flags:       • Internal device
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Updatable
│   
├─UEFI Device Firmware:
│     Device ID:          349bb341230b1a86e5effe7dfe4337e1590227bd
│     Summary:            UEFI ESRT device
│     Current version:    3
│     Vendor:             DMI:LENOVO
│     Update State:       Success
│     Problems:           • Device requires AC power to be connected
│     GUID:               fabf4bb2-5f55-48b8-9820-42d5df5435c9
│     Device Flags:       • Internal device
│                         • System requires external power source
│                         • Needs a reboot after installation
│                         • Device is usable for the duration of the update
│                         • Updatable
│   
└─UEFI Device Firmware:
      Device ID:          2292ae5236790b47884e37cf162dcf23bfcd1c60
      Summary:            UEFI ESRT device
      Current version:    196608
      Minimum Version:    57374
      Vendor:             DMI:LENOVO
      Update State:       Success
      Problems:           • Device requires AC power to be connected
      GUID:               42436a3a-f607-4189-8dc4-f167dfc4747c
      Device Flags:       • Internal device
                          • System requires external power source
                          • Needs a reboot after installation
                          • Device is usable for the duration of the update
                          • Updatable

I was able to update the fingerprint reader using `fwupdmgr get-updates`.

**Comment by mrhpearson** [comment]
Sorry, sadly the X13s isn't officially in the Linux program. 
We did a lot of Linux work on it with ARM and Linaro (and I know there is more improvements being done); but I wasn't able to get the FW team to commit to supporting FW updates on LVFS. 
I don't have the same levers as I do with a platform that is fully Linux certified to make this happen.

Recommendation for this platform is to keep a minimal Windows partition available for doing FW updates I'm afraid.
