### ISSUE TITLE
Failed to recover ME Firmware on Thinkpad T14 Gen2

### ISSUE THREAD

**Issue by ilyazat** [fwupd/firmware-lenovo#441]
```
OS: Ubuntu 22.04.4 LTS x86_64 
Host: 20W1S30005 ThinkPad T14 Gen 2i 
Kernel: 6.5.0-28-generic 
Terminal: gnome-terminal 
CPU: 11th Gen Intel i5-1145G7 (8) @ 4.400GHz 
GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics] 
Memory: 4788MiB / 31792MiB 
```

The issue is a kind of same as [this](https://github.com/fwupd/firmware-lenovo/issues/303)

So I try to install update for System Firmware:
```
zzz@notebook:~$ fwupdmgr update  
Devices with no available firmware updates: 
 • Integrated Camera
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI Device Firmware
 • UEFI dbx
Devices with the latest available firmware version:
 • Embedded Controller
 • Intel Management Engine
 • KXG60ZNV512G NVMe TOSHIBA 512GB
╔══════════════════════════════════════════════════════════════════════════════╗
║ Upgrade System Firmware from 0.1.58 to 0.1.61?                               ║
╠══════════════════════════════════════════════════════════════════════════════╣
║ This stable release fixes the following issues:                              ║
║                                                                              ║
║ • Enhancement to address security vulnerability.                             ║
║                                                                              ║
║ Some new functionality has also been added:                                  ║
║                                                                              ║
║ • Updated the Diagnostics module to version 04.33.000.                       ║
║                                                                              ║
║ 20W1S30005 must remain plugged into a power source for the duration of the   ║
║ update to avoid damage.                                                      ║
╚══════════════════════════════════════════════════════════════════════════════╝

Perform operation? [Y|n]: Y
Downloading…             [***************************************] Less than one minute remaining…
Decompressing…           [***************************************]
Decompressing…           [***************************************]
Authenticating…          [***************************************]
Authenticating…          [***************************************]
Restarting device…       [***************************************]
Writing…                 [***************************************]
Scheduling…              [***************************************]
Decompressing…           [***************************************]
Restarting device…       [***************************************]
Waiting…                 [***************************************]
Successfully installed firmware
Do not turn off your computer or remove the AC adapter while the update is in progress.

```

So it is success but 
(1) "Reading ME Firmware... Please do not power off! 48% Completed"
(2) "Recovering ME Firmware...Please do not power off! 10% Completed"
(3) "Failed to recover ME Firmware..."
 
 fail to recover still pops up and it repeats every reboot.
 
 NOTE: I did turned off my PC after first time I set up my Ubuntu. I was afraid that the new computer just had a black screen and held the power button to turn it off. 
 
 So what do I do? Will reinstalling the system help?

**Comment by kmauleon** [comment]
have you tried this one >> https://github.com/fwupd/firmware-lenovo/issues/303#issuecomment-1373192951

Also please try to update one firmware at a time only
update system firmware > restart system
update EC firmware > restart system
update MEFW > restart system

**Comment by ilyazat** [comment]
> have you tried this one >> [#303 (comment)](https://github.com/fwupd/firmware-lenovo/issues/303#issuecomment-1373192951)
> 
> Also please try to update one firmware at a time only update system firmware > restart system update EC firmware > restart system update MEFW > restart system

Yes, I've tried but nothing changed. Could you please consider NOTE? 

> NOTE: I did turned off my PC after first time I set up my Ubuntu. I was afraid that the new computer just had a black screen and held the power button to turn it off.

Can it be a problem? Maybe I forced turning off PC while updating FW?

**Comment by kmauleon** [comment]
can you please show screen shot of BIOS Setup Menu @ilyazat

**Comment by ilyazat** [comment]
![photo_2024-04-27_18-51-41](https://github.com/fwupd/firmware-lenovo/assets/86655859/2fa1a3a7-06b7-4e01-af9d-e92acc7274c7)

**Comment by kmauleon** [comment]
can you please try to manually install System Firmware as below
download [here](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN34ET.firmware)
execute as below
"fwupdmgr --allow -older --allow -reinstall install [cab file]"


if the above procedure did not work, please try to install firmware via USB
[BIOS](https://pcsupport.lenovo.com/ph/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t14-gen-2-type-20w0-20w1/downloads/driver-list/component?name=BIOS%2FUEFI&id=5AC6A815-321D-440E-8833-B07A93E0428C)

**Comment by ilyazat** [comment]
first didn't help. I try the second option

**Comment by ilyazat** [comment]
so how do I do it on Ubuntu?

**Comment by kmauleon** [comment]
you have to create a [bootable USB](https://download.lenovo.com/pccbbs/mobiles/n34ur28w.iso) with this ISO image
[ReadMe](https://download.lenovo.com/pccbbs/mobiles/n34ur28w.html)

**Comment by ilyazat** [comment]
![photo_2024-04-29_15-35-05](https://github.com/fwupd/firmware-lenovo/assets/86655859/86fdd654-9b05-45cb-a886-7fa9a95262cc)

**Comment by kmauleon** [comment]
please allow me to contact ODM owner and will get back to you as soon as possible.... thank you very much!

**Comment by kmauleon** [comment]
@ilyazat are you willing to update the system firmware via shell?  ODM owner can give the file.... if your interested, please send me an email >>> kmauleon at lenovo dot com

**Comment by ilyazat** [comment]
done sir

**Comment by ilyazat** [comment]
i have no problem working with shell. I've already reinstalled my OS but nothing happened

**Comment by kmauleon** [comment]
@ilyazat already forwarded the procedure to your email... please check. thank you...

**Comment by ilyazat** [comment]
can't find it. You sure?

**Comment by kmauleon** [comment]
yes i replied to your gmail il*******at
this is correct right?

**Comment by kmauleon** [comment]
sent another mail... please check @ilyazat thanks...

**Comment by ilyazat** [comment]
thank you so much

now I got it

пн, 6 мая 2024 г., 08:44 kmauleon ***@***.***>:

**Comment by ilyazat** [comment]
For those who follows this thread and met the same problem

After long conversation with the company that makes fw updates I've came to nothing

But problem were resolved somehow after updating OS Ubuntu from 22.04 to 23.10. I don't know how :)

I really appreciate work of support here, thanks @kmauleon

**Comment by kmauleon** [comment]
thanks for the update @ilyazat !

**Comment by norbertg1** [comment]
For people still struggling with ME firmware issue on the boot process, try this: https://github.com/fwupd/firmware-lenovo/issues/360#issuecomment-2395047396

**Comment by weav797** [comment]
> For people still struggling with ME firmware issue on the boot process, try this: [#360 (comment)](https://github.com/fwupd/firmware-lenovo/issues/360#issuecomment-2395047396)

@norbertg1  Will this comment work for Linux too? I'm on Fedora KDE. I tried downgrading via fwupdmgr, but every time it reboots, doesn't seem to apply the changes. I don't have windows installed on this T14s gen 2. Do I have to install Windows to resolve this? I've tried everything else I can, but nothing seems to work.

**Comment by kmauleon** [comment]
@weav797 unfortunately the procedure mentioned only works for windows... please install windows to try the procedure

**Comment by hazz-ina62** [comment]
Hello everyone
I am currently using Windows on this laptop, and I am experiencing an Intel ME firmware problem that appears before the operating system loads.
Each time the machine starts, I see the following pre-boot messages for several minutes:

`Reading ME Firmware... 48%`
`Recovering ME Firmware... 60%`
`Failed to recover ME Firmware...`

After this sequence, Windows eventually boots, but the process takes around 8–10 minutes.

When I attempted the official Intel Management Engine firmware update from Lenovo, the installer generated this message in error.txt:

`Error 280: Detected ME in Recovery Mode`

This indicates that the Management Engine is stuck in Recovery Mode, and the firmware cannot be reflashed from within the OS.

If this Intel ME firmware issue can be resolved through fwupd or any Linux-based flashing method, I am willing to try using Linux Mint to fix it.
At the moment, the ME is stuck in Recovery Mode and shows messages like:

Windows updates and Lenovo tools cannot repair the ME region (the updater reports Error 280: Detected ME in Recovery Mode).
So I would like to test whether Linux tools such as fwupd can successfully reflash or repair the ME firmware. If Linux can handle this, I will move to Linux Mint and attempt the repair process there.

Any advice or confirmation about whether fwupd can fix this situation would be greatly appreciated.

**Comment by weav797** [comment]
> [@weav797](https://github.com/weav797) unfortunately the procedure mentioned only works for windows... please install windows to try the procedure

This is frustrating. I've tried everything else mentioned on this GitHub issue for Linux, but nothing works. The only thing I haven't tried is this Windows thing, and go figure, you need to install windows. Now I have to undergo a whole new project of backing up all data off my laptop just to install windows just to run some executable to fix the firmware. Someone really fudged up the firmware update for Linux... My laptop is just a paperweight until I have time to install windows. Thanks for responding @kmauleon . I appreciate it, but it's not something I wanted to hear.

**Comment by kmauleon** [comment]
@weav797 really sorry for this... let me try to ask ODM CO if they can still provide EFI package for this one... will get back after hearing from them... thank you

**Comment by kmauleon** [comment]
@weav797 message from ODM CO... thank you...

The customer may consider sending the unit to us, as I need to verify whether the EFI package will work—but I currently don’t have an SVT unit available for testing. Moreover, units that have already shipped typically have a locked ME, so I cannot guarantee the EFI-based recovery will succeed.
Alternatively, it would be more reliable if the customer could visit an authorized service center. The engineers there can use an SF600 flash programmer to reprogram only the ME data section of the BIOS image. I’ve encountered this exact issue before, and it was successfully resolved using this method. Since the ME binary contains numerous components, it’s extremely difficult to pinpoint the exact corrupted segment—replacing the entire ME data partition is often the most effective solution.

**Does the customer happen to know the previous ME (Management Engine) version installed on the system?We’ll only be able to pinpoint the root cause accurately once we can reliably reproduce the problem.**

Based on code analysis, ME recovery can fail due to any of the following four conditions:
 
1.The ME Recovery Capsule is not present on the storage device;
2.Memory allocation failure during the recovery process;
3.Failure to read data from the ME Recovery Capsule;
4.ME firmware update failure (e.g., due to verification or flashing errors).
To determine the exact root cause in this case, we need access to the customer’s unit to capture detailed logs during the recovery attempt.

**Comment by kmauleon** [comment]
@weav797 ODM CO is requesting to run this tool in order to get some information of your MEFW...

<img width="1089" height="314" alt="Image" src="https://github.com/user-attachments/assets/f7da8e80-5083-4b42-b648-ce22c775459d" />

[Tool.zip](https://github.com/user-attachments/files/23781182/Tool.zip)
