### ISSUE TITLE
Missing firmware 1.44 (N2NET59W) for Thinkpad P53/P73 (W-BIOS)

### ISSUE THREAD

**Issue by Tabby** [fwupd/firmware-lenovo#447]
* Link to firmware update at OEM website
    https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-p-series-laptops/thinkpad-p53-type-20qn-20qq/20qq/20qqs3831w/pf1by1jm/downloads/ds540999
 * Firmware release date
    18 Apr 2024
 * Link to the device page on LVFS
    https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2NETXXW.firmware

**Comment by mrhpearson** [comment]
Sorry for the slow reply. Looks like the P-BIOS was released but they missed the W-BIOS.
I've created internal ticket LO-3085 to nudge them.
Thanks for reporting

**Comment by mrhpearson** [comment]
FW has been moved to stable - it should be available now (make sure to do a refresh to update your fwupd cache if you don't see it, it was moved only a few hours ago.
Let me know if you see any problems!
