### ISSUE TITLE
Failed to update ME firmware of ThinkPad T14s Gen 3

### ISSUE THREAD

**Issue by ITUNUOLUWA0** [fwupd/firmware-lenovo#449]
Please i need help in fixing my laptop i have checked every plaform on google including the lenovo form and i really would the assistant 
i have trying to fix but anytime i on the i says reading ME firmware please dont power off and at 48 % is fails

**Comment by kmauleon** [comment]
Hi @ITUNUOLUWA0 ,  i forwarded your issue to ODM owner... in the meantime can you please try the following...
SS BIOS Setup Menu so we can know current BIOS/EC version
Set BIOS to default settings
Place Linux-Firmware-Update to lowest boot priority

**Comment by kmauleon** [comment]
as per ODM owner...         

May we know the bios version on customer system, thank you.
I guess bios version is less than N3CET55W(1.36).

**Comment by ITUNUOLUWA0** [comment]
Actually the bios N3CET62W(1.43).

**Comment by ITUNUOLUWA0** [comment]
Should I attempt a roll back or what cause it is the latest uefi Bois version 🤔

**Comment by kmauleon** [comment]
u can try to downgrade but i don't think it's allowed... let me inform ODM regarding your BIOS version... BTW, can we have the SS of BIOS Menu?

**Comment by ITUNUOLUWA0** [comment]
![image](https://github.com/fwupd/firmware-lenovo/assets/173047710/1c8bec30-0f3c-455f-b8b4-cf1451e16172)

**Comment by kmauleon** [comment]
got it... forwarded to ODM owner...

have you tried these..
- Set BIOS to default settings
- Place Linux-Firmware-Update to lowest boot priority

**Comment by ITUNUOLUWA0** [comment]
Have done that already still the same thing

**Comment by kmauleon** [comment]
how about fwupdmgr reinstall?

following up ODM owner...

**Comment by ITUNUOLUWA0** [comment]
How do I do that

**Comment by kmauleon** [comment]
oh.. you can't boot into the OS itself...

how about reinstalling BIOS via USB bootable >> https://pcsupport.lenovo.com/ph/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t14s-gen-3-type-21br-21bs/downloads/driver-list/component?name=BIOS%2FUEFI&id=5AC6A815-321D-440E-8833-B07A93E0428C

**Comment by ITUNUOLUWA0** [comment]
Have download the latest bios already or is why for me roll back and then update the bios fron usb

**Comment by kmauleon** [comment]
yes please try

**Comment by kmauleon** [comment]
hi @ITUNUOLUWA0 any changes from your side?  are you still encountering the issue?  please advise... thank you very much

**Comment by kmauleon** [comment]
@ITUNUOLUWA0 have you tried updating BIOS via USB?  Please advise.  Thank you very much.

**Comment by kmauleon** [comment]
no update... closing for now... please let me know if need to reopen.... thank you very much.
