### ISSUE TITLE
Missing firmware 1.68 for Thinkpad X1 Carbon Gen 9

### ISSUE THREAD

**Issue by j5k** [fwupd/firmware-lenovo#451]
Security-advisory lists 1.67 as affected: https://support.lenovo.com/de/de/product_security/LEN-158632

Official download page offers 1.68:
https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-carbon-9th-gen-type-20xw-20xx/downloads/ds548819-bios-update-utility-bootable-cd-for-windows-10-64-bit-thinkpad-x1-carbon-9th-gen-x1-yoga-6th-gen
With release-date: 06 Jun 2024

Devicepage on LVFS only lists 1.67: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN32ETXXW.firmware

**Comment by mrhpearson** [comment]
FW is on LVFS - but still under embargo.
It usually takes the FW team a couple of weeks to complete their Linux testing and review process for release (unfortunately it doesn't happen in parallel to the release on the lenovo site).
Can we monitor for one more week - if it's not released to stable I'll nag then. Right now it's in their normal mode of operation.

**Comment by j5k** [comment]
Any news on this?

**Comment by mrhpearson** [comment]
Not sure. It's possible there were issues with it as I'm seeing 1.69 on there now (under embargo - uploaded 6 days ago).
Don't know why 1.68 wasn't released
Created internal ticket LO-3185 to find out what is happening.
Mark

**Comment by ChiWei-Chen** [comment]
@j5k , BIOS 1.68 is moved to LVFS stable.
Please let us know if this doesn't work for you.

**Comment by j5k** [comment]
Successfully updated :+1: Thanks!
