### ISSUE TITLE
Update Lenovo 40B0 Thunderbolt 4 Dock firmware (10.16 => 10.18)

### ISSUE THREAD

**Issue by VeldoraTheDragon** [fwupd/firmware-lenovo#452]
We use the Lenovo Thunderbolt 4 docks for our production environment.
Unfortunately, the dock's firmware is outdated on lvfs: `10.16`
The latest version is `1.0.18`.

We would like to ask you to update the firmware to the latest available version so that it can be updated via fwupdmgr, so that no additional windows-vm is required to update the firmware.

Thanks in advance.

**Comment by mrhpearson** [comment]
Under review by the docking team. No ETA yet

**Comment by schuerg** [comment]
Updating _ThinkPad Thunderbolt 4 Dock (10.16 → 10.18)_ from a _Fedora Workstation 40 (6.10.4-200.fc40.x86_64)_ using `fwupdmgr` worked successfully.

**Comment by mrhpearson** [comment]
You beat me to it :) I got the notification from the docking team the FW had been released.
Thanks for confirming it worked for you.

**Comment by marcel151** [comment]
Since I am not allowed to use Linux on my work Laptop (Lenovo T16 Gen 1) and upgrade to 1.0.18 does not work with Windows right now ("MCU check mode response timeout!") I tried to update it with my MacBook Pro 14" using Homebrew (https://formulae.brew.sh/formula/fwupd). Does this differ from the Linux version? As it can't find a newer firmware than my installed 1.0.16.
It's in german, sorry:
"sudo /opt/homebrew/bin/fwupdtool get-updates          
Laden …                  [************************************** ]
Geräte mit keinen verfügbaren Firmware-Aktualisierungen: 
 • USB3.0 Hub
Geräte mit der neuesten verfügbaren Firmware-Version:
 • ThinkPad Thunderbolt 4 Dock
Für die verbleibenden Geräte sind keine Aktualisierungen verfügbar"

**Comment by mrhpearson** [comment]
I think you're better following up with the Lenovo support team on the Windows issue.
As a note - there are two versions of PCB on the docks. I suspect you have the one that got withdrawn (for Windows and LVFS) as there were issues with it - probably why you can't see the update. You're better off waiting for the fix.

If you can confirm what GUID your dock has I think I can look it up and confirm.

**Comment by marcel151** [comment]
Sure:

_ThinkPad Thunderbolt 4 Dock:
│ │   Gerätekennung:      708a5b99d0afc737cdfcab5e16716ecbc6dee884
│ │   Aktuelle Version:   10.16
│ │   Anbieter:           Lenovo (USB:0x17EF)
│ │   Seriennummer:       xxxxxxxxxxxxxxxxxx
│ │   GUIDs:              8d30b09f-bcc5-5379-bc65-9ccceeece1f4 ← USB\VID_17EF&PID_30B4
│ │                       275e4695-9b4e-5263-835e-8681bec8cd1a ← USB\VID_17EF&PID_30B4&CID_40B0
│ │                       09f2cd6f-de67-5046-91ab-7de482e67877
│ │                       4097279c-ef84-58dc-9e12-4d01b1bee044 ← USB\VID_17EF&PID_30B4&CID_40B0&REV_0040
│ │   Geräte-Bitschalter: • Aktualisierbar
│ │                       • System benötigt externe Stromquelle
│ │                       • Unterstützt auf dem entfernten Server
│ │                       • Gerät führt Aktualisierungen in Etappen durch
│ │                       • Signierte Nutzdaten
│ │   Device Requests:    • Message_

**Comment by mrhpearson** [comment]
Yeah - afraid you have the rev4 version of dock, which is the one that has the FW demoted to testing.

If you enable the testing channel you will see the firmware offered again - but I don't recommend it as they are obviously seeing issues in the update process.
It will be moved back to stable once the problems are solved - but you should be able to update from Windows then too.

Mark

**Comment by ojh** [comment]
Is there any news on the release schedule for the rev4 version of the dock? Otherwise, is there any information on the issues encountered with the version in testing (e.g. does the issue only affect Windows)?

Incidentally, the latest firmware appears to be available to download from https://support.lenovo.com/gb/en/downloads/ds554336-firmware-thinkpad-universal-thunderbolt-4-dock-thinkpad-thunderbolt-4-workstation-dock - could I install this via a Windows machine (or a VM?), or does it suffer from the same upgrade issues? :confused:

**Comment by mrhpearson** [comment]
It got moved to stable, and then demoted again I'm afraid. It seems there are issues updating from older versions to the latest and they're adding in extra checks on versions to prevent it getting auto-demoted for too many failures.
You can install the update from a Windows machine (don't think it works from a VM).

**Comment by akvadrako** [comment]
10.18 is apparently still not available. Has anyone tried installed the testing version?

**Comment by hughsie** [comment]
You can install demoted firmware by enabling the lvfs-testing remote, but 10.16 is the newest version on the LVFS for  275e4695-9b4e-5263-835e-8681bec8cd1a

**Comment by mrhpearson** [comment]
Afraid the issues are still under analysis - it's been delayed by the Lunar New Year holidays.

The testing version is the same as the original version. My understanding is that the issues mostly come from not following the update instructions correctly (you have to unplug the dock to complete the update).

**Comment by hughsie** [comment]
> you have to unplug the dock to complete the update

If we can avoid this for future hardware I think that would help *a lot*.

**Comment by mrhpearson** [comment]
100% agreed - it's being worked on.

**Comment by seuchato** [comment]
Hi all
At current we got 3 of these marvellous docks. One, which was on 1.0.7 updated nicely using fwupdmgr. The other two refused repeatedly. Thus I wonder if those two are rev4 versions or not. So I ran 
```
LANG=C fwupdmgr get-devices | grep cd1a

Idle?: 0%
? ?                       275e4695-9b4e-5263-835e-8681bec8cd1a ? USB\VID_17EF&PID_30B4&CID_40B0
```
Is this proof enough, those are really rev4 versions?
greez
chris

**Comment by seuchato** [comment]
Follow up: the string cd1a is not the correct one. Comparing with the one that we got to 1.0.18 I saw the following difference only:
```
│ │   GUIDs:              8d30b09f-bcc5-5379-bc65-9ccceeece1f4 ← USB\VID_17EF&PID_30B4
│ │                       275e4695-9b4e-5263-835e-8681bec8cd1a ← USB\VID_17EF&PID_30B4&CID_40B0
│ │                       09f2cd6f-de67-5046-91ab-7de482e67877
```
The GUID ending with "e67877" makes the difference, all others not. Note:  "e67877" is for the ones that refuse to upgrade from 1.0.16 to 1.0.18. So I'd assume that  "e67877" indicates it is a revision 4 doc?
I'd love to have a positive confirmation for that assumption, beers on me.
Greez
chris

**Comment by managervcf** [comment]
```
compile   org.freedesktop.fwupd         2.0.7
```

```
├─ThinkPad Thunderbolt 4 Dock:
│ │   Device ID:          7073f7228b6ee3d493dfaa222ede7b68832d676e
│ │   Current version:    10.7
│ │   Vendor:             Lenovo (USB:0x17EF)
│ │   Serial Number:      XXXXXXXXXXXXX
│ │   GUIDs:              8d30b09f-bcc5-5379-bc65-9ccceeece1f4 ← USB\VID_17EF&PID_30B4
│ │                       275e4695-9b4e-5263-835e-8681bec8cd1a ← USB\VID_17EF&PID_30B4&CID_40B0
│ │                       ce170cf8-f4a5-52d6-8a6c-f206071a70ba ← USB\VID_17EF&PID_30B4&CID_40B0&DMCVER_10.7
│ │                       4097279c-ef84-58dc-9e12-4d01b1bee044 ← USB\VID_17EF&PID_30B4&CID_40B0&REV_0040
│ │   Device Flags:       • Updatable
│ │                       • System requires external power source
│ │                       • Device stages updates
│ │                       • Signed Payload
│ │                       • Can tag for emulation
│ │   Device Requests:    • Message
```

When I tried to update to 10.18, it returned
```
Not compatible with firmware version 10.7, requires >= 10.16
```

then when I tried to update to 10.16, it returned
```
Not compatible with firmware version 10.7, requires >= 10.13
```

next, I tried to update to 10.13, it returned
```
Not compatible with firmware version 10.7, requires >= 10.11
```

And there is no 10.11 available on LVFS anymore. Does anyone know how I can find this version or what can I do in this situation?

**Comment by seuchato** [comment]
Hi
Doesn't look like you have a "Rev. 4" Dock. Interesting.  
We managed to get ONE of two to something like 10.16 under Windows 11 pro. Not a single one of Rev. 4 docks to 10.18 be it under Windows 10 or 11 pro or OpenSuse, Fedora or Ubuntu. We had one non "Rev. 4" Dock, which was flawlessly upgraded through OpenSuse 15.6. to 10.18.
So, for the time being, and heart bleeding, try M$ Windows.
Greez
chris

**Comment by mrhpearson** [comment]
If you don't mind sharing your Serial number for the dock I can check it against some tables I have.

Probably best not to post publicly - so send to mpearson-lenovo@squebb.ca and I'll confirm exactly which board you've got.

Mark

**Comment by seuchato** [comment]
Mark
Great, you'll get the serials as soon as I am back home again. 
Greetz
chris

**Comment by seuchato** [comment]
Mark
Did you get my mail?

Greez
chris

**Comment by kodiakz** [comment]
```
├─ThinkPad Thunderbolt 4 Dock:
│ │   Device ID:          7073f7228b6ee3d493dfaa222ede7b68832d676e
│ │   Current version:    10.16
│ │   Vendor:             Lenovo (USB:0x17EF)
│ │   Serial Number:      xxxxxxxxxxxxxxxxxxx
│ │   GUIDs:              8d30b09f-bcc5-5379-bc65-9ccceeece1f4 ← USB\VID_17EF&PID_30B4
│ │                       275e4695-9b4e-5263-835e-8681bec8cd1a ← USB\VID_17EF&PID_30B4&CID_40B0
│ │                       09f2cd6f-de67-5046-91ab-7de482e67877 ← USB\VID_17EF&PID_30B4&CID_40B0&DMCVER_10.16
│ │                       fe1be6a9-3027-5135-8e1b-737015e2b5dd ← USB\VID_17EF&PID_30B4&CID_40B0&REV_0042
│ │   Device Flags:       • Updatable
│ │                       • System requires external power source
│ │                       • Device stages updates
│ │                       • Signed Payload
│ │                       • Can tag for emulation
│ │   Device Requests:    • Message
```
```
fwupdmgr update
Devices with the latest available firmware version:
 • ThinkPad Thunderbolt 4 Dock
 • Unifying Receiver
```
`compile   org.freedesktop.fwupd         2.0.12`

Is there still no firmware available for _e67877_ ?

**Comment by seuchato** [comment]
kodiakz
We are waiting, too. We sitt on 3 40B0 Docks, 2 of them unusable.
Then, I should point out that I sent mrhpearson the serials of our docks. He stated they are *all*  "Rev. 4" Dock, regardless of having the "e67877" in their guids or not. And then, I'd like to point out: we were able to bring one of the three  40B0 Docks upgraded through OpenSuse 15.6. to 10.18.
greez
chris

@mrhpearson: could beers or chocolate help ;.)

**Comment by VeldoraTheDragon** [comment]
@mrhpearson just wanted to ask: Have there been any updates to the failing update process, you've mentioned here: https://github.com/fwupd/firmware-lenovo/issues/452#issuecomment-2338311278?
I saw that version 10.18 for the Dock 4 is still in state: "not be suitable for production systems".

**Comment by mrhpearson** [comment]
I discussed this with the docking team just this morning so a timely nudge.

They have some fixes in progress and (I hope I have this right) they need fwupd to use libusb instead of libgusb. This is available with fwupd 2.x which is useful, and they are doing validation with that and dock FW version 10.19. It's not complete yet, but from the update I got this morning they are making progress. I don't have an ETA yet I'm afraid.

Recommendation is still to update your dock from a Windows system if that is an option. The 10.18 update does mostly work, but it's not reliable, hence why it's not recommended (my understanding is it won't brick your dock, it just doesn't always work).

**Comment by seuchato** [comment]
Mark
IF "it won't brick your dock, it just doesn't always work" means, you can get it but you must try, try and try, you'll succeed at last, then I can say, we did exactly that on each of  two of our three docks for 15 to 20 times. No success getting updated under windows.
Other meaning, idea?
greez
chris

**Comment by mrhpearson** [comment]
> If "it won't brick your dock, it just doesn't always work" means, you can get it but you must try, try and try, you'll succeed at last, then I can say, we did exactly that on each of two of our three docks for 15 to 20 times. No success getting updated under windows. Other meaning, idea? greez chris

Don't know I'm afraid - let me check with the team that have been working on this.

**Comment by mrhpearson** [comment]
@seuchato - can you send me your dock serial number (mpearson-lenovo at squebb dot ca). We'll check if it's one of the problematic ones (some PCB versions use a specific USB Hub that is facing issues)

**Comment by altobalta** [comment]
Hi, I'm using this dock with a MBP Pro M1 Max and I don't have a window thunderbolt PC to check the version. On mac I have Firmware Version: 38.6 in Information System. Is there a way to check the firmware version and update-it ? Otherwise, can someone tell me with the serial number which version of the dock I have ? Because I have some troubles with power management of the dock. Thank you

**Comment by martinhoyer** [comment]
> next, I tried to update to 10.13, it returned
> 
> ```
> Not compatible with firmware version 10.7, requires >= 10.11
> ```
> 
> And there is no 10.11 available on LVFS anymore. Does anyone know how I can find this version or what can I do in this situation?

Same here
