### ISSUE TITLE
Failed to run update on reboot: expected 0.1.56 and got 0.1.38

### ISSUE THREAD

**Issue by joe-clark-midsummer** [fwupd/firmware-lenovo#466]
Tried to run firmware updates on a Lenovo X1 Yoga Gen 1 yesterday and got this error.

After the firmware updated, the laptop got stuck on a black screen and was like that for over an hour. Drained the battery overnight and was able to start the laptop and run as normal, but the firmware had not updated. I have reason to believe the exact same thing happened with the same model attempting the same upgrade on the same day (this one went worse and is currently unbootable).

Error report is attached below.
[fw-report.txt](https://github.com/user-attachments/files/16905561/fw-report.txt)

Kind regards,
Joe

**Comment by hughsie** [comment]
@kmauleon in the log there's also a CSME update -- is there a missing requirement on the system BIOS perhaps?

**Comment by hughsie** [comment]
@joe-clark-midsummer if you do a "smaller" update (e.g. to 0.1.39) does that work?

**Comment by kmauleon** [comment]
hi @hughsie this is a very old system and has been End of Support since 2023... i'm afraid we won't be able to support this one.
and yes the version gap is a lot even for the MEFW and it may be helpful to update it one by one.... for BIOS you may want to try to update via USB... and after successful update let's see if you may be able to update the MEFW as well

**Comment by hughsie** [comment]
@joe-clark-midsummer does that help?

**Comment by joe-clark-midsummer** [comment]
Yes it does, thank you. But how does one find the end of Support dates for Lenovo models? I have scoured the internet and am unable to find anything. You would expect somewhere like https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-yoga-type-20fq-20fr to say end of support, but I can't find that anywhere... :/

**Comment by hughsie** [comment]
@kmauleon would you be able to click the "end-of-life" button on your LVFS admin page please? e.g. go to https://fwupd.org/lvfs/devices/status -- e.g.

![Screenshot 2024-09-10 at 09-17-04 LVFS Device Status](https://github.com/user-attachments/assets/18250e76-7413-46ec-8e5a-f43a71d4b5bf)

Feel free to "go wild" and set it for other EOL devices too :)

**Comment by kmauleon** [comment]
oh OK i'll do it...didn't know that ^_^

**Comment by kmauleon** [comment]
done for this device... shall we close this ticket?
![Uploading image.png…]()

**Comment by hughsie** [comment]
> shall we close this ticket

Yup, sorry @joe-clark-midsummer -- try in smaller steps tho, that might work.
