### ISSUE TITLE
Thinkpad T14s Gen 1 Intel not updating since 2022

### ISSUE THREAD

**Issue by vuori** [fwupd/firmware-lenovo#471]
Thinkpad T14s Gen 1 Intel firmwares don't appear to be updating on LVFS. Latest on support site is 1.32, latest on LVFS is 1.23. It seems like updates stopped in early 2022: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2YET.firmware

Meanwhile the AMD version of the same model is up to date: https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadR1CET.firmware

Updating to 1.32 from Windows didn't cause any immediately apparent problems on Linux side. Lenovo fixed LogoFail in 1.29 so getting these rolling on LVFS would be good for users who don't check Vantage or the support site.

**Comment by mrhpearson** [comment]
Thanks for reporting and my apologies - it's not acceptable that they've not delivered the updates. Looks like EC has not been updated in four years.

I've created ticket LO-3320 for internal tracking. It's a holiday in China this week so I won't get a reply until next week - but I'm escalating this as a priority.

**Comment by vuori** [comment]
Good to hear that the matter is moving forward.

Aside not related to LVFS, but in case you wish to notify the firmware team: a T14s G1 Intel running BIOS 1.28 wasn't showing any BIOS updates in Vantage either, just some Windows driver updates. Maybe there's also a problem with pushes to Windows-side autoupdate channels? (IIRC that machine was updated to 1.28 through Vantage last year. I didn't investigate further so this could be just random Vantage jank.)

**Comment by mrhpearson** [comment]
FW should be available now - let me know if any issues.

Mark

**Comment by vuori** [comment]
Thanks for the update. I already applied the update manually so I can't test the LVFS release, but at least version BIOS 1.32 is now showing up in `fwupdmgr get-releases` for me.
