### ISSUE TITLE
Thinkpad E16 Gen1 missing updates

### ISSUE THREAD

**Issue by mkkvcs** [fwupd/firmware-lenovo#473]
The latest BIOS version for the Intel E16 on LVFS is 1.29, the latest on Lenovo's site is 1.34. Intel ME updates are not even being published, even on Lenovo's site. The only firmware that can be updated via fwupd is the bios but on Lenovo's site many additional firmware updates are being published. 

[The updates can be found here](https://pcsupport.lenovo.com/us/en/products/laptops-and-netbooks/thinkpad-edge-laptops/thinkpad-e16-gen-1-type-21jn-21jq/downloads/driver-list)

**Comment by mrhpearson** [comment]
Thanks for the report. I've flagged it to the FW team - internal ticket is LO-3347

**Comment by mrhpearson** [comment]
System FW update 1.34 has been released - let me know if any issues.

The team are working on the ME update, and that will take longer. I'm keeping the internal ticket open to monitor that release and will update here when available.

**Comment by ITMOW** [comment]
> System FW update 1.34 has been released - let me know if any issues.
> 
> The team are working on the ME update, and that will take longer. I'm keeping the internal ticket open to monitor that release and will update here when available.

Can we have an update please?
Still sitting around with 16.1.27, and its december 2024.
The E16 Gen1 cannot be updated like other models with a "standard" ME.

**Comment by mrhpearson** [comment]
ME is under test - ETA is 10th December (and may take some time after that to be released to LVFS).

**Comment by mrhpearson** [comment]
FW is available now.

**Comment by mrhpearson** [comment]
Sorry - small correction because I can't read :(

The release is out for the E16 G2 - but is still in test for E16 G1. Should be done soon (fingers crossed).
Will update when that's out.

**Comment by mrhpearson** [comment]
OK - E16 G1/E14 G5 ME firmwre is now on LVFS. You should be good to go.
I'll close the ticket, but let me know if any issues.

**Comment by hughsie** [comment]
@mrhpearson anything I can do to smooth this? e.g. any automation you could need on the LVFS or any kind of automated reminder that would be useful? I'm *guessing* this is a person problem, not a _technical_ problem.

**Comment by mrhpearson** [comment]
Right - it was a process problem and nothing LVFS related - all on the Lenovo side.
Changes have been made that _should_ reduce the likelihood of it happening, but we'll find out next year how successful they are.
Note - there will still be a small delay between the Lenovo site and LVFS getting the updates, just because of how the FW team serialise the updates rather than doing them in parallel. Fixing that is going to take quite a bit longer I'm afraid. The more people that buy the Linux preload will help a lot ;)

**Comment by hughsie** [comment]
> just because of how the FW team serialise the updates rather than doing them in parallel

If it's useful, there is an endpoint you can hit with curl/python that uploads the firmware -- although I'm guessing that's not the bottleneck here.
