### ISSUE TITLE
[Lenovo ThinkBook] FWUPD Request to Lenovo

### ISSUE THREAD

**Issue by Cyber-Typhoon** [fwupd/firmware-lenovo#474]
Hi -

I see the thinkpad and even legion family of firmware available in the FWUPD. Can Lenovo please add Thinkbook firmware updates in the FWUPD too?

Thanks

**Comment by hughsie** [comment]
I don't think it's in the Linux support agreement, but I can ask Mark for a more public statement.

**Comment by mrhpearson** [comment]
I can't take this as a general request I'm afraid (sadly). 

If a platform is in our certified Linux program (www.lenovo.com/linux) then doing FW updates on LVFS is a requirement - and if the FW team aren't delivering those I do have a hammer I can use (with a caveat that for older platforms the hammer is sometimes replaced with a foam noodle...)

We do certify some Thinkbooks - but not the whole portfolio. So it's a bit platform by platform I'm afraid.

**Comment by Danny3** [comment]
If Lenovo wants me, and the people I help with hardware purchases, to choose their laptops, they must add support for firmware updates over LVFS!

Otherwise, I will still choose, for me and the people I help, Dell and other vendors that properly support Linux!

**Comment by Cyber-Typhoon** [comment]
> We do certify some Thinkbooks - but not the whole portfolio. So it's a bit platform by platform I'm afraid.

Could you please point which Thinkbook model has support?

I'm afraid this maybe isn't even the case. Please consider escalate this request with Lenovo so we have future models supported. If we don't bring those customers requests I'm afraid we will never see improvements.

**Comment by mrhpearson** [comment]
Check www.lenovo.com/linux for which platforms have been certified with Linux. We keep that page up to date as certification completes.

**Comment by Cyber-Typhoon** [comment]
As I mentioned, no ThinkBooks so, prior information that there are ThinkBooks supported is incorrect.

**Comment by mrhpearson** [comment]
Huh...that's strange. Not sure why they've not been added, I'll ask the team to check and update the page in the New Year
.
As an alternative you can see which Thinkbooks have been Ubuntu certified:
https://ubuntu.com/certified/laptops?q=thinkbook&limit=20&category=Laptop

**Comment by Cyber-Typhoon** [comment]
Quite weird, the ThinkBooks are a single yearly new hardware release rollout. Different from Thinkpads, keeping the fwupd support for it should be a smooth generation path. What is the criteria to skip a gen? Why not have support for the new gens? Thinkbook 14 gen 6 for example. Next year we should have gen 8 and how we can find out if it will have support? 
https://psref.lenovo.com/Product/ThinkBook/ThinkBook_14_G8_IRL
What is the agreement and commitment that Lenovo is putting of getting Linux onboard of the Thinkbook customers? Should we just avoid Thinkbooks and aim to get Thinkpads because it is officially guaranteed that it will have support?

**Comment by Danny3** [comment]
Well since, proper Linux support seems to be ignored or avoided, I have decided that from now on for new purchases I will start with the Framework laptop and the ones that KDE recommends:
https://kde.org/hardware/

Thanks Lenovo for not caring at all about proper security and Linux support!

**Comment by hughsie** [comment]
@Danny3 I'm not sure that's completely fair; Lenovo are one of the biggest uploaders to the LVFS now.

**Comment by Danny3** [comment]
> [@Danny3](https://github.com/Danny3) I'm not sure that's completely fair; Lenovo are one of the biggest uploaders to the LVFS now.

Hmm, it seems you are right:
https://fwupd.org/lvfs/vendors/
The only thing I have to do now is to meet with 2 friends I helped buy Lenovo laptops on which I've helped them install Linux + Windows in duall-boot mode.
I need to see if their laptops got any firmwares through LVFS before I make my mind completely about this vendor for future purchases and recommendations.

**Comment by Heavygrass** [comment]
Would like to request FWUPD support  for Thinkbook 14 g7 ARP (with Ryzen).

**Comment by hughsie** [comment]
@Heavygrass is that model currently listed on http://www.lenovo.com/linux ? Depending on the answer will change what I ask you to do :)

**Comment by Heavygrass** [comment]
> is that model currently listed on http://www.lenovo.com/linux ?

A simple CTRL+F search shows there's still **not a single thinkbook** listed (at least in the "Notebooks and Laptops" section), so no.

**Comment by mrhpearson** [comment]
Hi @Heavygrass - best I can recommend is to go on the Lenovo site and leave feedback - there should be a link at the bottom of the page
Or put a topic on the Thinkbook forums (maybe here: https://forums.lenovo.com/t5/ThinkBook-Laptops/bd-p/tb01_en ?) letting them know you want Linux support.
Whilst I can let them know there's a request - it's better if they hear directly from customers. I'm a bit of a biased resource.

We have certified a few Thinkbooks, but admittedly not many. Not sure why they aren't on that page - I asked for them to be added. I'll check on that.

Mark

**Comment by Cyber-Typhoon** [comment]
> best I can recommend is to go on the Lenovo site and leave feedback

I'd like to invite you to try that. Please go to Lenovo US website, go to the bottom of the page, click in "Provide Feedback" and please let us know the result. 

Can we maybe do a petition in some place? Is there some entity that can really hear the consumer and help us for real? Do we need to create some sort of brand shame to get their attention on this?

Posted on Lenovo's forum: https://forums.lenovo.com/t5/Other-Linux-Discussions/Why-Lenovo-supports-Linux-Firmware-updates-for-Thinkpads-and-not-Thinkbooks/m-p/10014397?page=1#10050945

Thanks for the guidance and patient.

**Comment by mrhpearson** [comment]
Saw your posting in the forum - I'll reply there but as a note you posted it in the Linux pages so you're going to hit the Linux team and not the Thinkbook team. It should get picked up and analysed by the Lenovo tools at least.
Confirmed the Feedback tool is broken (Gah!) - I'll let the web team know about that.

I did also get an update as to why we don't list the previously Ubuntu certified Thinkbooks on the lenovo.com/linux page - I'd actually forgotten the reason. I asked for them to be pulled from the page a while back - because of lack of LVFS updates. There are some long (and frankly poor) reasons for that, related to internal process and product requirement specs - but it was a miss, and they didn't/couldn't fix it. This means they aren't recommended as systems for Linux users.

The requirements are fixed for future platforms - but I'm not allowed to comment on which platforms exactly that will be I'm afraid.

I'll comment on the brand shame and other parts on the forum - as that's not LVFS related.

**Comment by Cyber-Typhoon** [comment]
> but as a note you posted it in the Linux pages

No, it was moved by Lenovo's moderation. I posted in the Thinkbook forum. 

> Confirmed the Feedback tool is broken (Gah!) - I'll let the web team know about that.

This kind of tells me how much they care about feedback.

> because of lack of LVFS updates

Lenovo really don't care about Thinkbook Linux support.

**Comment by Cyber-Typhoon** [comment]
Not sure if this helps in something but the Lenovo Page for the BIOS mentions only Win 10 and Win 11, which I think confirms that we don't have a Linux option: https://newthink.lenovo.com.cn/driveList.html?selname=21TK0002CD

https://think.lenovo.com.cn/support/driver/driverdetail.aspx?DEditid=150656
