### ISSUE TITLE
Missing Firmware Intel ME 11.8 on ThinkPad X1 Yoga 3rd Gen

### ISSUE THREAD

**Issue by fuufdiji** [fwupd/firmware-lenovo#48]
For missing firmware please provide the following items:

* Link to firmware update at OEM website 

https://pcsupport.lenovo.com/us/de/products/laptops-and-netbooks/thinkpad-x-series-laptops/thinkpad-x1-yoga-3rd-gen-type-20ld-20le-20lf-20lg/downloads/driver-list/component?name=Chipset

* Firmware release date (if available on OEM website)

04 May 2020

* Link to the device page on LVFS

https://cdn.fwupd.org/lvfs/devices/com.lenovo.ThinkPadN25RN.firmware

OEM also has Intel ME 12.0 (as opposed to ME 11.8), i.e. version 2014.14.0.1540 from 13 May 2020. Not sure if a big version jump is shipped as a normal update.

**Comment by kmauleon** [comment]
Closing... please refer to latest version links as below.  thank you very much.

[ThinkPad X1 Yoga 3rd Consumer ME Update](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN25RN.firmware)
Vendor: Lenovo (ThinkPad)
Latest Version: 184.92.4222

[ThinkPad X1 Yoga 3rd Corporate ME Update](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN25RM.firmware)
Vendor: Lenovo (ThinkPad)
Latest Version: 184.92.4222
