### ISSUE TITLE
Lenovo X1 Nano Gen 1 - Failed to recover ME Firmware

### ISSUE THREAD

**Issue by patrickdoern** [fwupd/firmware-lenovo#482]
Hello, 

I have the same problem with a Lenovo ThinkPad X1 Nano with BIOS version N2TET86W 1.64 as described in the following link: https://github.com/fwupd/firmware-lenovo/issues/458

![devicemanager](https://github.com/user-attachments/assets/38ec1e7d-104f-46bf-aeda-aa7ae6072f70)
![vantage](https://github.com/user-attachments/assets/ebe69a58-7d09-4653-a344-5fd2d6a998c3)

Can you help me?

Kind regards
Patrick

**Comment by hughsie** [comment]
@patrickdoern did you use fwupd to install the firmware?

**Comment by patrickdoern** [comment]
I use Lenovo Vantage Commercial on Windows 11

**Comment by hughsie** [comment]
Then I think you need to contact Lenovo support I'm afraid; this issue tracker is for fwupd/LVFS issued updates only.
