### ISSUE TITLE
X1 Carbon 2-in-1 Gen 9: Intel BootGuard OTP fuse: Unlocked

### ISSUE THREAD

**Issue by mcatanzaro** [fwupd/firmware-lenovo#485]
I have the following unsatisfactory `fwupdmgr security` report for a new X1 Carbon 2-in-1 Gen 9:

```
$ fwupdmgr security
Host Security ID: HSI:1 (v1.9.26)

HSI-1
✔ BIOS firmware updates:         Enabled
✔ MEI key manifest:              Valid
✔ MEI manufacturing mode:        Locked
✔ csme18 override:               Locked
✔ csme18 v0:18.0.5.2098:         Valid
✔ Platform debugging:            Disabled
✔ SPI write:                     Disabled
✔ SPI lock:                      Enabled
✔ SPI BIOS region:               Locked
✔ Supported CPU:                 Valid
✔ TPM empty PCRs:                Valid
✔ TPM v2.0:                      Found
✔ UEFI bootservice variables:    Locked
✔ UEFI platform key:             Valid
✔ UEFI secure boot:              Enabled

HSI-2
✔ BIOS rollback protection:      Enabled
✔ Intel BootGuard ACM protected: Valid
✔ Intel BootGuard:               Enabled
✔ IOMMU:                         Enabled
✔ Platform debugging:            Locked
✔ TPM PCR0 reconstruction:       Valid
✘ Intel BootGuard OTP fuse:      Unlocked

HSI-3
✔ CET Platform:                  Supported
✔ Pre-boot DMA protection:       Enabled
✔ Suspend-to-idle:               Enabled
✔ Suspend-to-ram:                Disabled

HSI-4
✔ SMAP:                          Enabled
✘ Encrypted RAM:                 Not supported

Runtime Suffix -!
✔ fwupd plugins:                 Untainted
✔ CET OS Support:                Supported
✔ Linux kernel lockdown:         Enabled
✔ Linux swap:                    Encrypted
✔ Linux kernel:                  Untainted
```

The report is the same after installing available firmware updates (Embedded Controller 0.1.22 -> 0.1.24 and System Firmware 0.1.29 -> 0.1.36). We should try to figure out what's wrong here:

```
✘ Intel BootGuard OTP fuse:      Unlocked
```

(And ideally within my return window, because Richard famously advises to return any laptop that cannot meet HSI-2. :)

**Comment by hughsie** [comment]
Is this a dupe of https://github.com/fwupd/fwupd/issues/7180 perhaps?

**Comment by mcatanzaro** [comment]
No, because the test results are completely different. Notably that bug shows `✔ Intel BootGuard OTP fuse:      Valid`

**Comment by mcatanzaro** [comment]
Ah, wait, after reading past the discussion on memory encryption, I see https://github.com/fwupd/fwupd/issues/7180#issuecomment-2415195263 which looks the same as my results. But at this point, it seems like a completely different bug than what was originally reported, since all of the original problems are fixed!

It's definitely the same problem as [here](https://github.com/fwupd/fwupd/issues/7180#issuecomment-2508382122).

So it might be pragmatic to mark my issue as a duplicate of that one after all.

**Comment by hughsie** [comment]
Right, dupe of https://github.com/fwupd/fwupd/issues/7180#issuecomment-2508382122 I think. Lets carry on there.

**Comment by mcatanzaro** [comment]
Responding here just to avoid spamming the other issue with humor: I have built fwupd git main, captured a debug log, stared it in in confusion for a while trying to figure out why it's missing the Intel BootGuard information you're looking for, and only then finally did I realize I should probably test on the affected laptop instead of my AMD workstation....

**Comment by mcatanzaro** [comment]
Um, actually hughsie, I'm not sure it's the same issue after all. Because after building git main and running `./src/fwupdtool get-plugins -vv --plugins pci-mei` I have the almost the same result on the affected Intel laptop as I do on AMD:

```
FuPciMeiPlugin:
  Name:                 pci_mei
  Flags:                ready
  PciDevice:            5fed1486be004d67ea79838d2e83aaa11bb72645
  Family:               unknown
  Issue:                unknown
```

(The only difference is the AMD workstation doesn't have the PciDevice line.)

I'll attach the entire log, but it seems to be missing all of the info you were looking for. I had been expecting the debug output would look similar to what Iyán attached in #7180, and that I should next modify fwupd to add extra debug that you requested. But seems that's not going to work. Here's the log:

[debug.log](https://github.com/user-attachments/files/18030216/debug.log)

CC @siwei-luo because I think we have the same problem and same hardware.

**Comment by mcatanzaro** [comment]
Oh sorry again, problem was just that I need to run as root. Now I see similar output to the other user, and I'm also missing Hfsts3. Will continue in https://github.com/fwupd/fwupd/issues/7180.
