### ISSUE TITLE
Update fails on ubuntu 20 T460s

### ISSUE THREAD

**Issue by NadirDerradj** [fwupd/firmware-lenovo#49]
After updating the firmware from software center and reboot it was blocked on this screen any help 

LENOVO

INSTALLING FIRMWARE UPDATE .....

**Comment by kmauleon** [comment]
Hi NadirDerradj...
Thank you very much for your attention.  Can you please show results for the below command...
fwupdmgr get-devices

**Comment by kmauleon** [comment]
target to release new versions by november... please wait...thank you very much

**Comment by kmauleon** [comment]
hi @NadirDerradj please try with latest MEFW... thank you very much
    Corporate (VPro) >> https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN1CRM.firmware
    Consumer (NonVPro) >> https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN1CRN.firmware

**Comment by kmauleon** [comment]
hi @NadirDerradj latest 11.8.80.3746 is available already.  please check with this.  thank you very much.
Corporate >> https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN1CRM.firmware
Consumer >> https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN1CRN.firmware

**Comment by kmauleon** [comment]
Closing this as BIOS ESRT fix has been rolled out already.  Please reopen if you still see the problem.  Thank you very much.
