### ISSUE TITLE
Looking for old firmware versions for X1 Yoga Gen 4

### ISSUE THREAD

**Issue by tberghuis** [fwupd/firmware-lenovo#73]
Linux will freeze unless I run with kernel parameter nomodeset. Want to rule out if latest firmware is causing the problem.

**Comment by kmauleon** [comment]
hi @tberghuis what firmware are you looking for?

**Comment by kmauleon** [comment]
please check LVFS site for available firmware >> https://fwupd.org/lvfs/search?value=X1+Yoga+4th

**Comment by tberghuis** [comment]
Thanks

**Comment by kmauleon** [comment]
pleasure ^_^
