### ISSUE TITLE
UEFI Firmware for T490s is missing / EC & ME FW outdated

### ISSUE THREAD

**Issue by der-eismann** [fwupd/firmware-lenovo#77]
Hey everyone,

It's me again. While showing my colleagues the capabilities of fwupd we noticed that the BIOS files for their T490s are completely missing on the LVFS website, others are outdated.

**UEFI Update**

Here's the `fwupd get-devices` output for the UEFI part:
```
├─System Firmware:
│     Device ID:           ca8e899e46f1da1776d16410bc92f2cf0d963433
│     Current version:     0.1.55
│     Vendor:              LENOVO (DMI:LENOVO)
│     GUID:                6300ba52-d9ea-4ca0-88f9-f89ef73cc07b
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Supported on remote server
│                          • Needs a reboot after installation
│                          • Cryptographic hash verification is available
│                          • Device is usable for the duration of the update
```

As mentioned before this is completely missing on the LVFS website at the moment, but the current firmware 1.70 is available as a *.cab file via the [T490s download page](https://pcsupport.lenovo.com/de/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t490s-type-20nx-20ny/downloads/DS539062).
What's interesting is that the output of `fwupd get-updates` says `• System Firmware has the latest available firmware version` instead of `has no available firmware updates`, so maybe it's hidden on the LVFS?

**Embedded Controller Firmware**

This one is outdated and also doesn't get recognized. On the [T490s download page](https://pcsupport.lenovo.com/de/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t490s-type-20nx-20ny/downloads/DS539062) there's version 1.20 available, on the LVFS it's [still 1.19](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2JHT.firmware). I'm also not sure what the `ThinkPad T490s/Fx390` in the title should mean. Is there a ThinkPad Fx390? The X390 has a different EC FW.
Here's the `fwupd get-devices` output again:
```
├─UEFI Device Firmware:
│     Device ID:           09ce7908b2d90a3b53473c3f328410590a527f29
│     Current version:     0.1.15
│     Minimum Version:     0.1.15
│     Vendor:              DMI:LENOVO
│     GUID:                be9a5f93-930b-40bf-8864-815268ea4ea3
│     Device Flags:        • Internal device
│                          • Updatable
│                          • Requires AC power
│                          • Supported on remote server
│                          • Needs a reboot after installation
│                          • Device is usable for the duration of the update
```
But when executing `fwupd get-updates` the newer 1.19 isn't shown, there's only this block (makes it hard to identify which device is which):
```
• UEFI Device Firmware has the latest available firmware version
• UEFI Device Firmware has the latest available firmware version
• UEFI Device Firmware has no available firmware updates
• UEFI Device Firmware has no available firmware updates
```

**ME Firmware**

Severely outdated! In this case there is version 12.0.68.1606 available on the [download page](https://pcsupport.lenovo.com/de/en/products/laptops-and-netbooks/thinkpad-t-series-laptops/thinkpad-t490s-type-20nx-20ny/downloads/DS539850) while the LVFS is still on 12.0.47.1524 ([consumer](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2JRN.firmware) & [corporate](https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2JRM.firmware)). The LVFS version was released in October 2019 and there were four new versions published since then.

**Comment by kmauleon** [comment]
hi @der-eismann thank you very much for the information... calling the attention of the owner....

**Comment by kmauleon** [comment]
target to release new versions by november...please wait...thank you very much

**Comment by der-eismann** [comment]
Thanks for the update, I'll keep an eye on it!

**Comment by joakim-tjernlund** [comment]
Great, I am also looking forward to T490s updates

**Comment by kmauleon** [comment]
hi latest MEFW already available please check >> https://fwupd.org/lvfs/search?value=T490s
As for BIOS/EC, will follow-up owner.  thank you very much....

**Comment by der-eismann** [comment]
It's getting better, on the LVFS we have BIOS 1.70 while on the Lenovo page BIOS 1.71 is offered since 02 Feb 2021. EC and ME FW are the latest version. I don't really understand the delay or release cycles of this, but it's improving.

**Comment by kmauleon** [comment]
hi all... latest BIOS uploaded here >> https://fwupd.org/lvfs/devices/com.lenovo.ThinkPadN2JETXXP.firmware
closing this ticket... thank you very much.
